-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv_bn_relu_Block_entry352_proc1_Pipeline_VITIS_LOOP_141_11 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem2_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_WREADY : IN STD_LOGIC;
    m_axi_gmem2_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RVALID : IN STD_LOGIC;
    m_axi_gmem2_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_RLAST : IN STD_LOGIC;
    m_axi_gmem2_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem2_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BVALID : IN STD_LOGIC;
    m_axi_gmem2_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    zext_ln87_21 : IN STD_LOGIC_VECTOR (16 downto 0);
    mul_ln87_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln87_13 : IN STD_LOGIC_VECTOR (15 downto 0);
    shl_ln1027_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bound57 : IN STD_LOGIC_VECTOR (95 downto 0);
    local_conv_kernel_blk_11_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_11_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_11_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_conv_kernel_blk_10_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_10_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_10_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_conv_kernel_blk_9_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_9_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_9_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_conv_kernel_blk_8_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_8_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_8_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_conv_kernel_blk_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_7_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_7_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_conv_kernel_blk_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_6_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_6_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_conv_kernel_blk_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_5_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_5_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_conv_kernel_blk_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_4_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_4_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_conv_kernel_blk_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_3_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_3_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_conv_kernel_blk_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_2_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_2_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_conv_kernel_blk_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_1_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_1_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_conv_kernel_blk_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_conv_kernel_blk_ce0 : OUT STD_LOGIC;
    local_conv_kernel_blk_we0 : OUT STD_LOGIC;
    local_conv_kernel_blk_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    zext_ln87_19 : IN STD_LOGIC_VECTOR (15 downto 0);
    kernel_size : IN STD_LOGIC_VECTOR (7 downto 0);
    icmp_ln1027_16 : IN STD_LOGIC_VECTOR (0 downto 0);
    mul_ln87_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    icmp_ln1027_17 : IN STD_LOGIC_VECTOR (0 downto 0);
    conv_kernel : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of conv_bn_relu_Block_entry352_proc1_Pipeline_VITIS_LOOP_141_11 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv96_0 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv96_1 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal or_ln1027_3_reg_1168 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_3_reg_1168_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1027_1_reg_1181 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1027_1_reg_1181_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op165_readreq_state6 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln138_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem2_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem2_blk_n_AR : STD_LOGIC;
    signal first_iter_1_reg_409 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_11_reg_420 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln87_19_cast_fu_432_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln87_19_cast_reg_1127 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln87_13_cast_fu_436_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln87_13_cast_reg_1132 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln138_reg_1143 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_reg_1143_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_reg_1143_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_reg_1147 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_reg_1147_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_reg_1147_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_fu_591_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_2_reg_1154_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln138_4_fu_624_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln138_4_reg_1158 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln138_4_reg_1158_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln138_4_reg_1158_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_3_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_3_reg_1168_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_3_reg_1168_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_149_fu_770_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172_pp0_iter10_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172_pp0_iter11_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_149_reg_1172_pp0_iter12_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln1027_7_fu_780_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_7_reg_1177_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1027_1_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1027_1_reg_1181_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1027_1_reg_1181_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln146_fu_808_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln146_reg_1186_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln138_fu_884_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln138_reg_1190 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln138_1_fu_894_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln138_1_reg_1195 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln138_fu_910_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln138_reg_1200 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln138_1_fu_914_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln138_1_reg_1206 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln140_mid2_v_reg_1212 : STD_LOGIC_VECTOR (61 downto 0);
    signal bitcast_ln146_fu_993_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln146_reg_1227 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter4_stage0 : STD_LOGIC;
    signal ap_phi_mux_first_iter_1_phi_fu_413_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_phi_mux_first_iter_11_phi_fu_424_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_cast1_fu_997_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln1027_1_fu_977_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal kw_fu_144 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln141_fu_812_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal kh_fu_148 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1027_8_fu_800_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten21_fu_152 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1027_9_fu_824_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_in_fu_156 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1027_1_fu_667_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal indvar_flatten45_fu_160 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1027_10_fu_838_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_out_fu_164 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln138_2_fu_565_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln87_21_cast_fu_440_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar3863_fu_168 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln138_5_fu_898_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten109_fu_172 : STD_LOGIC_VECTOR (95 downto 0);
    signal add_ln138_2_fu_522_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal icmp_ln1027_fu_540_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln138_fu_534_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast146_mid2_v_fu_573_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_fu_513_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln138_fu_595_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_1_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_2_fu_619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln138_fu_545_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln138_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_1_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln138_1_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln139_2_fu_631_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_583_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_147_fu_675_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_148_fu_679_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_503_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal and_ln138_fu_601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1027_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln138_3_fu_612_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_fu_649_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1027_4_fu_713_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_2_fu_657_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_4_fu_732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_5_fu_738_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln140_fu_720_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_mid1_fu_752_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln1027_3_fu_693_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_685_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln1027_6_fu_762_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_150_fu_776_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1027_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1027_fu_637_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1027_1_fu_788_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1027_5_fu_744_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1027_1_fu_818_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1027_2_fu_832_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln138_1_fu_888_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_1012_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1019_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln138_1_fu_922_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln139_3_fu_927_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln139_fu_918_p2 : STD_LOGIC_VECTOR (31 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln139_fu_918_p2 : signal is "no";
    signal add_ln139_5_fu_931_p2 : STD_LOGIC_VECTOR (31 downto 0);
    attribute use_dsp48 of add_ln139_5_fu_931_p2 : signal is "no";
    signal select_ln138_6_fu_936_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1027_2_fu_943_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln140_mid2_v_v_v_v_v_fu_950_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln1027_fu_958_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln1027_fu_962_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_1012_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1012_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1019_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1019_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1012_ce : STD_LOGIC;
    signal grp_fu_1019_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_1012_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1019_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv_bn_relu_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv_bn_relu_mac_muladd_16ns_16ns_32ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv_bn_relu_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_1_1_U63 : component conv_bn_relu_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => trunc_ln138_reg_1190,
        din1 => mul_ln87_5,
        dout => mul_ln138_fu_910_p2);

    mul_32s_32s_32_1_1_U64 : component conv_bn_relu_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => trunc_ln138_1_reg_1195,
        din1 => mul_ln87_5,
        dout => mul_ln138_1_fu_914_p2);

    mac_muladd_16ns_16ns_32ns_32_4_1_U65 : component conv_bn_relu_mac_muladd_16ns_16ns_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1012_p0,
        din1 => grp_fu_1012_p1,
        din2 => shl_ln1027_1,
        ce => grp_fu_1012_ce,
        dout => grp_fu_1012_p3);

    mac_muladd_16ns_16ns_32ns_32_4_1_U66 : component conv_bn_relu_mac_muladd_16ns_16ns_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1019_p0,
        din1 => grp_fu_1019_p1,
        din2 => shl_ln1027_1,
        ce => grp_fu_1019_ce,
        dout => grp_fu_1019_p3);

    flow_control_loop_pipe_sequential_init_U : component conv_bn_relu_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0)) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    c_in_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_in_fu_156 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_517_p2 = ap_const_lv1_0))) then 
                    c_in_fu_156 <= select_ln1027_1_fu_667_p3;
                end if;
            end if; 
        end if;
    end process;

    c_out_fu_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_out_fu_164 <= zext_ln87_21_cast_fu_440_p1;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_517_p2 = ap_const_lv1_0))) then 
                    c_out_fu_164 <= select_ln138_2_fu_565_p3;
                end if;
            end if; 
        end if;
    end process;

    first_iter_11_reg_420_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln138_reg_1143 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                first_iter_11_reg_420 <= ap_const_lv1_0;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                first_iter_11_reg_420 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    first_iter_1_reg_409_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln138_reg_1143 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                first_iter_1_reg_409 <= and_ln1027_1_reg_1181;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                first_iter_1_reg_409 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    indvar3863_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    indvar3863_fu_168 <= ap_const_lv64_0;
                elsif (((icmp_ln138_reg_1143 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    indvar3863_fu_168 <= select_ln138_5_fu_898_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten109_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten109_fu_172 <= ap_const_lv96_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_517_p2 = ap_const_lv1_0))) then 
                    indvar_flatten109_fu_172 <= add_ln138_2_fu_522_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten21_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten21_fu_152 <= ap_const_lv16_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_517_p2 = ap_const_lv1_0))) then 
                    indvar_flatten21_fu_152 <= select_ln1027_9_fu_824_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten45_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten45_fu_160 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_517_p2 = ap_const_lv1_0))) then 
                    indvar_flatten45_fu_160 <= select_ln1027_10_fu_838_p3;
                end if;
            end if; 
        end if;
    end process;

    kh_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    kh_fu_148 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_517_p2 = ap_const_lv1_0))) then 
                    kh_fu_148 <= select_ln1027_8_fu_800_p3;
                end if;
            end if; 
        end if;
    end process;

    kw_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    kw_fu_144 <= ap_const_lv8_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln138_fu_517_p2 = ap_const_lv1_0))) then 
                    kw_fu_144 <= add_ln141_fu_812_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_517_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln1027_1_reg_1181 <= and_ln1027_1_fu_794_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln1027_1_reg_1181_pp0_iter2_reg <= and_ln1027_1_reg_1181;
                and_ln1027_1_reg_1181_pp0_iter3_reg <= and_ln1027_1_reg_1181_pp0_iter2_reg;
                and_ln1027_1_reg_1181_pp0_iter4_reg <= and_ln1027_1_reg_1181_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                bitcast_ln146_reg_1227 <= bitcast_ln146_fu_993_p1;
                empty_149_reg_1172_pp0_iter10_reg <= empty_149_reg_1172_pp0_iter9_reg;
                empty_149_reg_1172_pp0_iter11_reg <= empty_149_reg_1172_pp0_iter10_reg;
                empty_149_reg_1172_pp0_iter12_reg <= empty_149_reg_1172_pp0_iter11_reg;
                empty_149_reg_1172_pp0_iter2_reg <= empty_149_reg_1172;
                empty_149_reg_1172_pp0_iter3_reg <= empty_149_reg_1172_pp0_iter2_reg;
                empty_149_reg_1172_pp0_iter4_reg <= empty_149_reg_1172_pp0_iter3_reg;
                empty_149_reg_1172_pp0_iter5_reg <= empty_149_reg_1172_pp0_iter4_reg;
                empty_149_reg_1172_pp0_iter6_reg <= empty_149_reg_1172_pp0_iter5_reg;
                empty_149_reg_1172_pp0_iter7_reg <= empty_149_reg_1172_pp0_iter6_reg;
                empty_149_reg_1172_pp0_iter8_reg <= empty_149_reg_1172_pp0_iter7_reg;
                empty_149_reg_1172_pp0_iter9_reg <= empty_149_reg_1172_pp0_iter8_reg;
                icmp_ln1027_reg_1147_pp0_iter2_reg <= icmp_ln1027_reg_1147;
                icmp_ln1027_reg_1147_pp0_iter3_reg <= icmp_ln1027_reg_1147_pp0_iter2_reg;
                icmp_ln138_reg_1143_pp0_iter2_reg <= icmp_ln138_reg_1143;
                icmp_ln138_reg_1143_pp0_iter3_reg <= icmp_ln138_reg_1143_pp0_iter2_reg;
                mul_ln138_reg_1200 <= mul_ln138_fu_910_p2;
                or_ln1027_3_reg_1168_pp0_iter2_reg <= or_ln1027_3_reg_1168;
                or_ln1027_3_reg_1168_pp0_iter3_reg <= or_ln1027_3_reg_1168_pp0_iter2_reg;
                or_ln1027_3_reg_1168_pp0_iter4_reg <= or_ln1027_3_reg_1168_pp0_iter3_reg;
                select_ln1027_7_reg_1177_pp0_iter10_reg <= select_ln1027_7_reg_1177_pp0_iter9_reg;
                select_ln1027_7_reg_1177_pp0_iter11_reg <= select_ln1027_7_reg_1177_pp0_iter10_reg;
                select_ln1027_7_reg_1177_pp0_iter12_reg <= select_ln1027_7_reg_1177_pp0_iter11_reg;
                select_ln1027_7_reg_1177_pp0_iter2_reg <= select_ln1027_7_reg_1177;
                select_ln1027_7_reg_1177_pp0_iter3_reg <= select_ln1027_7_reg_1177_pp0_iter2_reg;
                select_ln1027_7_reg_1177_pp0_iter4_reg <= select_ln1027_7_reg_1177_pp0_iter3_reg;
                select_ln1027_7_reg_1177_pp0_iter5_reg <= select_ln1027_7_reg_1177_pp0_iter4_reg;
                select_ln1027_7_reg_1177_pp0_iter6_reg <= select_ln1027_7_reg_1177_pp0_iter5_reg;
                select_ln1027_7_reg_1177_pp0_iter7_reg <= select_ln1027_7_reg_1177_pp0_iter6_reg;
                select_ln1027_7_reg_1177_pp0_iter8_reg <= select_ln1027_7_reg_1177_pp0_iter7_reg;
                select_ln1027_7_reg_1177_pp0_iter9_reg <= select_ln1027_7_reg_1177_pp0_iter8_reg;
                select_ln138_4_reg_1158_pp0_iter2_reg <= select_ln138_4_reg_1158;
                select_ln138_4_reg_1158_pp0_iter3_reg <= select_ln138_4_reg_1158_pp0_iter2_reg;
                trunc_ln138_2_reg_1154_pp0_iter10_reg <= trunc_ln138_2_reg_1154_pp0_iter9_reg;
                trunc_ln138_2_reg_1154_pp0_iter11_reg <= trunc_ln138_2_reg_1154_pp0_iter10_reg;
                trunc_ln138_2_reg_1154_pp0_iter12_reg <= trunc_ln138_2_reg_1154_pp0_iter11_reg;
                trunc_ln138_2_reg_1154_pp0_iter2_reg <= trunc_ln138_2_reg_1154;
                trunc_ln138_2_reg_1154_pp0_iter3_reg <= trunc_ln138_2_reg_1154_pp0_iter2_reg;
                trunc_ln138_2_reg_1154_pp0_iter4_reg <= trunc_ln138_2_reg_1154_pp0_iter3_reg;
                trunc_ln138_2_reg_1154_pp0_iter5_reg <= trunc_ln138_2_reg_1154_pp0_iter4_reg;
                trunc_ln138_2_reg_1154_pp0_iter6_reg <= trunc_ln138_2_reg_1154_pp0_iter5_reg;
                trunc_ln138_2_reg_1154_pp0_iter7_reg <= trunc_ln138_2_reg_1154_pp0_iter6_reg;
                trunc_ln138_2_reg_1154_pp0_iter8_reg <= trunc_ln138_2_reg_1154_pp0_iter7_reg;
                trunc_ln138_2_reg_1154_pp0_iter9_reg <= trunc_ln138_2_reg_1154_pp0_iter8_reg;
                trunc_ln138_reg_1190 <= trunc_ln138_fu_884_p1;
                trunc_ln146_reg_1186_pp0_iter10_reg <= trunc_ln146_reg_1186_pp0_iter9_reg;
                trunc_ln146_reg_1186_pp0_iter11_reg <= trunc_ln146_reg_1186_pp0_iter10_reg;
                trunc_ln146_reg_1186_pp0_iter12_reg <= trunc_ln146_reg_1186_pp0_iter11_reg;
                trunc_ln146_reg_1186_pp0_iter2_reg <= trunc_ln146_reg_1186;
                trunc_ln146_reg_1186_pp0_iter3_reg <= trunc_ln146_reg_1186_pp0_iter2_reg;
                trunc_ln146_reg_1186_pp0_iter4_reg <= trunc_ln146_reg_1186_pp0_iter3_reg;
                trunc_ln146_reg_1186_pp0_iter5_reg <= trunc_ln146_reg_1186_pp0_iter4_reg;
                trunc_ln146_reg_1186_pp0_iter6_reg <= trunc_ln146_reg_1186_pp0_iter5_reg;
                trunc_ln146_reg_1186_pp0_iter7_reg <= trunc_ln146_reg_1186_pp0_iter6_reg;
                trunc_ln146_reg_1186_pp0_iter8_reg <= trunc_ln146_reg_1186_pp0_iter7_reg;
                trunc_ln146_reg_1186_pp0_iter9_reg <= trunc_ln146_reg_1186_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln138_reg_1143 <= icmp_ln138_fu_517_p2;
                    zext_ln87_13_cast_reg_1132(15 downto 0) <= zext_ln87_13_cast_fu_436_p1(15 downto 0);
                    zext_ln87_19_cast_reg_1127(15 downto 0) <= zext_ln87_19_cast_fu_432_p1(15 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_517_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                empty_149_reg_1172 <= empty_149_fu_770_p2;
                icmp_ln1027_reg_1147 <= icmp_ln1027_fu_540_p2;
                or_ln1027_3_reg_1168 <= or_ln1027_3_fu_726_p2;
                select_ln1027_7_reg_1177 <= select_ln1027_7_fu_780_p3;
                select_ln138_4_reg_1158 <= select_ln138_4_fu_624_p3;
                trunc_ln138_2_reg_1154 <= trunc_ln138_2_fu_591_p1;
                trunc_ln146_reg_1186 <= trunc_ln146_fu_808_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln138_reg_1143_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                mul_ln138_1_reg_1206 <= mul_ln138_1_fu_914_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln138_reg_1143_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                sext_ln140_mid2_v_reg_1212 <= add_ln1027_fu_962_p2(63 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln138_reg_1143 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                trunc_ln138_1_reg_1195 <= trunc_ln138_1_fu_894_p1;
            end if;
        end if;
    end process;
    zext_ln87_19_cast_reg_1127(31 downto 16) <= "0000000000000000";
    zext_ln87_13_cast_reg_1132(31 downto 16) <= "0000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1027_1_fu_818_p2 <= std_logic_vector(unsigned(indvar_flatten21_fu_152) + unsigned(ap_const_lv16_1));
    add_ln1027_2_fu_832_p2 <= std_logic_vector(unsigned(indvar_flatten45_fu_160) + unsigned(ap_const_lv32_1));
    add_ln1027_fu_962_p2 <= std_logic_vector(signed(sext_ln1027_fu_958_p1) + signed(conv_kernel));
    add_ln138_1_fu_888_p2 <= std_logic_vector(unsigned(indvar3863_fu_168) + unsigned(ap_const_lv64_1));
    add_ln138_2_fu_522_p2 <= std_logic_vector(unsigned(indvar_flatten109_fu_172) + unsigned(ap_const_lv96_1));
    add_ln138_fu_534_p2 <= std_logic_vector(unsigned(c_out_fu_164) + unsigned(ap_const_lv64_1));
    add_ln139_2_fu_631_p2 <= std_logic_vector(unsigned(select_ln138_fu_545_p3) + unsigned(ap_const_lv16_1));
    add_ln139_3_fu_927_p2 <= std_logic_vector(unsigned(shl_ln1027_1) + unsigned(mul_ln138_1_reg_1206));
    add_ln139_5_fu_931_p2 <= std_logic_vector(unsigned(grp_fu_1019_p3) + unsigned(select_ln138_1_fu_922_p3));
    add_ln139_fu_918_p2 <= std_logic_vector(unsigned(grp_fu_1012_p3) + unsigned(mul_ln138_reg_1200));
    add_ln140_fu_720_p2 <= std_logic_vector(unsigned(select_ln1027_fu_649_p3) + unsigned(ap_const_lv8_1));
    add_ln141_fu_812_p2 <= std_logic_vector(unsigned(select_ln1027_5_fu_744_p3) + unsigned(ap_const_lv8_1));
    and_ln1027_1_fu_794_p2 <= (xor_ln1027_1_fu_788_p2 and or_ln1027_fu_637_p2);
    and_ln1027_fu_707_p2 <= (xor_ln1027_fu_701_p2 and and_ln138_fu_601_p2);
    and_ln138_fu_601_p2 <= (xor_ln138_fu_595_p2 and empty_fu_513_p1);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter12, m_axi_gmem2_RVALID, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (m_axi_gmem2_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter12, m_axi_gmem2_RVALID, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (m_axi_gmem2_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_io)));
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state13_pp0_stage0_iter12_assign_proc : process(m_axi_gmem2_RVALID)
    begin
                ap_block_state13_pp0_stage0_iter12 <= (m_axi_gmem2_RVALID = ap_const_logic_0);
    end process;

        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_io_assign_proc : process(m_axi_gmem2_ARREADY, ap_predicate_op165_readreq_state6)
    begin
                ap_block_state6_io <= ((m_axi_gmem2_ARREADY = ap_const_logic_0) and (ap_predicate_op165_readreq_state6 = ap_const_boolean_1));
    end process;

        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln138_fu_517_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_517_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter4_stage0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone, icmp_ln138_reg_1143_pp0_iter3_reg)
    begin
        if (((icmp_ln138_reg_1143_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter12_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_first_iter_11_phi_fu_424_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, first_iter_11_reg_420, icmp_ln138_reg_1143)
    begin
        if (((icmp_ln138_reg_1143 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_first_iter_11_phi_fu_424_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_first_iter_11_phi_fu_424_p4 <= first_iter_11_reg_420;
        end if; 
    end process;


    ap_phi_mux_first_iter_1_phi_fu_413_p4_assign_proc : process(ap_enable_reg_pp0_iter2, and_ln1027_1_reg_1181, ap_block_pp0_stage0, first_iter_1_reg_409, icmp_ln138_reg_1143)
    begin
        if (((icmp_ln138_reg_1143 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_first_iter_1_phi_fu_413_p4 <= and_ln1027_1_reg_1181;
        else 
            ap_phi_mux_first_iter_1_phi_fu_413_p4 <= first_iter_1_reg_409;
        end if; 
    end process;


    ap_predicate_op165_readreq_state6_assign_proc : process(or_ln1027_3_reg_1168_pp0_iter4_reg, and_ln1027_1_reg_1181_pp0_iter4_reg)
    begin
                ap_predicate_op165_readreq_state6 <= ((ap_const_lv1_1 = and_ln1027_1_reg_1181_pp0_iter4_reg) and (or_ln1027_3_reg_1168_pp0_iter4_reg = ap_const_lv1_1));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln146_fu_993_p1 <= m_axi_gmem2_RDATA;
    empty_147_fu_675_p1 <= select_ln1027_1_fu_667_p3(5 - 1 downto 0);
    empty_148_fu_679_p2 <= std_logic_vector(unsigned(tmp_1_fu_583_p3) + unsigned(empty_147_fu_675_p1));
    empty_149_fu_770_p2 <= std_logic_vector(unsigned(tmp_2_fu_685_p3) + unsigned(select_ln1027_6_fu_762_p3));
    empty_150_fu_776_p1 <= add_ln140_fu_720_p2(1 - 1 downto 0);
    empty_fu_513_p1 <= kh_fu_148(1 - 1 downto 0);

    gmem2_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_gmem2_ARREADY, ap_predicate_op165_readreq_state6, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op165_readreq_state6 = ap_const_boolean_1))) then 
            gmem2_blk_n_AR <= m_axi_gmem2_ARREADY;
        else 
            gmem2_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem2_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter12, m_axi_gmem2_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem2_blk_n_R <= m_axi_gmem2_RVALID;
        else 
            gmem2_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_1012_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_1012_ce <= ap_const_logic_1;
        else 
            grp_fu_1012_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1012_p0 <= grp_fu_1012_p00(16 - 1 downto 0);
    grp_fu_1012_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_in_fu_156),32));
    grp_fu_1012_p1 <= zext_ln87_13_cast_reg_1132(16 - 1 downto 0);

    grp_fu_1019_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_1019_ce <= ap_const_logic_1;
        else 
            grp_fu_1019_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1019_p0 <= grp_fu_1019_p00(16 - 1 downto 0);
    grp_fu_1019_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln139_2_fu_631_p2),32));
    grp_fu_1019_p1 <= zext_ln87_13_cast_reg_1132(16 - 1 downto 0);
    icmp_ln1027_1_fu_607_p2 <= "1" when (kw_fu_144 = kernel_size) else "0";
    icmp_ln1027_2_fu_619_p2 <= "1" when (indvar_flatten21_fu_152 = mul_ln87_4) else "0";
    icmp_ln1027_fu_540_p1 <= mul_ln87_5;
    icmp_ln1027_fu_540_p2 <= "1" when (indvar_flatten45_fu_160 = icmp_ln1027_fu_540_p1) else "0";
    icmp_ln138_fu_517_p2 <= "1" when (indvar_flatten109_fu_172 = bound57) else "0";
    local_conv_kernel_blk_10_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_10_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_10_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_10_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_10_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_1) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_1) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_10_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_11_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_11_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_11_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_11_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_11_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if ((not((trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_0)) and not((trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_1) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_11_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_1_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_1_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_1_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_1_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_1) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_0) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_1_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_2_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_2_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_2_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_2_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if ((not((trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_0)) and not((trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_0) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_2_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_3_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_3_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_3_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_3_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_0) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_1) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_3_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_4_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_4_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_4_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_4_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_1) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_1) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_4_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_5_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_5_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_5_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_5_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if ((not((trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_0)) and not((trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_1) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_5_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_6_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_6_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_6_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_6_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_0) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_0) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_6_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_7_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_7_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_7_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_7_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_1) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_0) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_7_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_8_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_8_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_8_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_8_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if ((not((trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_0)) and not((trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_0) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_8_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_9_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_9_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_9_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_9_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_9_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_0) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_1) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_9_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_address0 <= p_cast1_fu_997_p1(6 - 1 downto 0);

    local_conv_kernel_blk_ce0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_ce0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_conv_kernel_blk_d0 <= bitcast_ln146_reg_1227;

    local_conv_kernel_blk_we0_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln138_2_reg_1154_pp0_iter12_reg, select_ln1027_7_reg_1177_pp0_iter12_reg, trunc_ln146_reg_1186_pp0_iter12_reg)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln146_reg_1186_pp0_iter12_reg = ap_const_lv2_0) and (select_ln1027_7_reg_1177_pp0_iter12_reg = ap_const_lv1_0) and (trunc_ln138_2_reg_1154_pp0_iter12_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            local_conv_kernel_blk_we0 <= ap_const_logic_1;
        else 
            local_conv_kernel_blk_we0 <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_ARADDR <= sext_ln1027_1_fu_977_p1;
    m_axi_gmem2_ARBURST <= ap_const_lv2_0;
    m_axi_gmem2_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem2_ARID <= ap_const_lv1_0;
    m_axi_gmem2_ARLEN <= zext_ln87_19_cast_reg_1127;
    m_axi_gmem2_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem2_ARPROT <= ap_const_lv3_0;
    m_axi_gmem2_ARQOS <= ap_const_lv4_0;
    m_axi_gmem2_ARREGION <= ap_const_lv4_0;
    m_axi_gmem2_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem2_ARUSER <= ap_const_lv1_0;

    m_axi_gmem2_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter5, ap_predicate_op165_readreq_state6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op165_readreq_state6 = ap_const_boolean_1))) then 
            m_axi_gmem2_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem2_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_AWADDR <= ap_const_lv64_0;
    m_axi_gmem2_AWBURST <= ap_const_lv2_0;
    m_axi_gmem2_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem2_AWID <= ap_const_lv1_0;
    m_axi_gmem2_AWLEN <= ap_const_lv32_0;
    m_axi_gmem2_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem2_AWPROT <= ap_const_lv3_0;
    m_axi_gmem2_AWQOS <= ap_const_lv4_0;
    m_axi_gmem2_AWREGION <= ap_const_lv4_0;
    m_axi_gmem2_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem2_AWUSER <= ap_const_lv1_0;
    m_axi_gmem2_AWVALID <= ap_const_logic_0;
    m_axi_gmem2_BREADY <= ap_const_logic_0;

    m_axi_gmem2_RREADY_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem2_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem2_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_WDATA <= ap_const_lv32_0;
    m_axi_gmem2_WID <= ap_const_lv1_0;
    m_axi_gmem2_WLAST <= ap_const_logic_0;
    m_axi_gmem2_WSTRB <= ap_const_lv4_0;
    m_axi_gmem2_WUSER <= ap_const_lv1_0;
    m_axi_gmem2_WVALID <= ap_const_logic_0;
    or_ln1027_1_fu_643_p2 <= (select_ln138_4_fu_624_p3 or icmp_ln1027_fu_540_p2);
    or_ln1027_2_fu_657_p2 <= (select_ln138_4_fu_624_p3 or or_ln138_1_fu_559_p2);
    or_ln1027_3_fu_726_p2 <= (select_ln1027_4_fu_713_p3 or or_ln1027_2_fu_657_p2);
    or_ln1027_4_fu_732_p2 <= (select_ln138_4_fu_624_p3 or select_ln1027_4_fu_713_p3);
    or_ln1027_5_fu_738_p2 <= (or_ln1027_4_fu_732_p2 or icmp_ln1027_fu_540_p2);
    or_ln1027_fu_637_p2 <= (select_ln138_4_fu_624_p3 or or_ln138_fu_553_p2);
    or_ln138_1_fu_559_p2 <= (icmp_ln1027_fu_540_p2 or ap_phi_mux_first_iter_11_phi_fu_424_p4);
    or_ln138_fu_553_p2 <= (icmp_ln1027_fu_540_p2 or ap_phi_mux_first_iter_1_phi_fu_413_p4);
    p_cast146_mid2_v_fu_573_p4 <= select_ln138_2_fu_565_p3(2 downto 1);
    p_cast1_fu_997_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_149_reg_1172_pp0_iter12_reg),64));
    p_mid1_fu_752_p4 <= add_ln140_fu_720_p2(6 downto 1);
    select_ln1027_10_fu_838_p3 <= 
        ap_const_lv32_1 when (icmp_ln1027_fu_540_p2(0) = '1') else 
        add_ln1027_2_fu_832_p2;
    select_ln1027_1_fu_667_p3 <= 
        add_ln139_2_fu_631_p2 when (select_ln138_4_fu_624_p3(0) = '1') else 
        select_ln138_fu_545_p3;
    select_ln1027_2_fu_943_p3 <= 
        add_ln139_5_fu_931_p2 when (select_ln138_4_reg_1158_pp0_iter3_reg(0) = '1') else 
        select_ln138_6_fu_936_p3;
    select_ln1027_3_fu_693_p3 <= 
        ap_const_lv6_0 when (or_ln1027_1_fu_643_p2(0) = '1') else 
        tmp_s_fu_503_p4;
    select_ln1027_4_fu_713_p3 <= 
        icmp_ln1027_16 when (select_ln138_4_fu_624_p3(0) = '1') else 
        select_ln138_3_fu_612_p3;
    select_ln1027_5_fu_744_p3 <= 
        ap_const_lv8_0 when (or_ln1027_5_fu_738_p2(0) = '1') else 
        kw_fu_144;
    select_ln1027_6_fu_762_p3 <= 
        p_mid1_fu_752_p4 when (select_ln1027_4_fu_713_p3(0) = '1') else 
        select_ln1027_3_fu_693_p3;
    select_ln1027_7_fu_780_p3 <= 
        empty_150_fu_776_p1 when (select_ln1027_4_fu_713_p3(0) = '1') else 
        and_ln1027_fu_707_p2;
    select_ln1027_8_fu_800_p3 <= 
        add_ln140_fu_720_p2 when (select_ln1027_4_fu_713_p3(0) = '1') else 
        select_ln1027_fu_649_p3;
    select_ln1027_9_fu_824_p3 <= 
        ap_const_lv16_1 when (or_ln1027_1_fu_643_p2(0) = '1') else 
        add_ln1027_1_fu_818_p2;
    select_ln1027_fu_649_p3 <= 
        ap_const_lv8_0 when (or_ln1027_1_fu_643_p2(0) = '1') else 
        kh_fu_148;
    select_ln138_1_fu_922_p3 <= 
        mul_ln138_1_reg_1206 when (icmp_ln1027_reg_1147_pp0_iter3_reg(0) = '1') else 
        mul_ln138_reg_1200;
    select_ln138_2_fu_565_p3 <= 
        add_ln138_fu_534_p2 when (icmp_ln1027_fu_540_p2(0) = '1') else 
        c_out_fu_164;
    select_ln138_3_fu_612_p3 <= 
        icmp_ln1027_16 when (icmp_ln1027_fu_540_p2(0) = '1') else 
        icmp_ln1027_1_fu_607_p2;
    select_ln138_4_fu_624_p3 <= 
        icmp_ln1027_17 when (icmp_ln1027_fu_540_p2(0) = '1') else 
        icmp_ln1027_2_fu_619_p2;
    select_ln138_5_fu_898_p3 <= 
        add_ln138_1_fu_888_p2 when (icmp_ln1027_reg_1147(0) = '1') else 
        indvar3863_fu_168;
    select_ln138_6_fu_936_p3 <= 
        add_ln139_3_fu_927_p2 when (icmp_ln1027_reg_1147_pp0_iter3_reg(0) = '1') else 
        add_ln139_fu_918_p2;
    select_ln138_fu_545_p3 <= 
        ap_const_lv16_0 when (icmp_ln1027_fu_540_p2(0) = '1') else 
        c_in_fu_156;
        sext_ln1027_1_fu_977_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln140_mid2_v_reg_1212),64));

        sext_ln1027_fu_958_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln140_mid2_v_v_v_v_v_fu_950_p3),64));

    sext_ln140_mid2_v_v_v_v_v_fu_950_p3 <= (select_ln1027_2_fu_943_p3 & ap_const_lv2_0);
    tmp_1_fu_583_p3 <= (p_cast146_mid2_v_fu_573_p4 & ap_const_lv3_0);
    tmp_2_fu_685_p3 <= (empty_148_fu_679_p2 & ap_const_lv1_0);
    tmp_s_fu_503_p4 <= kh_fu_148(6 downto 1);
    trunc_ln138_1_fu_894_p1 <= add_ln138_1_fu_888_p2(32 - 1 downto 0);
    trunc_ln138_2_fu_591_p1 <= select_ln138_2_fu_565_p3(1 - 1 downto 0);
    trunc_ln138_fu_884_p1 <= indvar3863_fu_168(32 - 1 downto 0);
    trunc_ln146_fu_808_p1 <= select_ln1027_5_fu_744_p3(2 - 1 downto 0);
    xor_ln1027_1_fu_788_p2 <= (select_ln1027_4_fu_713_p3 xor ap_const_lv1_1);
    xor_ln1027_fu_701_p2 <= (select_ln138_4_fu_624_p3 xor ap_const_lv1_1);
    xor_ln138_fu_595_p2 <= (icmp_ln1027_fu_540_p2 xor ap_const_lv1_1);
    zext_ln87_13_cast_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln87_13),32));
    zext_ln87_19_cast_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln87_19),32));
    zext_ln87_21_cast_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln87_21),64));
end behav;
