-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv_bn_relu_Block_entry352_proc1_Pipeline_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    local_feature_in_blk_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_feature_in_blk_ce0 : OUT STD_LOGIC;
    local_feature_in_blk_we0 : OUT STD_LOGIC;
    local_feature_in_blk_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_feature_in_blk_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_feature_in_blk_1_ce0 : OUT STD_LOGIC;
    local_feature_in_blk_1_we0 : OUT STD_LOGIC;
    local_feature_in_blk_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of conv_bn_relu_Block_entry352_proc1_Pipeline_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv9_120 : STD_LOGIC_VECTOR (8 downto 0) := "100100000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv18_2AB : STD_LOGIC_VECTOR (17 downto 0) := "000000001010101011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv9_30 : STD_LOGIC_VECTOR (8 downto 0) := "000110000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal exitcond13_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal tmp_27_cast_fu_216_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal phi_urem_fu_60 : STD_LOGIC_VECTOR (8 downto 0);
    signal idx_urem_fu_241_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal phi_mul574_fu_64 : STD_LOGIC_VECTOR (17 downto 0);
    signal next_mul575_fu_136_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal empty_fu_68 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_162_fu_124_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_166_fu_222_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_142_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_160_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_152_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_cast_fu_168_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_178_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_164_fu_172_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_24_cast_fu_188_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_165_fu_192_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_3_fu_198_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_208_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal next_urem_fu_229_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_163_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv_bn_relu_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component conv_bn_relu_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    empty_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_fu_68 <= ap_const_lv9_0;
                elsif (((exitcond13_fu_118_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_fu_68 <= empty_162_fu_124_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_mul574_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul574_fu_64 <= ap_const_lv18_0;
                elsif (((exitcond13_fu_118_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    phi_mul574_fu_64 <= next_mul575_fu_136_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    phi_urem_fu_60 <= ap_const_lv9_0;
                elsif (((exitcond13_fu_118_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    phi_urem_fu_60 <= idx_urem_fu_241_p3;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, exitcond13_fu_118_p2)
    begin
        if (((exitcond13_fu_118_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_162_fu_124_p2 <= std_logic_vector(unsigned(empty_fu_68) + unsigned(ap_const_lv9_1));
    empty_163_fu_235_p2 <= "1" when (unsigned(next_urem_fu_229_p2) < unsigned(ap_const_lv9_30)) else "0";
    empty_164_fu_172_p2 <= std_logic_vector(unsigned(tmp_6_fu_152_p3) - unsigned(tmp_23_cast_fu_168_p1));
    empty_165_fu_192_p2 <= std_logic_vector(unsigned(empty_164_fu_172_p2) + unsigned(tmp_24_cast_fu_188_p1));
    empty_166_fu_222_p1 <= empty_fu_68(1 - 1 downto 0);
    exitcond13_fu_118_p2 <= "1" when (empty_fu_68 = ap_const_lv9_120) else "0";
    idx_urem_fu_241_p3 <= 
        next_urem_fu_229_p2 when (empty_163_fu_235_p2(0) = '1') else 
        ap_const_lv9_0;
    local_feature_in_blk_1_address0 <= tmp_27_cast_fu_216_p1(8 - 1 downto 0);

    local_feature_in_blk_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_feature_in_blk_1_ce0 <= ap_const_logic_1;
        else 
            local_feature_in_blk_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_feature_in_blk_1_d0 <= ap_const_lv32_0;

    local_feature_in_blk_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond13_fu_118_p2, ap_block_pp0_stage0_11001, empty_166_fu_222_p1)
    begin
        if (((empty_166_fu_222_p1 = ap_const_lv1_1) and (exitcond13_fu_118_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_feature_in_blk_1_we0 <= ap_const_logic_1;
        else 
            local_feature_in_blk_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_feature_in_blk_address0 <= tmp_27_cast_fu_216_p1(8 - 1 downto 0);

    local_feature_in_blk_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_feature_in_blk_ce0 <= ap_const_logic_1;
        else 
            local_feature_in_blk_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_feature_in_blk_d0 <= ap_const_lv32_0;

    local_feature_in_blk_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond13_fu_118_p2, ap_block_pp0_stage0_11001, empty_166_fu_222_p1)
    begin
        if (((empty_166_fu_222_p1 = ap_const_lv1_0) and (exitcond13_fu_118_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_feature_in_blk_we0 <= ap_const_logic_1;
        else 
            local_feature_in_blk_we0 <= ap_const_logic_0;
        end if; 
    end process;

    next_mul575_fu_136_p2 <= std_logic_vector(unsigned(phi_mul574_fu_64) + unsigned(ap_const_lv18_2AB));
    next_urem_fu_229_p2 <= std_logic_vector(unsigned(phi_urem_fu_60) + unsigned(ap_const_lv9_1));
    tmp_23_cast_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_160_p3),6));
    tmp_24_cast_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_178_p4),6));
    tmp_27_cast_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_208_p3),64));
    tmp_3_fu_198_p4 <= phi_urem_fu_60(2 downto 1);
    tmp_4_fu_208_p3 <= (empty_165_fu_192_p2 & tmp_3_fu_198_p4);
    tmp_6_fu_152_p3 <= (tmp_fu_142_p4 & ap_const_lv3_0);
    tmp_7_fu_160_p3 <= (tmp_fu_142_p4 & ap_const_lv1_0);
    tmp_fu_142_p4 <= phi_mul574_fu_64(17 downto 15);
    tmp_s_fu_178_p4 <= phi_urem_fu_60(5 downto 3);
end behav;
