// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="channel_shuffle_channel_shuffle,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2847,HLS_SYN_LUT=4049,HLS_VERSION=2022_2}" *)

module channel_shuffle (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_in_AWVALID,
        m_axi_gmem_in_AWREADY,
        m_axi_gmem_in_AWADDR,
        m_axi_gmem_in_AWID,
        m_axi_gmem_in_AWLEN,
        m_axi_gmem_in_AWSIZE,
        m_axi_gmem_in_AWBURST,
        m_axi_gmem_in_AWLOCK,
        m_axi_gmem_in_AWCACHE,
        m_axi_gmem_in_AWPROT,
        m_axi_gmem_in_AWQOS,
        m_axi_gmem_in_AWREGION,
        m_axi_gmem_in_AWUSER,
        m_axi_gmem_in_WVALID,
        m_axi_gmem_in_WREADY,
        m_axi_gmem_in_WDATA,
        m_axi_gmem_in_WSTRB,
        m_axi_gmem_in_WLAST,
        m_axi_gmem_in_WID,
        m_axi_gmem_in_WUSER,
        m_axi_gmem_in_ARVALID,
        m_axi_gmem_in_ARREADY,
        m_axi_gmem_in_ARADDR,
        m_axi_gmem_in_ARID,
        m_axi_gmem_in_ARLEN,
        m_axi_gmem_in_ARSIZE,
        m_axi_gmem_in_ARBURST,
        m_axi_gmem_in_ARLOCK,
        m_axi_gmem_in_ARCACHE,
        m_axi_gmem_in_ARPROT,
        m_axi_gmem_in_ARQOS,
        m_axi_gmem_in_ARREGION,
        m_axi_gmem_in_ARUSER,
        m_axi_gmem_in_RVALID,
        m_axi_gmem_in_RREADY,
        m_axi_gmem_in_RDATA,
        m_axi_gmem_in_RLAST,
        m_axi_gmem_in_RID,
        m_axi_gmem_in_RUSER,
        m_axi_gmem_in_RRESP,
        m_axi_gmem_in_BVALID,
        m_axi_gmem_in_BREADY,
        m_axi_gmem_in_BRESP,
        m_axi_gmem_in_BID,
        m_axi_gmem_in_BUSER,
        m_axi_gmem_out_AWVALID,
        m_axi_gmem_out_AWREADY,
        m_axi_gmem_out_AWADDR,
        m_axi_gmem_out_AWID,
        m_axi_gmem_out_AWLEN,
        m_axi_gmem_out_AWSIZE,
        m_axi_gmem_out_AWBURST,
        m_axi_gmem_out_AWLOCK,
        m_axi_gmem_out_AWCACHE,
        m_axi_gmem_out_AWPROT,
        m_axi_gmem_out_AWQOS,
        m_axi_gmem_out_AWREGION,
        m_axi_gmem_out_AWUSER,
        m_axi_gmem_out_WVALID,
        m_axi_gmem_out_WREADY,
        m_axi_gmem_out_WDATA,
        m_axi_gmem_out_WSTRB,
        m_axi_gmem_out_WLAST,
        m_axi_gmem_out_WID,
        m_axi_gmem_out_WUSER,
        m_axi_gmem_out_ARVALID,
        m_axi_gmem_out_ARREADY,
        m_axi_gmem_out_ARADDR,
        m_axi_gmem_out_ARID,
        m_axi_gmem_out_ARLEN,
        m_axi_gmem_out_ARSIZE,
        m_axi_gmem_out_ARBURST,
        m_axi_gmem_out_ARLOCK,
        m_axi_gmem_out_ARCACHE,
        m_axi_gmem_out_ARPROT,
        m_axi_gmem_out_ARQOS,
        m_axi_gmem_out_ARREGION,
        m_axi_gmem_out_ARUSER,
        m_axi_gmem_out_RVALID,
        m_axi_gmem_out_RREADY,
        m_axi_gmem_out_RDATA,
        m_axi_gmem_out_RLAST,
        m_axi_gmem_out_RID,
        m_axi_gmem_out_RUSER,
        m_axi_gmem_out_RRESP,
        m_axi_gmem_out_BVALID,
        m_axi_gmem_out_BREADY,
        m_axi_gmem_out_BRESP,
        m_axi_gmem_out_BID,
        m_axi_gmem_out_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 44'd1;
parameter    ap_ST_fsm_state2 = 44'd2;
parameter    ap_ST_fsm_state3 = 44'd4;
parameter    ap_ST_fsm_state4 = 44'd8;
parameter    ap_ST_fsm_state5 = 44'd16;
parameter    ap_ST_fsm_state6 = 44'd32;
parameter    ap_ST_fsm_state7 = 44'd64;
parameter    ap_ST_fsm_state8 = 44'd128;
parameter    ap_ST_fsm_state9 = 44'd256;
parameter    ap_ST_fsm_state10 = 44'd512;
parameter    ap_ST_fsm_state11 = 44'd1024;
parameter    ap_ST_fsm_state12 = 44'd2048;
parameter    ap_ST_fsm_state13 = 44'd4096;
parameter    ap_ST_fsm_state14 = 44'd8192;
parameter    ap_ST_fsm_state15 = 44'd16384;
parameter    ap_ST_fsm_state16 = 44'd32768;
parameter    ap_ST_fsm_state17 = 44'd65536;
parameter    ap_ST_fsm_state18 = 44'd131072;
parameter    ap_ST_fsm_state19 = 44'd262144;
parameter    ap_ST_fsm_state20 = 44'd524288;
parameter    ap_ST_fsm_state21 = 44'd1048576;
parameter    ap_ST_fsm_state22 = 44'd2097152;
parameter    ap_ST_fsm_state23 = 44'd4194304;
parameter    ap_ST_fsm_state24 = 44'd8388608;
parameter    ap_ST_fsm_state25 = 44'd16777216;
parameter    ap_ST_fsm_state26 = 44'd33554432;
parameter    ap_ST_fsm_state27 = 44'd67108864;
parameter    ap_ST_fsm_state28 = 44'd134217728;
parameter    ap_ST_fsm_state29 = 44'd268435456;
parameter    ap_ST_fsm_state30 = 44'd536870912;
parameter    ap_ST_fsm_state31 = 44'd1073741824;
parameter    ap_ST_fsm_state32 = 44'd2147483648;
parameter    ap_ST_fsm_state33 = 44'd4294967296;
parameter    ap_ST_fsm_state34 = 44'd8589934592;
parameter    ap_ST_fsm_state35 = 44'd17179869184;
parameter    ap_ST_fsm_state36 = 44'd34359738368;
parameter    ap_ST_fsm_state37 = 44'd68719476736;
parameter    ap_ST_fsm_state38 = 44'd137438953472;
parameter    ap_ST_fsm_state39 = 44'd274877906944;
parameter    ap_ST_fsm_state40 = 44'd549755813888;
parameter    ap_ST_fsm_state41 = 44'd1099511627776;
parameter    ap_ST_fsm_state42 = 44'd2199023255552;
parameter    ap_ST_fsm_state43 = 44'd4398046511104;
parameter    ap_ST_fsm_state44 = 44'd8796093022208;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_IN_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_IN_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_IN_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_IN_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_IN_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_IN_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_OUT_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_OUT_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_OUT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_OUT_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_OUT_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_OUT_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_IN_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_OUT_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_in_AWVALID;
input   m_axi_gmem_in_AWREADY;
output  [C_M_AXI_GMEM_IN_ADDR_WIDTH - 1:0] m_axi_gmem_in_AWADDR;
output  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_AWID;
output  [7:0] m_axi_gmem_in_AWLEN;
output  [2:0] m_axi_gmem_in_AWSIZE;
output  [1:0] m_axi_gmem_in_AWBURST;
output  [1:0] m_axi_gmem_in_AWLOCK;
output  [3:0] m_axi_gmem_in_AWCACHE;
output  [2:0] m_axi_gmem_in_AWPROT;
output  [3:0] m_axi_gmem_in_AWQOS;
output  [3:0] m_axi_gmem_in_AWREGION;
output  [C_M_AXI_GMEM_IN_AWUSER_WIDTH - 1:0] m_axi_gmem_in_AWUSER;
output   m_axi_gmem_in_WVALID;
input   m_axi_gmem_in_WREADY;
output  [C_M_AXI_GMEM_IN_DATA_WIDTH - 1:0] m_axi_gmem_in_WDATA;
output  [C_M_AXI_GMEM_IN_WSTRB_WIDTH - 1:0] m_axi_gmem_in_WSTRB;
output   m_axi_gmem_in_WLAST;
output  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_WID;
output  [C_M_AXI_GMEM_IN_WUSER_WIDTH - 1:0] m_axi_gmem_in_WUSER;
output   m_axi_gmem_in_ARVALID;
input   m_axi_gmem_in_ARREADY;
output  [C_M_AXI_GMEM_IN_ADDR_WIDTH - 1:0] m_axi_gmem_in_ARADDR;
output  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_ARID;
output  [7:0] m_axi_gmem_in_ARLEN;
output  [2:0] m_axi_gmem_in_ARSIZE;
output  [1:0] m_axi_gmem_in_ARBURST;
output  [1:0] m_axi_gmem_in_ARLOCK;
output  [3:0] m_axi_gmem_in_ARCACHE;
output  [2:0] m_axi_gmem_in_ARPROT;
output  [3:0] m_axi_gmem_in_ARQOS;
output  [3:0] m_axi_gmem_in_ARREGION;
output  [C_M_AXI_GMEM_IN_ARUSER_WIDTH - 1:0] m_axi_gmem_in_ARUSER;
input   m_axi_gmem_in_RVALID;
output   m_axi_gmem_in_RREADY;
input  [C_M_AXI_GMEM_IN_DATA_WIDTH - 1:0] m_axi_gmem_in_RDATA;
input   m_axi_gmem_in_RLAST;
input  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_RID;
input  [C_M_AXI_GMEM_IN_RUSER_WIDTH - 1:0] m_axi_gmem_in_RUSER;
input  [1:0] m_axi_gmem_in_RRESP;
input   m_axi_gmem_in_BVALID;
output   m_axi_gmem_in_BREADY;
input  [1:0] m_axi_gmem_in_BRESP;
input  [C_M_AXI_GMEM_IN_ID_WIDTH - 1:0] m_axi_gmem_in_BID;
input  [C_M_AXI_GMEM_IN_BUSER_WIDTH - 1:0] m_axi_gmem_in_BUSER;
output   m_axi_gmem_out_AWVALID;
input   m_axi_gmem_out_AWREADY;
output  [C_M_AXI_GMEM_OUT_ADDR_WIDTH - 1:0] m_axi_gmem_out_AWADDR;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_AWID;
output  [7:0] m_axi_gmem_out_AWLEN;
output  [2:0] m_axi_gmem_out_AWSIZE;
output  [1:0] m_axi_gmem_out_AWBURST;
output  [1:0] m_axi_gmem_out_AWLOCK;
output  [3:0] m_axi_gmem_out_AWCACHE;
output  [2:0] m_axi_gmem_out_AWPROT;
output  [3:0] m_axi_gmem_out_AWQOS;
output  [3:0] m_axi_gmem_out_AWREGION;
output  [C_M_AXI_GMEM_OUT_AWUSER_WIDTH - 1:0] m_axi_gmem_out_AWUSER;
output   m_axi_gmem_out_WVALID;
input   m_axi_gmem_out_WREADY;
output  [C_M_AXI_GMEM_OUT_DATA_WIDTH - 1:0] m_axi_gmem_out_WDATA;
output  [C_M_AXI_GMEM_OUT_WSTRB_WIDTH - 1:0] m_axi_gmem_out_WSTRB;
output   m_axi_gmem_out_WLAST;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_WID;
output  [C_M_AXI_GMEM_OUT_WUSER_WIDTH - 1:0] m_axi_gmem_out_WUSER;
output   m_axi_gmem_out_ARVALID;
input   m_axi_gmem_out_ARREADY;
output  [C_M_AXI_GMEM_OUT_ADDR_WIDTH - 1:0] m_axi_gmem_out_ARADDR;
output  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_ARID;
output  [7:0] m_axi_gmem_out_ARLEN;
output  [2:0] m_axi_gmem_out_ARSIZE;
output  [1:0] m_axi_gmem_out_ARBURST;
output  [1:0] m_axi_gmem_out_ARLOCK;
output  [3:0] m_axi_gmem_out_ARCACHE;
output  [2:0] m_axi_gmem_out_ARPROT;
output  [3:0] m_axi_gmem_out_ARQOS;
output  [3:0] m_axi_gmem_out_ARREGION;
output  [C_M_AXI_GMEM_OUT_ARUSER_WIDTH - 1:0] m_axi_gmem_out_ARUSER;
input   m_axi_gmem_out_RVALID;
output   m_axi_gmem_out_RREADY;
input  [C_M_AXI_GMEM_OUT_DATA_WIDTH - 1:0] m_axi_gmem_out_RDATA;
input   m_axi_gmem_out_RLAST;
input  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_RID;
input  [C_M_AXI_GMEM_OUT_RUSER_WIDTH - 1:0] m_axi_gmem_out_RUSER;
input  [1:0] m_axi_gmem_out_RRESP;
input   m_axi_gmem_out_BVALID;
output   m_axi_gmem_out_BREADY;
input  [1:0] m_axi_gmem_out_BRESP;
input  [C_M_AXI_GMEM_OUT_ID_WIDTH - 1:0] m_axi_gmem_out_BID;
input  [C_M_AXI_GMEM_OUT_BUSER_WIDTH - 1:0] m_axi_gmem_out_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [43:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] c_in;
wire   [15:0] h_w;
wire   [7:0] groups;
wire   [63:0] in_r;
wire   [63:0] out_r;
reg    gmem_in_blk_n_AR;
wire    ap_CS_fsm_state31;
reg    gmem_in_blk_n_R;
wire    ap_CS_fsm_state38;
reg    gmem_out_blk_n_AW;
reg    gmem_out_blk_n_W;
wire    ap_CS_fsm_state39;
reg    gmem_out_blk_n_B;
wire    ap_CS_fsm_state44;
reg   [63:0] out_r_read_reg_654;
reg   [63:0] in_r_read_reg_659;
reg   [7:0] groups_read_reg_664;
reg   [15:0] h_w_read_reg_671;
wire   [15:0] zext_ln1513_fu_219_p1;
reg   [15:0] zext_ln1513_reg_683;
wire    ap_CS_fsm_state14;
wire   [31:0] zext_ln186_fu_260_p1;
reg   [31:0] zext_ln186_reg_699;
wire    ap_CS_fsm_state17;
wire   [23:0] grp_fu_582_p2;
reg   [23:0] mul_ln11_reg_707;
wire   [15:0] grp_fu_223_p2;
reg   [15:0] ret_V_4_reg_722;
wire    ap_CS_fsm_state20;
wire   [23:0] conv3_i11_i329_fu_269_p1;
reg   [23:0] conv3_i11_i329_reg_727;
wire  signed [31:0] grp_fu_589_p2;
reg  signed [31:0] ret_V_3_reg_732;
wire  signed [39:0] grp_fu_595_p2;
reg   [39:0] mul_ln11_1_reg_738;
wire   [0:0] icmp_ln1027_fu_273_p2;
reg   [0:0] icmp_ln1027_reg_743;
wire    ap_CS_fsm_state21;
wire  signed [31:0] grp_fu_601_p2;
reg   [31:0] ret_V_1_reg_759;
wire    ap_CS_fsm_state24;
(* use_dsp48 = "no" *) wire   [31:0] add_ln186_fu_295_p2;
reg   [31:0] add_ln186_reg_764;
wire   [39:0] add_ln1027_1_fu_305_p2;
reg   [39:0] add_ln1027_1_reg_772;
wire   [0:0] icmp_ln1027_2_fu_314_p2;
reg   [0:0] icmp_ln1027_2_reg_777;
wire   [0:0] icmp_ln1027_1_fu_300_p2;
wire   [0:0] select_ln1027_3_fu_333_p3;
reg   [0:0] select_ln1027_3_reg_790;
wire   [15:0] select_ln1027_4_fu_340_p3;
reg   [15:0] select_ln1027_4_reg_796;
wire   [7:0] select_ln34_fu_353_p3;
reg   [7:0] select_ln34_reg_801;
wire   [31:0] select_ln34_1_fu_397_p3;
reg   [31:0] select_ln34_1_reg_812;
wire    ap_CS_fsm_state27;
wire   [15:0] select_ln1027_5_fu_404_p3;
reg   [15:0] select_ln1027_5_reg_818;
wire  signed [23:0] grp_fu_614_p2;
reg   [23:0] lhs_reg_823;
wire   [15:0] zext_ln186_2_fu_411_p1;
reg   [15:0] zext_ln186_2_reg_828;
wire   [15:0] c_V_fu_419_p2;
reg   [15:0] c_V_reg_836;
wire    ap_CS_fsm_state28;
(* use_dsp48 = "no" *) wire   [23:0] ret_V_fu_429_p2;
reg   [23:0] ret_V_reg_841;
wire   [0:0] icmp_ln1027_3_fu_414_p2;
wire   [15:0] add_ln186_3_fu_434_p2;
reg   [15:0] add_ln186_3_reg_846;
wire   [15:0] out_c_V_fu_439_p2;
reg   [15:0] out_c_V_reg_851;
wire   [31:0] mul_ln186_1_fu_487_p2;
reg   [31:0] mul_ln186_1_reg_856;
wire    ap_CS_fsm_state29;
wire   [31:0] mul_ln186_fu_495_p2;
reg   [31:0] mul_ln186_reg_861;
reg   [63:0] gmem_in_addr_reg_866;
wire    ap_CS_fsm_state30;
reg   [63:0] gmem_out_addr_reg_872;
reg   [31:0] gmem_in_addr_read_reg_878;
wire    gmem_in_AWREADY;
wire    gmem_in_WREADY;
reg    gmem_in_ARVALID;
wire    gmem_in_ARREADY;
wire    gmem_in_RVALID;
reg    gmem_in_RREADY;
wire   [31:0] gmem_in_RDATA;
wire   [8:0] gmem_in_RFIFONUM;
wire    gmem_in_BVALID;
reg    gmem_out_AWVALID;
wire    gmem_out_AWREADY;
reg    gmem_out_WVALID;
wire    gmem_out_WREADY;
wire    gmem_out_ARREADY;
wire    gmem_out_RVALID;
wire   [31:0] gmem_out_RDATA;
wire   [8:0] gmem_out_RFIFONUM;
wire    gmem_out_BVALID;
reg    gmem_out_BREADY;
reg   [15:0] c_V_1_reg_194;
reg   [15:0] phi_mul_reg_205;
wire  signed [63:0] sext_ln46_fu_535_p1;
wire  signed [63:0] sext_ln46_1_fu_572_p1;
reg    ap_block_state31_io;
reg   [7:0] g_V_fu_116;
wire   [7:0] g_V_1_fu_444_p2;
reg   [15:0] w_V_fu_120;
reg   [23:0] indvar_flatten_fu_124;
wire   [23:0] select_ln1027_6_fu_455_p3;
reg   [15:0] h_V_fu_128;
reg   [39:0] indvar_flatten15_fu_132;
wire   [7:0] grp_fu_223_p1;
wire   [31:0] add_ln186_fu_295_p0;
wire   [31:0] zext_ln186_1_fu_291_p1;
wire   [15:0] add_ln840_fu_319_p2;
wire   [0:0] icmp_ln1027_4_fu_328_p2;
wire   [0:0] or_ln34_fu_347_p2;
wire   [31:0] select_ln1027_1_fu_371_p1;
wire  signed [31:0] grp_fu_607_p2;
wire   [31:0] select_ln1027_2_fu_376_p1;
wire   [15:0] select_ln1027_fu_365_p3;
wire   [15:0] w_V_3_fu_381_p2;
wire   [31:0] select_ln1027_1_fu_371_p3;
wire   [31:0] zext_ln186_5_fu_387_p1;
wire   [31:0] add_ln186_1_fu_391_p2;
wire   [31:0] select_ln1027_2_fu_376_p3;
wire   [23:0] zext_ln1495_fu_425_p1;
wire   [23:0] add_ln1027_fu_449_p2;
wire   [23:0] mul_ln186_1_fu_487_p1;
wire   [15:0] mul_ln186_fu_495_p1;
wire   [31:0] in_idx_V_fu_500_p2;
wire   [33:0] shl_ln_fu_508_p3;
wire   [63:0] zext_ln46_fu_516_p1;
wire   [63:0] add_ln46_fu_520_p2;
wire   [61:0] trunc_ln_fu_525_p4;
wire   [31:0] out_idx_V_fu_504_p2;
wire   [33:0] shl_ln46_1_fu_545_p3;
wire   [63:0] zext_ln46_1_fu_553_p1;
wire   [63:0] add_ln46_1_fu_557_p2;
wire   [61:0] trunc_ln46_1_fu_562_p4;
wire   [15:0] grp_fu_582_p0;
wire   [7:0] grp_fu_582_p1;
wire   [15:0] grp_fu_589_p0;
wire   [15:0] grp_fu_589_p1;
wire   [15:0] grp_fu_595_p0;
wire   [23:0] grp_fu_595_p1;
wire   [15:0] grp_fu_601_p0;
wire   [15:0] grp_fu_601_p1;
wire   [15:0] grp_fu_607_p0;
wire   [15:0] grp_fu_607_p1;
wire   [15:0] grp_fu_614_p0;
wire   [7:0] grp_fu_614_p1;
reg    grp_fu_223_ap_start;
wire    grp_fu_223_ap_done;
reg   [43:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
reg    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
reg    ap_ST_fsm_state38_blk;
reg    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
reg    ap_ST_fsm_state44_blk;
wire   [15:0] grp_fu_223_p10;
wire   [23:0] grp_fu_582_p00;
wire   [23:0] grp_fu_582_p10;
wire   [39:0] grp_fu_595_p00;
wire   [39:0] grp_fu_595_p10;
wire   [31:0] grp_fu_601_p00;
wire   [31:0] grp_fu_607_p00;
wire   [23:0] grp_fu_614_p10;
wire   [31:0] mul_ln186_1_fu_487_p10;
wire   [31:0] mul_ln186_fu_495_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 44'd1;
end

channel_shuffle_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .c_in(c_in),
    .groups(groups),
    .h_w(h_w),
    .in_r(in_r),
    .out_r(out_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

channel_shuffle_gmem_in_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_IN_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_IN_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_IN_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_IN_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_IN_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_IN_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_IN_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_IN_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_IN_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_IN_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_IN_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_in_m_axi_U(
    .AWVALID(m_axi_gmem_in_AWVALID),
    .AWREADY(m_axi_gmem_in_AWREADY),
    .AWADDR(m_axi_gmem_in_AWADDR),
    .AWID(m_axi_gmem_in_AWID),
    .AWLEN(m_axi_gmem_in_AWLEN),
    .AWSIZE(m_axi_gmem_in_AWSIZE),
    .AWBURST(m_axi_gmem_in_AWBURST),
    .AWLOCK(m_axi_gmem_in_AWLOCK),
    .AWCACHE(m_axi_gmem_in_AWCACHE),
    .AWPROT(m_axi_gmem_in_AWPROT),
    .AWQOS(m_axi_gmem_in_AWQOS),
    .AWREGION(m_axi_gmem_in_AWREGION),
    .AWUSER(m_axi_gmem_in_AWUSER),
    .WVALID(m_axi_gmem_in_WVALID),
    .WREADY(m_axi_gmem_in_WREADY),
    .WDATA(m_axi_gmem_in_WDATA),
    .WSTRB(m_axi_gmem_in_WSTRB),
    .WLAST(m_axi_gmem_in_WLAST),
    .WID(m_axi_gmem_in_WID),
    .WUSER(m_axi_gmem_in_WUSER),
    .ARVALID(m_axi_gmem_in_ARVALID),
    .ARREADY(m_axi_gmem_in_ARREADY),
    .ARADDR(m_axi_gmem_in_ARADDR),
    .ARID(m_axi_gmem_in_ARID),
    .ARLEN(m_axi_gmem_in_ARLEN),
    .ARSIZE(m_axi_gmem_in_ARSIZE),
    .ARBURST(m_axi_gmem_in_ARBURST),
    .ARLOCK(m_axi_gmem_in_ARLOCK),
    .ARCACHE(m_axi_gmem_in_ARCACHE),
    .ARPROT(m_axi_gmem_in_ARPROT),
    .ARQOS(m_axi_gmem_in_ARQOS),
    .ARREGION(m_axi_gmem_in_ARREGION),
    .ARUSER(m_axi_gmem_in_ARUSER),
    .RVALID(m_axi_gmem_in_RVALID),
    .RREADY(m_axi_gmem_in_RREADY),
    .RDATA(m_axi_gmem_in_RDATA),
    .RLAST(m_axi_gmem_in_RLAST),
    .RID(m_axi_gmem_in_RID),
    .RUSER(m_axi_gmem_in_RUSER),
    .RRESP(m_axi_gmem_in_RRESP),
    .BVALID(m_axi_gmem_in_BVALID),
    .BREADY(m_axi_gmem_in_BREADY),
    .BRESP(m_axi_gmem_in_BRESP),
    .BID(m_axi_gmem_in_BID),
    .BUSER(m_axi_gmem_in_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_in_ARVALID),
    .I_ARREADY(gmem_in_ARREADY),
    .I_ARADDR(gmem_in_addr_reg_866),
    .I_ARLEN(32'd1),
    .I_RVALID(gmem_in_RVALID),
    .I_RREADY(gmem_in_RREADY),
    .I_RDATA(gmem_in_RDATA),
    .I_RFIFONUM(gmem_in_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem_in_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem_in_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem_in_BVALID),
    .I_BREADY(1'b0)
);

channel_shuffle_gmem_out_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_OUT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_OUT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_OUT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_OUT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_OUT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_OUT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_OUT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_OUT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_OUT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_OUT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_OUT_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_out_m_axi_U(
    .AWVALID(m_axi_gmem_out_AWVALID),
    .AWREADY(m_axi_gmem_out_AWREADY),
    .AWADDR(m_axi_gmem_out_AWADDR),
    .AWID(m_axi_gmem_out_AWID),
    .AWLEN(m_axi_gmem_out_AWLEN),
    .AWSIZE(m_axi_gmem_out_AWSIZE),
    .AWBURST(m_axi_gmem_out_AWBURST),
    .AWLOCK(m_axi_gmem_out_AWLOCK),
    .AWCACHE(m_axi_gmem_out_AWCACHE),
    .AWPROT(m_axi_gmem_out_AWPROT),
    .AWQOS(m_axi_gmem_out_AWQOS),
    .AWREGION(m_axi_gmem_out_AWREGION),
    .AWUSER(m_axi_gmem_out_AWUSER),
    .WVALID(m_axi_gmem_out_WVALID),
    .WREADY(m_axi_gmem_out_WREADY),
    .WDATA(m_axi_gmem_out_WDATA),
    .WSTRB(m_axi_gmem_out_WSTRB),
    .WLAST(m_axi_gmem_out_WLAST),
    .WID(m_axi_gmem_out_WID),
    .WUSER(m_axi_gmem_out_WUSER),
    .ARVALID(m_axi_gmem_out_ARVALID),
    .ARREADY(m_axi_gmem_out_ARREADY),
    .ARADDR(m_axi_gmem_out_ARADDR),
    .ARID(m_axi_gmem_out_ARID),
    .ARLEN(m_axi_gmem_out_ARLEN),
    .ARSIZE(m_axi_gmem_out_ARSIZE),
    .ARBURST(m_axi_gmem_out_ARBURST),
    .ARLOCK(m_axi_gmem_out_ARLOCK),
    .ARCACHE(m_axi_gmem_out_ARCACHE),
    .ARPROT(m_axi_gmem_out_ARPROT),
    .ARQOS(m_axi_gmem_out_ARQOS),
    .ARREGION(m_axi_gmem_out_ARREGION),
    .ARUSER(m_axi_gmem_out_ARUSER),
    .RVALID(m_axi_gmem_out_RVALID),
    .RREADY(m_axi_gmem_out_RREADY),
    .RDATA(m_axi_gmem_out_RDATA),
    .RLAST(m_axi_gmem_out_RLAST),
    .RID(m_axi_gmem_out_RID),
    .RUSER(m_axi_gmem_out_RUSER),
    .RRESP(m_axi_gmem_out_RRESP),
    .BVALID(m_axi_gmem_out_BVALID),
    .BREADY(m_axi_gmem_out_BREADY),
    .BRESP(m_axi_gmem_out_BRESP),
    .BID(m_axi_gmem_out_BID),
    .BUSER(m_axi_gmem_out_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem_out_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(gmem_out_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem_out_RDATA),
    .I_RFIFONUM(gmem_out_RFIFONUM),
    .I_AWVALID(gmem_out_AWVALID),
    .I_AWREADY(gmem_out_AWREADY),
    .I_AWADDR(gmem_out_addr_reg_872),
    .I_AWLEN(32'd1),
    .I_WVALID(gmem_out_WVALID),
    .I_WREADY(gmem_out_WREADY),
    .I_WDATA(gmem_in_addr_read_reg_878),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem_out_BVALID),
    .I_BREADY(gmem_out_BREADY)
);

channel_shuffle_udiv_16ns_8ns_16_20_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 20 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
udiv_16ns_8ns_16_20_seq_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_223_ap_start),
    .done(grp_fu_223_ap_done),
    .din0(c_in),
    .din1(grp_fu_223_p1),
    .ce(1'b1),
    .dout(grp_fu_223_p2)
);

channel_shuffle_mul_32s_24ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 32 ))
mul_32s_24ns_32_1_1_U2(
    .din0(ret_V_3_reg_732),
    .din1(mul_ln186_1_fu_487_p1),
    .dout(mul_ln186_1_fu_487_p2)
);

channel_shuffle_mul_32s_16ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_32s_16ns_32_1_1_U3(
    .din0(ret_V_3_reg_732),
    .din1(mul_ln186_fu_495_p1),
    .dout(mul_ln186_fu_495_p2)
);

channel_shuffle_mul_mul_16ns_8ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16ns_8ns_24_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_582_p0),
    .din1(grp_fu_582_p1),
    .ce(1'b1),
    .dout(grp_fu_582_p2)
);

channel_shuffle_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_589_p0),
    .din1(grp_fu_589_p1),
    .ce(1'b1),
    .dout(grp_fu_589_p2)
);

channel_shuffle_mul_mul_16ns_24ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 40 ))
mul_mul_16ns_24ns_40_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_595_p0),
    .din1(grp_fu_595_p1),
    .ce(1'b1),
    .dout(grp_fu_595_p2)
);

channel_shuffle_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_601_p0),
    .din1(grp_fu_601_p1),
    .ce(1'b1),
    .dout(grp_fu_601_p2)
);

channel_shuffle_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_607_p0),
    .din1(grp_fu_607_p1),
    .ce(1'b1),
    .dout(grp_fu_607_p2)
);

channel_shuffle_mul_mul_16ns_8ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16ns_8ns_24_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_614_p0),
    .din1(grp_fu_614_p1),
    .ce(1'b1),
    .dout(grp_fu_614_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem_out_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
        c_V_1_reg_194 <= c_V_reg_836;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        c_V_1_reg_194 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        g_V_fu_116 <= 8'd0;
    end else if (((icmp_ln1027_3_fu_414_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        g_V_fu_116 <= g_V_1_fu_444_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        h_V_fu_128 <= 16'd0;
    end else if (((icmp_ln1027_3_fu_414_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        h_V_fu_128 <= select_ln1027_4_reg_796;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten15_fu_132 <= 40'd0;
    end else if (((icmp_ln1027_3_fu_414_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        indvar_flatten15_fu_132 <= add_ln1027_1_reg_772;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_124 <= 24'd0;
    end else if (((icmp_ln1027_3_fu_414_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        indvar_flatten_fu_124 <= select_ln1027_6_fu_455_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem_out_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
        phi_mul_reg_205 <= add_ln186_3_reg_846;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        phi_mul_reg_205 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_fu_120 <= 16'd0;
    end else if (((icmp_ln1027_3_fu_414_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        w_V_fu_120 <= select_ln1027_5_reg_818;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        add_ln1027_1_reg_772 <= add_ln1027_1_fu_305_p2;
        add_ln186_reg_764 <= add_ln186_fu_295_p2;
        ret_V_1_reg_759 <= grp_fu_601_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_3_fu_414_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        add_ln186_3_reg_846 <= add_ln186_3_fu_434_p2;
        out_c_V_reg_851 <= out_c_V_fu_439_p2;
        ret_V_reg_841 <= ret_V_fu_429_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        c_V_reg_836 <= c_V_fu_419_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        conv3_i11_i329_reg_727[15 : 0] <= conv3_i11_i329_fu_269_p1[15 : 0];
        icmp_ln1027_reg_743 <= icmp_ln1027_fu_273_p2;
        mul_ln11_1_reg_738 <= grp_fu_595_p2;
        ret_V_3_reg_732 <= grp_fu_589_p2;
        ret_V_4_reg_722 <= grp_fu_223_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        gmem_in_addr_read_reg_878 <= gmem_in_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        gmem_in_addr_reg_866 <= sext_ln46_fu_535_p1;
        gmem_out_addr_reg_872 <= sext_ln46_1_fu_572_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        groups_read_reg_664 <= groups;
        h_w_read_reg_671 <= h_w;
        in_r_read_reg_659 <= in_r;
        out_r_read_reg_654 <= out_r;
        zext_ln1513_reg_683[7 : 0] <= zext_ln1513_fu_219_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_1_fu_300_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        icmp_ln1027_2_reg_777 <= icmp_ln1027_2_fu_314_p2;
        select_ln1027_3_reg_790 <= select_ln1027_3_fu_333_p3;
        select_ln1027_4_reg_796 <= select_ln1027_4_fu_340_p3;
        select_ln34_reg_801 <= select_ln34_fu_353_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        lhs_reg_823 <= grp_fu_614_p2;
        select_ln1027_5_reg_818 <= select_ln1027_5_fu_404_p3;
        select_ln34_1_reg_812 <= select_ln34_1_fu_397_p3;
        zext_ln186_2_reg_828[7 : 0] <= zext_ln186_2_fu_411_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        mul_ln11_reg_707 <= grp_fu_582_p2;
        zext_ln186_reg_699[15 : 0] <= zext_ln186_fu_260_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        mul_ln186_1_reg_856 <= mul_ln186_1_fu_487_p2;
        mul_ln186_reg_861 <= mul_ln186_fu_495_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state31_io)) begin
        ap_ST_fsm_state31_blk = 1'b1;
    end else begin
        ap_ST_fsm_state31_blk = 1'b0;
    end
end

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

always @ (*) begin
    if ((gmem_in_RVALID == 1'b0)) begin
        ap_ST_fsm_state38_blk = 1'b1;
    end else begin
        ap_ST_fsm_state38_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_out_WREADY == 1'b0)) begin
        ap_ST_fsm_state39_blk = 1'b1;
    end else begin
        ap_ST_fsm_state39_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

always @ (*) begin
    if ((gmem_out_BVALID == 1'b0)) begin
        ap_ST_fsm_state44_blk = 1'b1;
    end else begin
        ap_ST_fsm_state44_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln1027_1_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1027_1_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state31_io) & (1'b1 == ap_CS_fsm_state31))) begin
        gmem_in_ARVALID = 1'b1;
    end else begin
        gmem_in_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_in_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state38))) begin
        gmem_in_RREADY = 1'b1;
    end else begin
        gmem_in_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        gmem_in_blk_n_AR = m_axi_gmem_in_ARREADY;
    end else begin
        gmem_in_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        gmem_in_blk_n_R = m_axi_gmem_in_RVALID;
    end else begin
        gmem_in_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state31_io) & (1'b1 == ap_CS_fsm_state31))) begin
        gmem_out_AWVALID = 1'b1;
    end else begin
        gmem_out_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_out_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
        gmem_out_BREADY = 1'b1;
    end else begin
        gmem_out_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_out_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state39))) begin
        gmem_out_WVALID = 1'b1;
    end else begin
        gmem_out_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        gmem_out_blk_n_AW = m_axi_gmem_out_AWREADY;
    end else begin
        gmem_out_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        gmem_out_blk_n_B = m_axi_gmem_out_BVALID;
    end else begin
        gmem_out_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        gmem_out_blk_n_W = m_axi_gmem_out_WREADY;
    end else begin
        gmem_out_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_223_ap_start = 1'b1;
    end else begin
        grp_fu_223_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((icmp_ln1027_1_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((icmp_ln1027_3_fu_414_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((1'b0 == ap_block_state31_io) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            if (((gmem_in_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state38))) begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end
        end
        ap_ST_fsm_state39 : begin
            if (((gmem_out_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state39))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            if (((gmem_out_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1027_1_fu_305_p2 = (indvar_flatten15_fu_132 + 40'd1);

assign add_ln1027_fu_449_p2 = (indvar_flatten_fu_124 + 24'd1);

assign add_ln186_1_fu_391_p2 = (select_ln1027_1_fu_371_p3 + zext_ln186_5_fu_387_p1);

assign add_ln186_3_fu_434_p2 = (phi_mul_reg_205 + zext_ln1513_reg_683);

assign add_ln186_fu_295_p0 = grp_fu_601_p2;

assign add_ln186_fu_295_p2 = (add_ln186_fu_295_p0 + zext_ln186_1_fu_291_p1);

assign add_ln46_1_fu_557_p2 = (zext_ln46_1_fu_553_p1 + out_r_read_reg_654);

assign add_ln46_fu_520_p2 = (zext_ln46_fu_516_p1 + in_r_read_reg_659);

assign add_ln840_fu_319_p2 = (h_V_fu_128 + 16'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

always @ (*) begin
    ap_block_state31_io = ((gmem_out_AWREADY == 1'b0) | (gmem_in_ARREADY == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign c_V_fu_419_p2 = (c_V_1_reg_194 + 16'd1);

assign conv3_i11_i329_fu_269_p1 = grp_fu_223_p2;

assign g_V_1_fu_444_p2 = (select_ln34_reg_801 + 8'd1);

assign grp_fu_223_p1 = grp_fu_223_p10;

assign grp_fu_223_p10 = groups;

assign grp_fu_582_p0 = grp_fu_582_p00;

assign grp_fu_582_p00 = h_w_read_reg_671;

assign grp_fu_582_p1 = grp_fu_582_p10;

assign grp_fu_582_p10 = groups_read_reg_664;

assign grp_fu_589_p0 = zext_ln186_fu_260_p1;

assign grp_fu_589_p1 = zext_ln186_fu_260_p1;

assign grp_fu_595_p0 = grp_fu_595_p00;

assign grp_fu_595_p00 = h_w_read_reg_671;

assign grp_fu_595_p1 = grp_fu_595_p10;

assign grp_fu_595_p10 = grp_fu_582_p2;

assign grp_fu_601_p0 = grp_fu_601_p00;

assign grp_fu_601_p00 = h_V_fu_128;

assign grp_fu_601_p1 = zext_ln186_reg_699;

assign grp_fu_607_p0 = grp_fu_607_p00;

assign grp_fu_607_p00 = add_ln840_fu_319_p2;

assign grp_fu_607_p1 = zext_ln186_reg_699;

assign grp_fu_614_p0 = conv3_i11_i329_reg_727;

assign grp_fu_614_p1 = grp_fu_614_p10;

assign grp_fu_614_p10 = select_ln34_fu_353_p3;

assign icmp_ln1027_1_fu_300_p2 = ((indvar_flatten15_fu_132 == mul_ln11_1_reg_738) ? 1'b1 : 1'b0);

assign icmp_ln1027_2_fu_314_p2 = ((indvar_flatten_fu_124 == mul_ln11_reg_707) ? 1'b1 : 1'b0);

assign icmp_ln1027_3_fu_414_p2 = ((c_V_1_reg_194 == ret_V_4_reg_722) ? 1'b1 : 1'b0);

assign icmp_ln1027_4_fu_328_p2 = ((g_V_fu_116 == groups_read_reg_664) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_273_p2 = ((groups_read_reg_664 == 8'd0) ? 1'b1 : 1'b0);

assign in_idx_V_fu_500_p2 = (mul_ln186_1_reg_856 + select_ln34_1_reg_812);

assign mul_ln186_1_fu_487_p1 = mul_ln186_1_fu_487_p10;

assign mul_ln186_1_fu_487_p10 = ret_V_reg_841;

assign mul_ln186_fu_495_p1 = mul_ln186_fu_495_p10;

assign mul_ln186_fu_495_p10 = out_c_V_reg_851;

assign or_ln34_fu_347_p2 = (select_ln1027_3_fu_333_p3 | icmp_ln1027_2_fu_314_p2);

assign out_c_V_fu_439_p2 = (phi_mul_reg_205 + zext_ln186_2_reg_828);

assign out_idx_V_fu_504_p2 = (mul_ln186_reg_861 + select_ln34_1_reg_812);

assign ret_V_fu_429_p2 = (lhs_reg_823 + zext_ln1495_fu_425_p1);

assign select_ln1027_1_fu_371_p1 = grp_fu_607_p2;

assign select_ln1027_1_fu_371_p3 = ((icmp_ln1027_2_reg_777[0:0] == 1'b1) ? select_ln1027_1_fu_371_p1 : ret_V_1_reg_759);

assign select_ln1027_2_fu_376_p1 = grp_fu_607_p2;

assign select_ln1027_2_fu_376_p3 = ((icmp_ln1027_2_reg_777[0:0] == 1'b1) ? select_ln1027_2_fu_376_p1 : add_ln186_reg_764);

assign select_ln1027_3_fu_333_p3 = ((icmp_ln1027_2_fu_314_p2[0:0] == 1'b1) ? icmp_ln1027_reg_743 : icmp_ln1027_4_fu_328_p2);

assign select_ln1027_4_fu_340_p3 = ((icmp_ln1027_2_fu_314_p2[0:0] == 1'b1) ? add_ln840_fu_319_p2 : h_V_fu_128);

assign select_ln1027_5_fu_404_p3 = ((select_ln1027_3_reg_790[0:0] == 1'b1) ? w_V_3_fu_381_p2 : select_ln1027_fu_365_p3);

assign select_ln1027_6_fu_455_p3 = ((icmp_ln1027_2_reg_777[0:0] == 1'b1) ? 24'd1 : add_ln1027_fu_449_p2);

assign select_ln1027_fu_365_p3 = ((icmp_ln1027_2_reg_777[0:0] == 1'b1) ? 16'd0 : w_V_fu_120);

assign select_ln34_1_fu_397_p3 = ((select_ln1027_3_reg_790[0:0] == 1'b1) ? add_ln186_1_fu_391_p2 : select_ln1027_2_fu_376_p3);

assign select_ln34_fu_353_p3 = ((or_ln34_fu_347_p2[0:0] == 1'b1) ? 8'd0 : g_V_fu_116);

assign sext_ln46_1_fu_572_p1 = $signed(trunc_ln46_1_fu_562_p4);

assign sext_ln46_fu_535_p1 = $signed(trunc_ln_fu_525_p4);

assign shl_ln46_1_fu_545_p3 = {{out_idx_V_fu_504_p2}, {2'd0}};

assign shl_ln_fu_508_p3 = {{in_idx_V_fu_500_p2}, {2'd0}};

assign trunc_ln46_1_fu_562_p4 = {{add_ln46_1_fu_557_p2[63:2]}};

assign trunc_ln_fu_525_p4 = {{add_ln46_fu_520_p2[63:2]}};

assign w_V_3_fu_381_p2 = (select_ln1027_fu_365_p3 + 16'd1);

assign zext_ln1495_fu_425_p1 = c_V_1_reg_194;

assign zext_ln1513_fu_219_p1 = groups;

assign zext_ln186_1_fu_291_p1 = w_V_fu_120;

assign zext_ln186_2_fu_411_p1 = select_ln34_reg_801;

assign zext_ln186_5_fu_387_p1 = w_V_3_fu_381_p2;

assign zext_ln186_fu_260_p1 = h_w_read_reg_671;

assign zext_ln46_1_fu_553_p1 = shl_ln46_1_fu_545_p3;

assign zext_ln46_fu_516_p1 = shl_ln_fu_508_p3;

always @ (posedge ap_clk) begin
    zext_ln1513_reg_683[15:8] <= 8'b00000000;
    zext_ln186_reg_699[31:16] <= 16'b0000000000000000;
    conv3_i11_i329_reg_727[23:16] <= 8'b00000000;
    zext_ln186_2_reg_828[15:8] <= 8'b00000000;
end

endmodule //channel_shuffle
