// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_bn_relu_Block_entry352_proc1_Pipeline_VITIS_LOOP_117_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        add_i_i1015,
        conv_i_i961,
        bound,
        local_feature_in_blk_1_address0,
        local_feature_in_blk_1_ce0,
        local_feature_in_blk_1_we0,
        local_feature_in_blk_1_d0,
        local_feature_in_blk_1_address1,
        local_feature_in_blk_1_ce1,
        local_feature_in_blk_1_we1,
        local_feature_in_blk_1_d1,
        local_feature_in_blk_address0,
        local_feature_in_blk_ce0,
        local_feature_in_blk_we0,
        local_feature_in_blk_d0,
        local_feature_in_blk_address1,
        local_feature_in_blk_ce1,
        local_feature_in_blk_we1,
        local_feature_in_blk_d1,
        C_in,
        tmp22,
        zext_ln87_2,
        phi_mul594,
        mul_ln105_1,
        add_ln116,
        feature_in,
        sub_ln131
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [31:0] m_axi_gmem1_WDATA;
output  [3:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [31:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [31:0] add_i_i1015;
input  [15:0] conv_i_i961;
input  [79:0] bound;
output  [7:0] local_feature_in_blk_1_address0;
output   local_feature_in_blk_1_ce0;
output   local_feature_in_blk_1_we0;
output  [31:0] local_feature_in_blk_1_d0;
output  [7:0] local_feature_in_blk_1_address1;
output   local_feature_in_blk_1_ce1;
output   local_feature_in_blk_1_we1;
output  [31:0] local_feature_in_blk_1_d1;
output  [7:0] local_feature_in_blk_address0;
output   local_feature_in_blk_ce0;
output   local_feature_in_blk_we0;
output  [31:0] local_feature_in_blk_d0;
output  [7:0] local_feature_in_blk_address1;
output   local_feature_in_blk_ce1;
output   local_feature_in_blk_we1;
output  [31:0] local_feature_in_blk_d1;
input  [15:0] C_in;
input  [0:0] tmp22;
input  [15:0] zext_ln87_2;
input  [31:0] phi_mul594;
input  [31:0] mul_ln105_1;
input  [31:0] add_ln116;
input  [63:0] feature_in;
input  [61:0] sub_ln131;

reg ap_idle;
reg m_axi_gmem1_ARVALID;
reg m_axi_gmem1_RREADY;
reg local_feature_in_blk_1_ce0;
reg local_feature_in_blk_1_we0;
reg local_feature_in_blk_1_ce1;
reg local_feature_in_blk_1_we1;
reg local_feature_in_blk_ce0;
reg local_feature_in_blk_we0;
reg local_feature_in_blk_ce1;
reg local_feature_in_blk_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg   [0:0] or_ln1027_reg_632;
reg   [0:0] or_ln1027_reg_632_pp0_iter4_reg;
reg    ap_block_state6_io;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
reg   [0:0] and_ln1027_reg_660;
reg   [0:0] and_ln1027_reg_660_pp0_iter11_reg;
reg    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1027_fu_311_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem1_blk_n_AR;
reg   [0:0] first_iter_0_reg_236;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] zext_ln87_2_cast_fu_248_p1;
reg   [31:0] zext_ln87_2_cast_reg_607;
wire   [31:0] conv_i_i961_cast_fu_252_p1;
reg   [31:0] conv_i_i961_cast_reg_612;
wire   [0:0] tmp23_fu_305_p2;
reg   [0:0] tmp23_reg_618;
reg   [0:0] icmp_ln1027_reg_623;
wire   [0:0] icmp_ln1027_3_fu_331_p2;
reg   [0:0] icmp_ln1027_3_reg_627;
wire   [0:0] or_ln1027_fu_336_p2;
reg   [0:0] or_ln1027_reg_632_pp0_iter2_reg;
reg   [0:0] or_ln1027_reg_632_pp0_iter3_reg;
wire   [31:0] w_in_1_mid1_fu_354_p2;
reg   [31:0] w_in_1_mid1_reg_636;
wire   [0:0] cmp_i_i962_mid1_fu_359_p2;
reg   [0:0] cmp_i_i962_mid1_reg_641;
wire  signed [31:0] select_ln1027_11_fu_364_p3;
reg  signed [31:0] select_ln1027_11_reg_646;
wire   [7:0] add_ln131_1_fu_411_p2;
reg   [7:0] add_ln131_1_reg_651;
wire   [0:0] trunc_ln131_2_fu_417_p1;
reg   [0:0] trunc_ln131_2_reg_656;
reg   [0:0] trunc_ln131_2_reg_656_pp0_iter2_reg;
reg   [0:0] trunc_ln131_2_reg_656_pp0_iter3_reg;
reg   [0:0] trunc_ln131_2_reg_656_pp0_iter4_reg;
reg   [0:0] trunc_ln131_2_reg_656_pp0_iter5_reg;
reg   [0:0] trunc_ln131_2_reg_656_pp0_iter6_reg;
reg   [0:0] trunc_ln131_2_reg_656_pp0_iter7_reg;
reg   [0:0] trunc_ln131_2_reg_656_pp0_iter8_reg;
reg   [0:0] trunc_ln131_2_reg_656_pp0_iter9_reg;
reg   [0:0] trunc_ln131_2_reg_656_pp0_iter10_reg;
reg   [0:0] trunc_ln131_2_reg_656_pp0_iter11_reg;
reg   [0:0] trunc_ln131_2_reg_656_pp0_iter12_reg;
wire   [0:0] and_ln1027_fu_466_p2;
reg   [0:0] and_ln1027_reg_660_pp0_iter3_reg;
reg   [0:0] and_ln1027_reg_660_pp0_iter4_reg;
reg   [0:0] and_ln1027_reg_660_pp0_iter5_reg;
reg   [0:0] and_ln1027_reg_660_pp0_iter6_reg;
reg   [0:0] and_ln1027_reg_660_pp0_iter7_reg;
reg   [0:0] and_ln1027_reg_660_pp0_iter8_reg;
reg   [0:0] and_ln1027_reg_660_pp0_iter9_reg;
reg   [0:0] and_ln1027_reg_660_pp0_iter10_reg;
reg   [0:0] and_ln1027_reg_660_pp0_iter12_reg;
wire   [31:0] mul_ln1027_fu_471_p2;
reg   [31:0] mul_ln1027_reg_664;
reg   [7:0] local_feature_in_blk_addr_reg_669;
reg   [7:0] local_feature_in_blk_addr_reg_669_pp0_iter3_reg;
reg   [7:0] local_feature_in_blk_addr_reg_669_pp0_iter4_reg;
reg   [7:0] local_feature_in_blk_addr_reg_669_pp0_iter5_reg;
reg   [7:0] local_feature_in_blk_addr_reg_669_pp0_iter6_reg;
reg   [7:0] local_feature_in_blk_addr_reg_669_pp0_iter7_reg;
reg   [7:0] local_feature_in_blk_addr_reg_669_pp0_iter8_reg;
reg   [7:0] local_feature_in_blk_addr_reg_669_pp0_iter9_reg;
reg   [7:0] local_feature_in_blk_addr_reg_669_pp0_iter10_reg;
reg   [7:0] local_feature_in_blk_addr_reg_669_pp0_iter11_reg;
reg   [7:0] local_feature_in_blk_addr_reg_669_pp0_iter12_reg;
reg   [7:0] local_feature_in_blk_1_addr_reg_674;
reg   [7:0] local_feature_in_blk_1_addr_reg_674_pp0_iter3_reg;
reg   [7:0] local_feature_in_blk_1_addr_reg_674_pp0_iter4_reg;
reg   [7:0] local_feature_in_blk_1_addr_reg_674_pp0_iter5_reg;
reg   [7:0] local_feature_in_blk_1_addr_reg_674_pp0_iter6_reg;
reg   [7:0] local_feature_in_blk_1_addr_reg_674_pp0_iter7_reg;
reg   [7:0] local_feature_in_blk_1_addr_reg_674_pp0_iter8_reg;
reg   [7:0] local_feature_in_blk_1_addr_reg_674_pp0_iter9_reg;
reg   [7:0] local_feature_in_blk_1_addr_reg_674_pp0_iter10_reg;
reg   [7:0] local_feature_in_blk_1_addr_reg_674_pp0_iter11_reg;
reg   [7:0] local_feature_in_blk_1_addr_reg_674_pp0_iter12_reg;
wire   [31:0] add_ln1027_5_fu_489_p2;
reg   [31:0] add_ln1027_5_reg_679;
reg   [61:0] sext_ln117_mid2_v_reg_684;
wire   [31:0] bitcast_ln128_fu_536_p1;
reg   [31:0] bitcast_ln128_reg_699;
reg   [0:0] ap_phi_mux_first_iter_0_phi_fu_240_p4;
wire    ap_loop_init;
wire   [63:0] zext_ln131_fu_475_p1;
wire  signed [63:0] sext_ln1027_2_fu_520_p1;
reg   [15:0] c_in_3_fu_110;
wire   [15:0] add_ln117_fu_421_p2;
reg   [63:0] w_in_blk_fu_114;
wire   [63:0] select_ln1027_12_fu_372_p3;
reg   [79:0] indvar_flatten_fu_118;
wire   [79:0] add_ln1027_fu_316_p2;
wire   [31:0] trunc_ln1027_fu_277_p1;
wire   [31:0] w_in_fu_281_p2;
wire   [0:0] tmp_fu_286_p3;
wire   [0:0] cmp_i_i962_fu_300_p2;
wire   [0:0] rev_fu_294_p2;
wire   [63:0] add_ln116_1_fu_325_p2;
wire   [31:0] trunc_ln1027_1_fu_350_p1;
wire   [5:0] trunc_ln131_fu_380_p1;
wire   [5:0] trunc_ln131_1_fu_383_p1;
wire   [5:0] add_ln131_fu_387_p2;
wire   [15:0] select_ln1027_10_fu_342_p3;
wire   [7:0] tmp_s_fu_393_p3;
wire   [7:0] lshr_ln4_fu_401_p4;
wire   [0:0] tmp_1_fu_442_p3;
wire   [0:0] rev21_fu_449_p2;
wire   [0:0] tmp23_mid1_fu_455_p2;
wire   [0:0] select_ln1027_fu_460_p3;
wire   [15:0] mul_ln1027_fu_471_p1;
wire   [31:0] add_ln1027_3_fu_480_p2;
wire   [31:0] add_ln1027_4_fu_484_p2;
wire   [33:0] sext_ln117_mid2_v_v_v_v_v_fu_494_p3;
wire  signed [63:0] sext_ln1027_fu_501_p1;
wire   [63:0] add_ln1027_6_fu_505_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv_bn_relu_mul_32s_16ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_32s_16ns_32_1_1_U47(
    .din0(select_ln1027_11_reg_646),
    .din1(mul_ln1027_fu_471_p1),
    .dout(mul_ln1027_fu_471_p2)
);

conv_bn_relu_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_in_3_fu_110 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_fu_311_p2 == 1'd0))) begin
            c_in_3_fu_110 <= add_ln117_fu_421_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_reg_623 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_0_reg_236 <= 1'd0;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_0_reg_236 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_118 <= 80'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_fu_311_p2 == 1'd0))) begin
            indvar_flatten_fu_118 <= add_ln1027_fu_316_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_in_blk_fu_114 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_fu_311_p2 == 1'd0))) begin
            w_in_blk_fu_114 <= select_ln1027_12_fu_372_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln1027_5_reg_679 <= add_ln1027_5_fu_489_p2;
        and_ln1027_reg_660 <= and_ln1027_fu_466_p2;
        and_ln1027_reg_660_pp0_iter10_reg <= and_ln1027_reg_660_pp0_iter9_reg;
        and_ln1027_reg_660_pp0_iter11_reg <= and_ln1027_reg_660_pp0_iter10_reg;
        and_ln1027_reg_660_pp0_iter12_reg <= and_ln1027_reg_660_pp0_iter11_reg;
        and_ln1027_reg_660_pp0_iter3_reg <= and_ln1027_reg_660;
        and_ln1027_reg_660_pp0_iter4_reg <= and_ln1027_reg_660_pp0_iter3_reg;
        and_ln1027_reg_660_pp0_iter5_reg <= and_ln1027_reg_660_pp0_iter4_reg;
        and_ln1027_reg_660_pp0_iter6_reg <= and_ln1027_reg_660_pp0_iter5_reg;
        and_ln1027_reg_660_pp0_iter7_reg <= and_ln1027_reg_660_pp0_iter6_reg;
        and_ln1027_reg_660_pp0_iter8_reg <= and_ln1027_reg_660_pp0_iter7_reg;
        and_ln1027_reg_660_pp0_iter9_reg <= and_ln1027_reg_660_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        local_feature_in_blk_1_addr_reg_674 <= zext_ln131_fu_475_p1;
        local_feature_in_blk_1_addr_reg_674_pp0_iter10_reg <= local_feature_in_blk_1_addr_reg_674_pp0_iter9_reg;
        local_feature_in_blk_1_addr_reg_674_pp0_iter11_reg <= local_feature_in_blk_1_addr_reg_674_pp0_iter10_reg;
        local_feature_in_blk_1_addr_reg_674_pp0_iter12_reg <= local_feature_in_blk_1_addr_reg_674_pp0_iter11_reg;
        local_feature_in_blk_1_addr_reg_674_pp0_iter3_reg <= local_feature_in_blk_1_addr_reg_674;
        local_feature_in_blk_1_addr_reg_674_pp0_iter4_reg <= local_feature_in_blk_1_addr_reg_674_pp0_iter3_reg;
        local_feature_in_blk_1_addr_reg_674_pp0_iter5_reg <= local_feature_in_blk_1_addr_reg_674_pp0_iter4_reg;
        local_feature_in_blk_1_addr_reg_674_pp0_iter6_reg <= local_feature_in_blk_1_addr_reg_674_pp0_iter5_reg;
        local_feature_in_blk_1_addr_reg_674_pp0_iter7_reg <= local_feature_in_blk_1_addr_reg_674_pp0_iter6_reg;
        local_feature_in_blk_1_addr_reg_674_pp0_iter8_reg <= local_feature_in_blk_1_addr_reg_674_pp0_iter7_reg;
        local_feature_in_blk_1_addr_reg_674_pp0_iter9_reg <= local_feature_in_blk_1_addr_reg_674_pp0_iter8_reg;
        local_feature_in_blk_addr_reg_669 <= zext_ln131_fu_475_p1;
        local_feature_in_blk_addr_reg_669_pp0_iter10_reg <= local_feature_in_blk_addr_reg_669_pp0_iter9_reg;
        local_feature_in_blk_addr_reg_669_pp0_iter11_reg <= local_feature_in_blk_addr_reg_669_pp0_iter10_reg;
        local_feature_in_blk_addr_reg_669_pp0_iter12_reg <= local_feature_in_blk_addr_reg_669_pp0_iter11_reg;
        local_feature_in_blk_addr_reg_669_pp0_iter3_reg <= local_feature_in_blk_addr_reg_669;
        local_feature_in_blk_addr_reg_669_pp0_iter4_reg <= local_feature_in_blk_addr_reg_669_pp0_iter3_reg;
        local_feature_in_blk_addr_reg_669_pp0_iter5_reg <= local_feature_in_blk_addr_reg_669_pp0_iter4_reg;
        local_feature_in_blk_addr_reg_669_pp0_iter6_reg <= local_feature_in_blk_addr_reg_669_pp0_iter5_reg;
        local_feature_in_blk_addr_reg_669_pp0_iter7_reg <= local_feature_in_blk_addr_reg_669_pp0_iter6_reg;
        local_feature_in_blk_addr_reg_669_pp0_iter8_reg <= local_feature_in_blk_addr_reg_669_pp0_iter7_reg;
        local_feature_in_blk_addr_reg_669_pp0_iter9_reg <= local_feature_in_blk_addr_reg_669_pp0_iter8_reg;
        mul_ln1027_reg_664 <= mul_ln1027_fu_471_p2;
        or_ln1027_reg_632_pp0_iter2_reg <= or_ln1027_reg_632;
        or_ln1027_reg_632_pp0_iter3_reg <= or_ln1027_reg_632_pp0_iter2_reg;
        or_ln1027_reg_632_pp0_iter4_reg <= or_ln1027_reg_632_pp0_iter3_reg;
        sext_ln117_mid2_v_reg_684 <= {{add_ln1027_6_fu_505_p2[63:2]}};
        trunc_ln131_2_reg_656_pp0_iter10_reg <= trunc_ln131_2_reg_656_pp0_iter9_reg;
        trunc_ln131_2_reg_656_pp0_iter11_reg <= trunc_ln131_2_reg_656_pp0_iter10_reg;
        trunc_ln131_2_reg_656_pp0_iter12_reg <= trunc_ln131_2_reg_656_pp0_iter11_reg;
        trunc_ln131_2_reg_656_pp0_iter2_reg <= trunc_ln131_2_reg_656;
        trunc_ln131_2_reg_656_pp0_iter3_reg <= trunc_ln131_2_reg_656_pp0_iter2_reg;
        trunc_ln131_2_reg_656_pp0_iter4_reg <= trunc_ln131_2_reg_656_pp0_iter3_reg;
        trunc_ln131_2_reg_656_pp0_iter5_reg <= trunc_ln131_2_reg_656_pp0_iter4_reg;
        trunc_ln131_2_reg_656_pp0_iter6_reg <= trunc_ln131_2_reg_656_pp0_iter5_reg;
        trunc_ln131_2_reg_656_pp0_iter7_reg <= trunc_ln131_2_reg_656_pp0_iter6_reg;
        trunc_ln131_2_reg_656_pp0_iter8_reg <= trunc_ln131_2_reg_656_pp0_iter7_reg;
        trunc_ln131_2_reg_656_pp0_iter9_reg <= trunc_ln131_2_reg_656_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_fu_311_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln131_1_reg_651 <= add_ln131_1_fu_411_p2;
        cmp_i_i962_mid1_reg_641 <= cmp_i_i962_mid1_fu_359_p2;
        icmp_ln1027_3_reg_627 <= icmp_ln1027_3_fu_331_p2;
        or_ln1027_reg_632 <= or_ln1027_fu_336_p2;
        select_ln1027_11_reg_646 <= select_ln1027_11_fu_364_p3;
        trunc_ln131_2_reg_656 <= trunc_ln131_2_fu_417_p1;
        w_in_1_mid1_reg_636 <= w_in_1_mid1_fu_354_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        conv_i_i961_cast_reg_612[15 : 0] <= conv_i_i961_cast_fu_252_p1[15 : 0];
        icmp_ln1027_reg_623 <= icmp_ln1027_fu_311_p2;
        tmp23_reg_618 <= tmp23_fu_305_p2;
        zext_ln87_2_cast_reg_607[15 : 0] <= zext_ln87_2_cast_fu_248_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1027_reg_660_pp0_iter11_reg))) begin
        bitcast_ln128_reg_699 <= bitcast_ln128_fu_536_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_fu_311_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_reg_623 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_0_phi_fu_240_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_0_phi_fu_240_p4 = first_iter_0_reg_236;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (or_ln1027_reg_632_pp0_iter4_reg == 1'd1))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln1027_reg_660_pp0_iter11_reg))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_feature_in_blk_1_ce0 = 1'b1;
    end else begin
        local_feature_in_blk_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_feature_in_blk_1_ce1 = 1'b1;
    end else begin
        local_feature_in_blk_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln131_2_reg_656_pp0_iter12_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1027_reg_660_pp0_iter12_reg))) begin
        local_feature_in_blk_1_we0 = 1'b1;
    end else begin
        local_feature_in_blk_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln131_2_reg_656 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'd0 == and_ln1027_fu_466_p2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_feature_in_blk_1_we1 = 1'b1;
    end else begin
        local_feature_in_blk_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_feature_in_blk_ce0 = 1'b1;
    end else begin
        local_feature_in_blk_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_feature_in_blk_ce1 = 1'b1;
    end else begin
        local_feature_in_blk_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln131_2_reg_656_pp0_iter12_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1027_reg_660_pp0_iter12_reg))) begin
        local_feature_in_blk_we0 = 1'b1;
    end else begin
        local_feature_in_blk_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln131_2_reg_656 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'd0 == and_ln1027_fu_466_p2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_feature_in_blk_we1 = 1'b1;
    end else begin
        local_feature_in_blk_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln1027_reg_632_pp0_iter4_reg == 1'd1))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1027_reg_660_pp0_iter11_reg))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1027_3_fu_480_p2 = (phi_mul594 + mul_ln1027_reg_664);

assign add_ln1027_4_fu_484_p2 = (add_ln1027_3_fu_480_p2 + mul_ln105_1);

assign add_ln1027_5_fu_489_p2 = (add_ln1027_4_fu_484_p2 + add_ln116);

assign add_ln1027_6_fu_505_p2 = ($signed(sext_ln1027_fu_501_p1) + $signed(feature_in));

assign add_ln1027_fu_316_p2 = (indvar_flatten_fu_118 + 80'd1);

assign add_ln116_1_fu_325_p2 = (w_in_blk_fu_114 + 64'd1);

assign add_ln117_fu_421_p2 = (select_ln1027_10_fu_342_p3 + 16'd1);

assign add_ln131_1_fu_411_p2 = (tmp_s_fu_393_p3 + lshr_ln4_fu_401_p4);

assign add_ln131_fu_387_p2 = (trunc_ln131_fu_380_p1 + trunc_ln131_1_fu_383_p1);

assign and_ln1027_fu_466_p2 = (tmp22 & select_ln1027_fu_460_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'd1 == and_ln1027_reg_660_pp0_iter11_reg) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'd1 == and_ln1027_reg_660_pp0_iter11_reg) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state13_pp0_stage0_iter12 = ((1'd1 == and_ln1027_reg_660_pp0_iter11_reg) & (m_axi_gmem1_RVALID == 1'b0));
end

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_io = ((m_axi_gmem1_ARREADY == 1'b0) & (or_ln1027_reg_632_pp0_iter4_reg == 1'd1));
end

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign bitcast_ln128_fu_536_p1 = m_axi_gmem1_RDATA;

assign cmp_i_i962_fu_300_p2 = (($signed(w_in_fu_281_p2) < $signed(conv_i_i961_cast_reg_612)) ? 1'b1 : 1'b0);

assign cmp_i_i962_mid1_fu_359_p2 = (($signed(w_in_1_mid1_fu_354_p2) < $signed(conv_i_i961_cast_reg_612)) ? 1'b1 : 1'b0);

assign conv_i_i961_cast_fu_252_p1 = conv_i_i961;

assign icmp_ln1027_3_fu_331_p2 = ((c_in_3_fu_110 == C_in) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_311_p2 = ((indvar_flatten_fu_118 == bound) ? 1'b1 : 1'b0);

assign local_feature_in_blk_1_address0 = local_feature_in_blk_1_addr_reg_674_pp0_iter12_reg;

assign local_feature_in_blk_1_address1 = zext_ln131_fu_475_p1;

assign local_feature_in_blk_1_d0 = bitcast_ln128_reg_699;

assign local_feature_in_blk_1_d1 = 32'd0;

assign local_feature_in_blk_address0 = local_feature_in_blk_addr_reg_669_pp0_iter12_reg;

assign local_feature_in_blk_address1 = zext_ln131_fu_475_p1;

assign local_feature_in_blk_d0 = bitcast_ln128_reg_699;

assign local_feature_in_blk_d1 = 32'd0;

assign lshr_ln4_fu_401_p4 = {{select_ln1027_10_fu_342_p3[8:1]}};

assign m_axi_gmem1_ARADDR = sext_ln1027_2_fu_520_p1;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd0;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 32'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 4'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign mul_ln1027_fu_471_p1 = zext_ln87_2_cast_reg_607;

assign or_ln1027_fu_336_p2 = (icmp_ln1027_3_fu_331_p2 | ap_phi_mux_first_iter_0_phi_fu_240_p4);

assign rev21_fu_449_p2 = (tmp_1_fu_442_p3 ^ 1'd1);

assign rev_fu_294_p2 = (tmp_fu_286_p3 ^ 1'd1);

assign select_ln1027_10_fu_342_p3 = ((icmp_ln1027_3_fu_331_p2[0:0] == 1'b1) ? 16'd0 : c_in_3_fu_110);

assign select_ln1027_11_fu_364_p3 = ((icmp_ln1027_3_fu_331_p2[0:0] == 1'b1) ? trunc_ln1027_1_fu_350_p1 : trunc_ln1027_fu_277_p1);

assign select_ln1027_12_fu_372_p3 = ((icmp_ln1027_3_fu_331_p2[0:0] == 1'b1) ? add_ln116_1_fu_325_p2 : w_in_blk_fu_114);

assign select_ln1027_fu_460_p3 = ((icmp_ln1027_3_reg_627[0:0] == 1'b1) ? tmp23_mid1_fu_455_p2 : tmp23_reg_618);

assign sext_ln1027_2_fu_520_p1 = $signed(sext_ln117_mid2_v_reg_684);

assign sext_ln1027_fu_501_p1 = $signed(sext_ln117_mid2_v_v_v_v_v_fu_494_p3);

assign sext_ln117_mid2_v_v_v_v_v_fu_494_p3 = {{add_ln1027_5_reg_679}, {2'd0}};

assign tmp23_fu_305_p2 = (rev_fu_294_p2 & cmp_i_i962_fu_300_p2);

assign tmp23_mid1_fu_455_p2 = (rev21_fu_449_p2 & cmp_i_i962_mid1_reg_641);

assign tmp_1_fu_442_p3 = w_in_1_mid1_reg_636[32'd31];

assign tmp_fu_286_p3 = w_in_fu_281_p2[32'd31];

assign tmp_s_fu_393_p3 = {{add_ln131_fu_387_p2}, {2'd0}};

assign trunc_ln1027_1_fu_350_p1 = add_ln116_1_fu_325_p2[31:0];

assign trunc_ln1027_fu_277_p1 = w_in_blk_fu_114[31:0];

assign trunc_ln131_1_fu_383_p1 = select_ln1027_12_fu_372_p3[5:0];

assign trunc_ln131_2_fu_417_p1 = select_ln1027_10_fu_342_p3[0:0];

assign trunc_ln131_fu_380_p1 = sub_ln131[5:0];

assign w_in_1_mid1_fu_354_p2 = (trunc_ln1027_1_fu_350_p1 + add_i_i1015);

assign w_in_fu_281_p2 = (trunc_ln1027_fu_277_p1 + add_i_i1015);

assign zext_ln131_fu_475_p1 = add_ln131_1_reg_651;

assign zext_ln87_2_cast_fu_248_p1 = zext_ln87_2;

always @ (posedge ap_clk) begin
    zext_ln87_2_cast_reg_607[31:16] <= 16'b0000000000000000;
    conv_i_i961_cast_reg_612[31:16] <= 16'b0000000000000000;
end

endmodule //conv_bn_relu_Block_entry352_proc1_Pipeline_VITIS_LOOP_117_7
