// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_bn_relu_Block_entry352_proc1_Pipeline_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        local_conv_kernel_blk_address0,
        local_conv_kernel_blk_ce0,
        local_conv_kernel_blk_we0,
        local_conv_kernel_blk_d0,
        local_conv_kernel_blk_1_address0,
        local_conv_kernel_blk_1_ce0,
        local_conv_kernel_blk_1_we0,
        local_conv_kernel_blk_1_d0,
        local_conv_kernel_blk_2_address0,
        local_conv_kernel_blk_2_ce0,
        local_conv_kernel_blk_2_we0,
        local_conv_kernel_blk_2_d0,
        local_conv_kernel_blk_3_address0,
        local_conv_kernel_blk_3_ce0,
        local_conv_kernel_blk_3_we0,
        local_conv_kernel_blk_3_d0,
        local_conv_kernel_blk_4_address0,
        local_conv_kernel_blk_4_ce0,
        local_conv_kernel_blk_4_we0,
        local_conv_kernel_blk_4_d0,
        local_conv_kernel_blk_5_address0,
        local_conv_kernel_blk_5_ce0,
        local_conv_kernel_blk_5_we0,
        local_conv_kernel_blk_5_d0,
        local_conv_kernel_blk_6_address0,
        local_conv_kernel_blk_6_ce0,
        local_conv_kernel_blk_6_we0,
        local_conv_kernel_blk_6_d0,
        local_conv_kernel_blk_7_address0,
        local_conv_kernel_blk_7_ce0,
        local_conv_kernel_blk_7_we0,
        local_conv_kernel_blk_7_d0,
        local_conv_kernel_blk_8_address0,
        local_conv_kernel_blk_8_ce0,
        local_conv_kernel_blk_8_we0,
        local_conv_kernel_blk_8_d0,
        local_conv_kernel_blk_9_address0,
        local_conv_kernel_blk_9_ce0,
        local_conv_kernel_blk_9_we0,
        local_conv_kernel_blk_9_d0,
        local_conv_kernel_blk_10_address0,
        local_conv_kernel_blk_10_ce0,
        local_conv_kernel_blk_10_we0,
        local_conv_kernel_blk_10_d0,
        local_conv_kernel_blk_11_address0,
        local_conv_kernel_blk_11_ce0,
        local_conv_kernel_blk_11_we0,
        local_conv_kernel_blk_11_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] local_conv_kernel_blk_address0;
output   local_conv_kernel_blk_ce0;
output   local_conv_kernel_blk_we0;
output  [31:0] local_conv_kernel_blk_d0;
output  [5:0] local_conv_kernel_blk_1_address0;
output   local_conv_kernel_blk_1_ce0;
output   local_conv_kernel_blk_1_we0;
output  [31:0] local_conv_kernel_blk_1_d0;
output  [5:0] local_conv_kernel_blk_2_address0;
output   local_conv_kernel_blk_2_ce0;
output   local_conv_kernel_blk_2_we0;
output  [31:0] local_conv_kernel_blk_2_d0;
output  [5:0] local_conv_kernel_blk_3_address0;
output   local_conv_kernel_blk_3_ce0;
output   local_conv_kernel_blk_3_we0;
output  [31:0] local_conv_kernel_blk_3_d0;
output  [5:0] local_conv_kernel_blk_4_address0;
output   local_conv_kernel_blk_4_ce0;
output   local_conv_kernel_blk_4_we0;
output  [31:0] local_conv_kernel_blk_4_d0;
output  [5:0] local_conv_kernel_blk_5_address0;
output   local_conv_kernel_blk_5_ce0;
output   local_conv_kernel_blk_5_we0;
output  [31:0] local_conv_kernel_blk_5_d0;
output  [5:0] local_conv_kernel_blk_6_address0;
output   local_conv_kernel_blk_6_ce0;
output   local_conv_kernel_blk_6_we0;
output  [31:0] local_conv_kernel_blk_6_d0;
output  [5:0] local_conv_kernel_blk_7_address0;
output   local_conv_kernel_blk_7_ce0;
output   local_conv_kernel_blk_7_we0;
output  [31:0] local_conv_kernel_blk_7_d0;
output  [5:0] local_conv_kernel_blk_8_address0;
output   local_conv_kernel_blk_8_ce0;
output   local_conv_kernel_blk_8_we0;
output  [31:0] local_conv_kernel_blk_8_d0;
output  [5:0] local_conv_kernel_blk_9_address0;
output   local_conv_kernel_blk_9_ce0;
output   local_conv_kernel_blk_9_we0;
output  [31:0] local_conv_kernel_blk_9_d0;
output  [5:0] local_conv_kernel_blk_10_address0;
output   local_conv_kernel_blk_10_ce0;
output   local_conv_kernel_blk_10_we0;
output  [31:0] local_conv_kernel_blk_10_d0;
output  [5:0] local_conv_kernel_blk_11_address0;
output   local_conv_kernel_blk_11_ce0;
output   local_conv_kernel_blk_11_we0;
output  [31:0] local_conv_kernel_blk_11_d0;

reg ap_idle;
reg local_conv_kernel_blk_ce0;
reg local_conv_kernel_blk_we0;
reg local_conv_kernel_blk_1_ce0;
reg local_conv_kernel_blk_1_we0;
reg local_conv_kernel_blk_2_ce0;
reg local_conv_kernel_blk_2_we0;
reg local_conv_kernel_blk_3_ce0;
reg local_conv_kernel_blk_3_we0;
reg local_conv_kernel_blk_4_ce0;
reg local_conv_kernel_blk_4_we0;
reg local_conv_kernel_blk_5_ce0;
reg local_conv_kernel_blk_5_we0;
reg local_conv_kernel_blk_6_ce0;
reg local_conv_kernel_blk_6_we0;
reg local_conv_kernel_blk_7_ce0;
reg local_conv_kernel_blk_7_we0;
reg local_conv_kernel_blk_8_ce0;
reg local_conv_kernel_blk_8_we0;
reg local_conv_kernel_blk_9_ce0;
reg local_conv_kernel_blk_9_we0;
reg local_conv_kernel_blk_10_ce0;
reg local_conv_kernel_blk_10_we0;
reg local_conv_kernel_blk_11_ce0;
reg local_conv_kernel_blk_11_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] exitcond360614_fu_319_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond360614_reg_586;
reg   [0:0] exitcond360614_reg_586_pp0_iter2_reg;
reg   [0:0] exitcond360614_reg_586_pp0_iter3_reg;
reg   [0:0] exitcond360614_reg_586_pp0_iter4_reg;
reg   [0:0] exitcond360614_reg_586_pp0_iter5_reg;
reg   [0:0] exitcond360614_reg_586_pp0_iter6_reg;
reg   [0:0] exitcond360614_reg_586_pp0_iter7_reg;
reg   [0:0] exitcond360614_reg_586_pp0_iter8_reg;
reg   [0:0] exitcond360614_reg_586_pp0_iter9_reg;
reg   [0:0] exitcond360614_reg_586_pp0_iter10_reg;
reg   [0:0] tmp_reg_590;
reg   [0:0] tmp_reg_590_pp0_iter2_reg;
reg   [0:0] tmp_reg_590_pp0_iter3_reg;
reg   [0:0] tmp_reg_590_pp0_iter4_reg;
reg   [0:0] tmp_reg_590_pp0_iter5_reg;
reg   [0:0] tmp_reg_590_pp0_iter6_reg;
reg   [0:0] tmp_reg_590_pp0_iter7_reg;
reg   [0:0] tmp_reg_590_pp0_iter8_reg;
reg   [0:0] tmp_reg_590_pp0_iter9_reg;
reg   [0:0] tmp_reg_590_pp0_iter10_reg;
reg   [0:0] tmp_reg_590_pp0_iter11_reg;
wire   [6:0] empty_155_fu_348_p1;
reg   [3:0] tmp_2_reg_599;
reg   [3:0] tmp_2_reg_599_pp0_iter2_reg;
reg   [3:0] tmp_2_reg_599_pp0_iter3_reg;
reg   [3:0] tmp_2_reg_599_pp0_iter4_reg;
reg   [3:0] tmp_2_reg_599_pp0_iter5_reg;
reg   [3:0] tmp_2_reg_599_pp0_iter6_reg;
reg   [3:0] tmp_2_reg_599_pp0_iter7_reg;
reg   [3:0] tmp_2_reg_599_pp0_iter8_reg;
reg   [3:0] tmp_2_reg_599_pp0_iter9_reg;
reg   [3:0] tmp_2_reg_599_pp0_iter10_reg;
reg   [3:0] tmp_2_reg_599_pp0_iter11_reg;
reg   [0:0] tmp_3_reg_604;
wire   [1:0] empty_158_fu_438_p1;
reg   [1:0] empty_158_reg_608;
reg   [1:0] tmp_5_reg_612;
reg    ap_condition_exit_pp0_iter11_stage0;
wire   [63:0] p_cast2_fu_530_p1;
wire    ap_block_pp0_stage0;
reg   [9:0] phi_urem583_fu_100;
wire   [9:0] idx_urem585_fu_464_p3;
wire    ap_loop_init;
reg   [9:0] phi_urem580_fu_104;
wire   [9:0] idx_urem582_fu_390_p3;
reg   [20:0] phi_mul578_fu_108;
wire   [20:0] next_mul579_fu_483_p2;
reg   [20:0] phi_mul576_fu_112;
wire   [20:0] next_mul577_fu_334_p2;
reg   [9:0] empty_fu_116;
wire   [9:0] empty_152_fu_325_p2;
wire   [6:0] mul123_fu_356_p0;
wire   [8:0] mul123_fu_356_p1;
wire   [14:0] mul123_fu_356_p2;
wire   [4:0] grp_fu_372_p1;
wire   [9:0] next_urem581_fu_378_p2;
wire   [0:0] empty_154_fu_384_p2;
wire   [3:0] grp_fu_372_p2;
wire   [3:0] empty_157_fu_416_p1;
wire   [3:0] mul120_fu_424_p0;
wire   [5:0] mul120_fu_424_p1;
wire   [8:0] mul120_fu_424_p2;
wire   [9:0] next_urem584_fu_452_p2;
wire   [0:0] empty_153_fu_458_p2;
wire   [1:0] tmp_4_fu_489_p4;
wire   [4:0] tmp_30_cast_fu_499_p3;
wire   [4:0] tmp_28_cast_fu_480_p1;
wire   [4:0] empty_159_fu_507_p2;
wire   [5:0] tmp_s_fu_513_p3;
wire   [5:0] tmp_33_cast_fu_521_p1;
wire   [5:0] empty_160_fu_524_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [8:0] mul120_fu_424_p00;
wire   [14:0] mul123_fu_356_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv_bn_relu_mul_7ns_9ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 15 ))
mul_7ns_9ns_15_1_1_U29(
    .din0(mul123_fu_356_p0),
    .din1(mul123_fu_356_p1),
    .dout(mul123_fu_356_p2)
);

conv_bn_relu_urem_7ns_5ns_4_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 11 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
urem_7ns_5ns_4_11_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(empty_155_fu_348_p1),
    .din1(grp_fu_372_p1),
    .ce(1'b1),
    .dout(grp_fu_372_p2)
);

conv_bn_relu_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U31(
    .din0(mul120_fu_424_p0),
    .din1(mul120_fu_424_p1),
    .dout(mul120_fu_424_p2)
);

conv_bn_relu_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter11_stage0)) begin
            ap_enable_reg_pp0_iter12 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_fu_116 <= 10'd0;
        end else if (((exitcond360614_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_fu_116 <= empty_152_fu_325_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_mul576_fu_112 <= 21'd0;
        end else if (((exitcond360614_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            phi_mul576_fu_112 <= next_mul577_fu_334_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            phi_mul578_fu_108 <= 21'd0;
        end else if ((ap_enable_reg_pp0_iter12 == 1'b1)) begin
            phi_mul578_fu_108 <= next_mul579_fu_483_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_urem580_fu_104 <= 10'd0;
        end else if (((exitcond360614_fu_319_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            phi_urem580_fu_104 <= idx_urem582_fu_390_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            phi_urem583_fu_100 <= 10'd0;
        end else if (((ap_enable_reg_pp0_iter11 == 1'b1) & (exitcond360614_reg_586_pp0_iter10_reg == 1'd0))) begin
            phi_urem583_fu_100 <= idx_urem585_fu_464_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        exitcond360614_reg_586_pp0_iter10_reg <= exitcond360614_reg_586_pp0_iter9_reg;
        exitcond360614_reg_586_pp0_iter2_reg <= exitcond360614_reg_586;
        exitcond360614_reg_586_pp0_iter3_reg <= exitcond360614_reg_586_pp0_iter2_reg;
        exitcond360614_reg_586_pp0_iter4_reg <= exitcond360614_reg_586_pp0_iter3_reg;
        exitcond360614_reg_586_pp0_iter5_reg <= exitcond360614_reg_586_pp0_iter4_reg;
        exitcond360614_reg_586_pp0_iter6_reg <= exitcond360614_reg_586_pp0_iter5_reg;
        exitcond360614_reg_586_pp0_iter7_reg <= exitcond360614_reg_586_pp0_iter6_reg;
        exitcond360614_reg_586_pp0_iter8_reg <= exitcond360614_reg_586_pp0_iter7_reg;
        exitcond360614_reg_586_pp0_iter9_reg <= exitcond360614_reg_586_pp0_iter8_reg;
        tmp_2_reg_599_pp0_iter10_reg <= tmp_2_reg_599_pp0_iter9_reg;
        tmp_2_reg_599_pp0_iter11_reg <= tmp_2_reg_599_pp0_iter10_reg;
        tmp_2_reg_599_pp0_iter2_reg <= tmp_2_reg_599;
        tmp_2_reg_599_pp0_iter3_reg <= tmp_2_reg_599_pp0_iter2_reg;
        tmp_2_reg_599_pp0_iter4_reg <= tmp_2_reg_599_pp0_iter3_reg;
        tmp_2_reg_599_pp0_iter5_reg <= tmp_2_reg_599_pp0_iter4_reg;
        tmp_2_reg_599_pp0_iter6_reg <= tmp_2_reg_599_pp0_iter5_reg;
        tmp_2_reg_599_pp0_iter7_reg <= tmp_2_reg_599_pp0_iter6_reg;
        tmp_2_reg_599_pp0_iter8_reg <= tmp_2_reg_599_pp0_iter7_reg;
        tmp_2_reg_599_pp0_iter9_reg <= tmp_2_reg_599_pp0_iter8_reg;
        tmp_reg_590_pp0_iter10_reg <= tmp_reg_590_pp0_iter9_reg;
        tmp_reg_590_pp0_iter11_reg <= tmp_reg_590_pp0_iter10_reg;
        tmp_reg_590_pp0_iter2_reg <= tmp_reg_590;
        tmp_reg_590_pp0_iter3_reg <= tmp_reg_590_pp0_iter2_reg;
        tmp_reg_590_pp0_iter4_reg <= tmp_reg_590_pp0_iter3_reg;
        tmp_reg_590_pp0_iter5_reg <= tmp_reg_590_pp0_iter4_reg;
        tmp_reg_590_pp0_iter6_reg <= tmp_reg_590_pp0_iter5_reg;
        tmp_reg_590_pp0_iter7_reg <= tmp_reg_590_pp0_iter6_reg;
        tmp_reg_590_pp0_iter8_reg <= tmp_reg_590_pp0_iter7_reg;
        tmp_reg_590_pp0_iter9_reg <= tmp_reg_590_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        exitcond360614_reg_586 <= exitcond360614_fu_319_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond360614_reg_586_pp0_iter10_reg == 1'd0))) begin
        empty_158_reg_608 <= empty_158_fu_438_p1;
        tmp_3_reg_604 <= mul120_fu_424_p2[32'd6];
        tmp_5_reg_612 <= {{mul120_fu_424_p2[8:7]}};
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond360614_fu_319_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_2_reg_599 <= {{mul123_fu_356_p2[14:11]}};
        tmp_reg_590 <= phi_mul576_fu_112[32'd17];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter11 == 1'b1) & (exitcond360614_reg_586_pp0_iter10_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter11_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter11_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond360614_fu_319_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_10_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (empty_158_reg_608 == 2'd1) & (tmp_3_reg_604 == 1'd1) & (tmp_reg_590_pp0_iter11_reg == 1'd1))) begin
        local_conv_kernel_blk_10_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_11_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(empty_158_reg_608 == 2'd0) & ~(empty_158_reg_608 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (tmp_3_reg_604 == 1'd1) & (tmp_reg_590_pp0_iter11_reg == 1'd1))) begin
        local_conv_kernel_blk_11_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_1_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (empty_158_reg_608 == 2'd1) & (tmp_3_reg_604 == 1'd0) & (tmp_reg_590_pp0_iter11_reg == 1'd0))) begin
        local_conv_kernel_blk_1_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_2_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(empty_158_reg_608 == 2'd0) & ~(empty_158_reg_608 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (tmp_3_reg_604 == 1'd0) & (tmp_reg_590_pp0_iter11_reg == 1'd0))) begin
        local_conv_kernel_blk_2_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_3_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (empty_158_reg_608 == 2'd0) & (tmp_3_reg_604 == 1'd1) & (tmp_reg_590_pp0_iter11_reg == 1'd0))) begin
        local_conv_kernel_blk_3_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_4_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (empty_158_reg_608 == 2'd1) & (tmp_3_reg_604 == 1'd1) & (tmp_reg_590_pp0_iter11_reg == 1'd0))) begin
        local_conv_kernel_blk_4_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_5_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(empty_158_reg_608 == 2'd0) & ~(empty_158_reg_608 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (tmp_3_reg_604 == 1'd1) & (tmp_reg_590_pp0_iter11_reg == 1'd0))) begin
        local_conv_kernel_blk_5_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_6_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (empty_158_reg_608 == 2'd0) & (tmp_3_reg_604 == 1'd0) & (tmp_reg_590_pp0_iter11_reg == 1'd1))) begin
        local_conv_kernel_blk_6_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_7_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (empty_158_reg_608 == 2'd1) & (tmp_3_reg_604 == 1'd0) & (tmp_reg_590_pp0_iter11_reg == 1'd1))) begin
        local_conv_kernel_blk_7_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_8_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(empty_158_reg_608 == 2'd0) & ~(empty_158_reg_608 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (tmp_3_reg_604 == 1'd0) & (tmp_reg_590_pp0_iter11_reg == 1'd1))) begin
        local_conv_kernel_blk_8_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_9_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (empty_158_reg_608 == 2'd0) & (tmp_3_reg_604 == 1'd1) & (tmp_reg_590_pp0_iter11_reg == 1'd1))) begin
        local_conv_kernel_blk_9_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        local_conv_kernel_blk_ce0 = 1'b1;
    end else begin
        local_conv_kernel_blk_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (empty_158_reg_608 == 2'd0) & (tmp_3_reg_604 == 1'd0) & (tmp_reg_590_pp0_iter11_reg == 1'd0))) begin
        local_conv_kernel_blk_we0 = 1'b1;
    end else begin
        local_conv_kernel_blk_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign empty_152_fu_325_p2 = (empty_fu_116 + 10'd1);

assign empty_153_fu_458_p2 = ((next_urem584_fu_452_p2 < 10'd3) ? 1'b1 : 1'b0);

assign empty_154_fu_384_p2 = ((next_urem581_fu_378_p2 < 10'd72) ? 1'b1 : 1'b0);

assign empty_155_fu_348_p1 = phi_urem580_fu_104[6:0];

assign empty_157_fu_416_p1 = grp_fu_372_p2[3:0];

assign empty_158_fu_438_p1 = phi_urem583_fu_100[1:0];

assign empty_159_fu_507_p2 = (tmp_30_cast_fu_499_p3 + tmp_28_cast_fu_480_p1);

assign empty_160_fu_524_p2 = (tmp_s_fu_513_p3 + tmp_33_cast_fu_521_p1);

assign exitcond360614_fu_319_p2 = ((empty_fu_116 == 10'd576) ? 1'b1 : 1'b0);

assign grp_fu_372_p1 = 7'd9;

assign idx_urem582_fu_390_p3 = ((empty_154_fu_384_p2[0:0] == 1'b1) ? next_urem581_fu_378_p2 : 10'd0);

assign idx_urem585_fu_464_p3 = ((empty_153_fu_458_p2[0:0] == 1'b1) ? next_urem584_fu_452_p2 : 10'd0);

assign local_conv_kernel_blk_10_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_10_d0 = 32'd0;

assign local_conv_kernel_blk_11_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_11_d0 = 32'd0;

assign local_conv_kernel_blk_1_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_1_d0 = 32'd0;

assign local_conv_kernel_blk_2_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_2_d0 = 32'd0;

assign local_conv_kernel_blk_3_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_3_d0 = 32'd0;

assign local_conv_kernel_blk_4_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_4_d0 = 32'd0;

assign local_conv_kernel_blk_5_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_5_d0 = 32'd0;

assign local_conv_kernel_blk_6_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_6_d0 = 32'd0;

assign local_conv_kernel_blk_7_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_7_d0 = 32'd0;

assign local_conv_kernel_blk_8_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_8_d0 = 32'd0;

assign local_conv_kernel_blk_9_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_9_d0 = 32'd0;

assign local_conv_kernel_blk_address0 = p_cast2_fu_530_p1;

assign local_conv_kernel_blk_d0 = 32'd0;

assign mul120_fu_424_p0 = mul120_fu_424_p00;

assign mul120_fu_424_p00 = empty_157_fu_416_p1;

assign mul120_fu_424_p1 = 9'd22;

assign mul123_fu_356_p0 = mul123_fu_356_p00;

assign mul123_fu_356_p00 = empty_155_fu_348_p1;

assign mul123_fu_356_p1 = 15'd228;

assign next_mul577_fu_334_p2 = (phi_mul576_fu_112 + 21'd1821);

assign next_mul579_fu_483_p2 = (phi_mul578_fu_108 + 21'd1821);

assign next_urem581_fu_378_p2 = (phi_urem580_fu_104 + 10'd1);

assign next_urem584_fu_452_p2 = (phi_urem583_fu_100 + 10'd1);

assign p_cast2_fu_530_p1 = empty_160_fu_524_p2;

assign tmp_28_cast_fu_480_p1 = tmp_2_reg_599_pp0_iter11_reg;

assign tmp_30_cast_fu_499_p3 = {{tmp_4_fu_489_p4}, {3'd0}};

assign tmp_33_cast_fu_521_p1 = tmp_5_reg_612;

assign tmp_4_fu_489_p4 = {{phi_mul578_fu_108[19:18]}};

assign tmp_s_fu_513_p3 = {{empty_159_fu_507_p2}, {1'd0}};

endmodule //conv_bn_relu_Block_entry352_proc1_Pipeline_4
