# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_1/design_1_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_1 || ORIG_REF_NAME==design_1_smartconnect_0_1} -quiet] -quiet

# Block Designs: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/bd_886d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_0/bd_886d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_2/bd_886d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_3/bd_886d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_4/bd_886d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_5/bd_886d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_6/bd_886d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_7/bd_886d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_8/bd_886d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_9/bd_886d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_10/bd_886d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_11/bd_886d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_12/bd_886d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_1_0/design_1_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_1_0 || ORIG_REF_NAME==design_1_smartconnect_1_0} -quiet] -quiet

# Block Designs: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/bd_88fd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_0/bd_88fd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_2/bd_88fd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_3/bd_88fd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_4/bd_88fd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_5/bd_88fd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_6/bd_88fd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_7/bd_88fd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_8/bd_88fd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_9/bd_88fd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_10/bd_88fd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_11/bd_88fd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_12/bd_88fd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_2_0/design_1_smartconnect_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_2_0 || ORIG_REF_NAME==design_1_smartconnect_2_0} -quiet] -quiet

# Block Designs: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/bd_880d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_0/bd_880d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_1/bd_880d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_2/bd_880d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_3/bd_880d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_4/bd_880d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_5/bd_880d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_6/bd_880d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_7/bd_880d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_8/bd_880d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_9/bd_880d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_10/bd_880d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_11/bd_880d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_12/bd_880d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_pooling_0_1/design_1_pooling_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pooling_0_1 || ORIG_REF_NAME==design_1_pooling_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fully_connected_0_1/design_1_fully_connected_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fully_connected_0_1 || ORIG_REF_NAME==design_1_fully_connected_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_conv_bn_relu_0_3/design_1_conv_bn_relu_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_conv_bn_relu_0_3 || ORIG_REF_NAME==design_1_conv_bn_relu_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_channel_shuffle_0_7/design_1_channel_shuffle_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_channel_shuffle_0_7 || ORIG_REF_NAME==design_1_channel_shuffle_0_7} -quiet] -quiet

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_s00a2s_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_sarn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_srn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_sawn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_swn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_sbn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_m00s2a_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_5/bd_886d_s00a2s_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_6/bd_886d_sarn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_7/bd_886d_srn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_8/bd_886d_sawn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_9/bd_886d_swn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_10/bd_886d_sbn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_11/bd_886d_m00s2a_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_5/bd_88fd_s00a2s_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_6/bd_88fd_sarn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_7/bd_88fd_srn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_8/bd_88fd_sawn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_9/bd_88fd_swn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_10/bd_88fd_sbn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_11/bd_88fd_m00s2a_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_1/bd_880d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_1/bd_880d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_5/bd_880d_s00a2s_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_6/bd_880d_sarn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_7/bd_880d_srn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_8/bd_880d_sawn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_9/bd_880d_swn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_10/bd_880d_sbn_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/bd_0/ip/ip_11/bd_880d_m00s2a_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_smartconnect_2_0/ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_pooling_0_1/constraints/pooling_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fully_connected_0_1/constraints/fully_connected_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_conv_bn_relu_0_3/constraints/conv_bn_relu_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_channel_shuffle_0_7/constraints/channel_shuffle_ooc.xdc

# XDC: c:/Users/11400/Desktop/shuffletest/vivado/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
