// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pooling_pooling,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3895,HLS_SYN_LUT=4893,HLS_VERSION=2022_2}" *)

module pooling (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 79'd1;
parameter    ap_ST_fsm_state2 = 79'd2;
parameter    ap_ST_fsm_state3 = 79'd4;
parameter    ap_ST_fsm_state4 = 79'd8;
parameter    ap_ST_fsm_state5 = 79'd16;
parameter    ap_ST_fsm_state6 = 79'd32;
parameter    ap_ST_fsm_state7 = 79'd64;
parameter    ap_ST_fsm_state8 = 79'd128;
parameter    ap_ST_fsm_state9 = 79'd256;
parameter    ap_ST_fsm_state10 = 79'd512;
parameter    ap_ST_fsm_state11 = 79'd1024;
parameter    ap_ST_fsm_state12 = 79'd2048;
parameter    ap_ST_fsm_state13 = 79'd4096;
parameter    ap_ST_fsm_state14 = 79'd8192;
parameter    ap_ST_fsm_state15 = 79'd16384;
parameter    ap_ST_fsm_state16 = 79'd32768;
parameter    ap_ST_fsm_state17 = 79'd65536;
parameter    ap_ST_fsm_state18 = 79'd131072;
parameter    ap_ST_fsm_state19 = 79'd262144;
parameter    ap_ST_fsm_state20 = 79'd524288;
parameter    ap_ST_fsm_state21 = 79'd1048576;
parameter    ap_ST_fsm_state22 = 79'd2097152;
parameter    ap_ST_fsm_state23 = 79'd4194304;
parameter    ap_ST_fsm_state24 = 79'd8388608;
parameter    ap_ST_fsm_state25 = 79'd16777216;
parameter    ap_ST_fsm_state26 = 79'd33554432;
parameter    ap_ST_fsm_state27 = 79'd67108864;
parameter    ap_ST_fsm_state28 = 79'd134217728;
parameter    ap_ST_fsm_state29 = 79'd268435456;
parameter    ap_ST_fsm_state30 = 79'd536870912;
parameter    ap_ST_fsm_state31 = 79'd1073741824;
parameter    ap_ST_fsm_state32 = 79'd2147483648;
parameter    ap_ST_fsm_state33 = 79'd4294967296;
parameter    ap_ST_fsm_state34 = 79'd8589934592;
parameter    ap_ST_fsm_state35 = 79'd17179869184;
parameter    ap_ST_fsm_state36 = 79'd34359738368;
parameter    ap_ST_fsm_state37 = 79'd68719476736;
parameter    ap_ST_fsm_state38 = 79'd137438953472;
parameter    ap_ST_fsm_state39 = 79'd274877906944;
parameter    ap_ST_fsm_state40 = 79'd549755813888;
parameter    ap_ST_fsm_state41 = 79'd1099511627776;
parameter    ap_ST_fsm_state42 = 79'd2199023255552;
parameter    ap_ST_fsm_state43 = 79'd4398046511104;
parameter    ap_ST_fsm_state44 = 79'd8796093022208;
parameter    ap_ST_fsm_state45 = 79'd17592186044416;
parameter    ap_ST_fsm_state46 = 79'd35184372088832;
parameter    ap_ST_fsm_state47 = 79'd70368744177664;
parameter    ap_ST_fsm_state48 = 79'd140737488355328;
parameter    ap_ST_fsm_state49 = 79'd281474976710656;
parameter    ap_ST_fsm_state50 = 79'd562949953421312;
parameter    ap_ST_fsm_state51 = 79'd1125899906842624;
parameter    ap_ST_fsm_state52 = 79'd2251799813685248;
parameter    ap_ST_fsm_state53 = 79'd4503599627370496;
parameter    ap_ST_fsm_state54 = 79'd9007199254740992;
parameter    ap_ST_fsm_state55 = 79'd18014398509481984;
parameter    ap_ST_fsm_state56 = 79'd36028797018963968;
parameter    ap_ST_fsm_state57 = 79'd72057594037927936;
parameter    ap_ST_fsm_state58 = 79'd144115188075855872;
parameter    ap_ST_fsm_state59 = 79'd288230376151711744;
parameter    ap_ST_fsm_state60 = 79'd576460752303423488;
parameter    ap_ST_fsm_state61 = 79'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 79'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 79'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 79'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 79'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 79'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 79'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 79'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 79'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 79'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 79'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 79'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 79'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 79'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 79'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 79'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 79'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 79'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 79'd302231454903657293676544;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [78:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] C_in;
wire   [15:0] H_in;
wire   [15:0] W_in;
wire   [7:0] kernel_size;
wire   [7:0] stride;
wire   [7:0] padding;
wire   [0:0] pool_type;
wire   [63:0] feature_in;
wire   [63:0] feature_out;
reg    gmem0_blk_n_AW;
wire    ap_CS_fsm_state55;
reg    gmem0_blk_n_W;
wire    ap_CS_fsm_state74;
reg    gmem0_blk_n_B;
wire    ap_CS_fsm_state79;
reg   [63:0] feature_out_read_reg_785;
reg   [63:0] feature_in_read_reg_790;
reg   [0:0] pool_type_read_reg_796;
reg   [7:0] padding_read_reg_800;
reg   [7:0] stride_read_reg_805;
reg   [7:0] kernel_size_read_reg_810;
reg   [15:0] W_in_read_reg_817;
reg   [15:0] H_in_read_reg_825;
reg   [15:0] C_in_read_reg_831;
wire   [17:0] zext_ln1513_1_fu_338_p1;
wire   [15:0] W_out_V_fu_413_p2;
reg   [15:0] W_out_V_reg_873;
wire    ap_CS_fsm_state22;
wire   [31:0] conv_i_i707_fu_419_p1;
reg   [31:0] conv_i_i707_reg_879;
wire   [31:0] grp_fu_716_p2;
reg   [31:0] mul_ln15_1_reg_891;
wire    ap_CS_fsm_state25;
wire   [31:0] conv_i_i721_fu_427_p1;
reg   [31:0] conv_i_i721_reg_897;
wire    ap_CS_fsm_state26;
wire   [23:0] stride_cast2_fu_430_p1;
reg   [23:0] stride_cast2_reg_902;
wire   [24:0] zext_ln48_fu_433_p1;
reg   [24:0] zext_ln48_reg_909;
wire   [15:0] mul_ln15_fu_439_p2;
reg   [15:0] mul_ln15_reg_915;
wire   [47:0] mul_ln15_2_fu_451_p2;
reg   [47:0] mul_ln15_2_reg_921;
wire   [0:0] icmp_ln1027_fu_457_p2;
reg   [0:0] icmp_ln1027_reg_926;
wire    ap_CS_fsm_state27;
wire  signed [31:0] grp_fu_722_p2;
reg   [31:0] mul_ln1494_reg_944;
wire    ap_CS_fsm_state30;
wire  signed [23:0] grp_fu_727_p2;
reg   [23:0] empty_reg_949;
wire   [47:0] add_ln1027_fu_481_p2;
reg   [47:0] add_ln1027_reg_957;
wire   [0:0] icmp_ln1027_4_fu_490_p2;
reg   [0:0] icmp_ln1027_4_reg_965;
wire   [0:0] icmp_ln1027_3_fu_476_p2;
wire   [0:0] select_ln1633_4_fu_500_p3;
reg   [0:0] select_ln1633_4_reg_975;
wire    ap_CS_fsm_state31;
wire   [15:0] select_ln1027_3_fu_527_p3;
reg   [15:0] select_ln1027_3_reg_993;
wire   [15:0] select_ln1027_fu_538_p3;
reg   [15:0] select_ln1027_reg_998;
wire    ap_CS_fsm_state32;
wire   [24:0] sub_ln1027_fu_577_p2;
reg   [24:0] sub_ln1027_reg_1009;
wire    ap_CS_fsm_state34;
wire  signed [31:0] add_ln1494_fu_585_p2;
reg  signed [31:0] add_ln1494_reg_1015;
wire   [15:0] select_ln1633_1_fu_600_p3;
reg   [15:0] select_ln1633_1_reg_1020;
wire    ap_CS_fsm_state35;
wire   [31:0] mul_ln105_fu_607_p2;
reg   [31:0] mul_ln105_reg_1028;
wire   [24:0] grp_fu_744_p3;
reg   [24:0] sub_ln1496_reg_1033;
reg   [63:0] gmem0_addr_reg_1039;
wire    ap_CS_fsm_state36;
wire   [31:0] bitcast_ln106_fu_659_p1;
wire   [0:0] icmp_ln104_fu_710_p2;
reg   [0:0] icmp_ln104_reg_1059;
wire    ap_CS_fsm_state57;
wire   [31:0] grp_fu_296_p1;
reg   [31:0] conv1_reg_1063;
wire    ap_CS_fsm_state61;
wire   [31:0] grp_fu_292_p2;
reg   [31:0] div_reg_1068;
wire    ap_CS_fsm_state73;
wire    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_start;
wire    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_done;
wire    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_idle;
wire    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_ready;
wire    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWVALID;
wire   [63:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWADDR;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWID;
wire   [31:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWLEN;
wire   [2:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWBURST;
wire   [1:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWPROT;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWQOS;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWREGION;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWUSER;
wire    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WVALID;
wire   [31:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WDATA;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WSTRB;
wire    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WLAST;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WID;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WUSER;
wire    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARVALID;
wire   [63:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARADDR;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARID;
wire   [31:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARLEN;
wire   [2:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARBURST;
wire   [1:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARPROT;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARQOS;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARREGION;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARUSER;
wire    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_RREADY;
wire    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_BREADY;
wire   [31:0] grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_p_out;
wire    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_p_out_ap_vld;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_start;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_done;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_idle;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_ready;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWVALID;
wire   [63:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWADDR;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWID;
wire   [31:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWLEN;
wire   [2:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWBURST;
wire   [1:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWPROT;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWQOS;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWREGION;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWUSER;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WVALID;
wire   [31:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WDATA;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WSTRB;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WLAST;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WID;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WUSER;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARVALID;
wire   [63:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARADDR;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARID;
wire   [31:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARLEN;
wire   [2:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARBURST;
wire   [1:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARPROT;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARQOS;
wire   [3:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARREGION;
wire   [0:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARUSER;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_RREADY;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_BREADY;
wire   [31:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_count_1_out;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_count_1_out_ap_vld;
wire   [31:0] grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_sum_1_out;
wire    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_sum_1_out_ap_vld;
reg    gmem0_AWVALID;
wire    gmem0_AWREADY;
reg    gmem0_WVALID;
wire    gmem0_WREADY;
reg    gmem0_ARVALID;
wire    gmem0_ARREADY;
reg   [63:0] gmem0_ARADDR;
reg   [31:0] gmem0_ARLEN;
wire    gmem0_RVALID;
reg    gmem0_RREADY;
wire   [31:0] gmem0_RDATA;
wire   [8:0] gmem0_RFIFONUM;
wire    gmem0_BVALID;
reg    gmem0_BREADY;
reg   [31:0] ap_phi_mux_avg_val_phi_fu_240_p4;
reg   [31:0] avg_val_reg_236;
reg   [31:0] storemerge_reg_247;
reg    grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_start_reg;
wire    ap_CS_fsm_state37;
reg    grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_start_reg;
wire    ap_CS_fsm_state56;
wire  signed [63:0] sext_ln106_1_fu_646_p1;
reg   [15:0] w_out_1_fu_134;
wire   [15:0] w_out_fu_663_p2;
reg   [15:0] h_out_fu_138;
reg   [31:0] indvar_flatten21_fu_142;
wire   [31:0] select_ln1027_9_fu_674_p3;
reg   [15:0] c_fu_146;
reg   [47:0] indvar_flatten45_fu_150;
wire    ap_CS_fsm_state62;
wire   [8:0] shl_ln_fu_302_p3;
wire   [16:0] zext_ln1495_fu_310_p1;
wire   [16:0] zext_ln1496_fu_314_p1;
wire   [16:0] add_ln1496_fu_318_p2;
wire   [17:0] zext_ln1496_1_fu_324_p1;
wire   [17:0] zext_ln1513_fu_328_p1;
wire   [17:0] grp_fu_342_p0;
wire   [8:0] grp_fu_342_p1;
wire   [16:0] zext_ln1496_2_fu_348_p1;
wire   [16:0] add_ln1496_1_fu_352_p2;
wire   [17:0] zext_ln1513_2_fu_358_p1;
wire   [17:0] grp_fu_368_p0;
wire   [8:0] grp_fu_368_p1;
wire   [15:0] grp_fu_342_p2;
wire   [15:0] trunc_ln186_fu_399_p1;
wire   [15:0] grp_fu_368_p2;
wire   [15:0] trunc_ln186_1_fu_409_p1;
wire   [15:0] H_out_V_fu_403_p2;
wire   [7:0] mul_ln15_fu_439_p0;
wire   [15:0] zext_ln15_fu_436_p1;
wire   [7:0] mul_ln15_fu_439_p1;
wire   [15:0] mul_ln15_2_fu_451_p0;
wire   [31:0] mul_ln15_2_fu_451_p1;
wire   [0:0] icmp_ln1027_5_fu_495_p2;
wire   [15:0] select_ln1633_fu_507_p3;
wire   [15:0] h_out_3_fu_513_p2;
wire   [0:0] or_ln1027_fu_534_p2;
wire   [31:0] select_ln1027_1_fu_561_p1;
wire  signed [31:0] grp_fu_732_p2;
wire   [31:0] select_ln1633_2_fu_549_p3;
wire   [23:0] select_ln1027_2_fu_567_p1;
wire  signed [23:0] grp_fu_738_p2;
wire   [23:0] select_ln1633_3_fu_555_p3;
wire   [23:0] select_ln1027_2_fu_567_p3;
wire   [24:0] zext_ln1027_5_fu_573_p1;
wire   [31:0] zext_ln1633_1_fu_582_p1;
wire   [31:0] select_ln1027_1_fu_561_p3;
wire   [15:0] add_ln48_fu_594_p2;
wire   [15:0] mul_ln105_fu_607_p1;
wire   [31:0] zext_ln1633_fu_611_p1;
wire   [31:0] out_offset_fu_614_p2;
wire   [33:0] shl_ln1_fu_619_p3;
wire  signed [63:0] sext_ln106_fu_627_p1;
wire   [63:0] add_ln106_fu_631_p2;
wire   [61:0] trunc_ln1_fu_636_p4;
wire   [31:0] add_ln1027_1_fu_668_p2;
wire   [15:0] grp_fu_716_p0;
wire   [15:0] grp_fu_716_p1;
wire   [15:0] grp_fu_722_p0;
wire   [15:0] grp_fu_722_p1;
wire   [15:0] grp_fu_727_p0;
wire   [7:0] grp_fu_727_p1;
wire   [15:0] grp_fu_732_p0;
wire   [15:0] grp_fu_732_p1;
wire   [15:0] grp_fu_738_p0;
wire   [7:0] grp_fu_738_p1;
wire   [15:0] grp_fu_744_p0;
wire   [7:0] grp_fu_744_p1;
wire   [7:0] grp_fu_744_p2;
reg    grp_fu_342_ap_start;
wire    grp_fu_342_ap_done;
reg    grp_fu_368_ap_start;
wire    grp_fu_368_ap_done;
reg   [78:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
reg    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
reg    ap_ST_fsm_state55_blk;
reg    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
reg    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
reg    ap_ST_fsm_state79_blk;
wire   [31:0] grp_fu_716_p00;
wire   [31:0] grp_fu_716_p10;
wire   [31:0] grp_fu_722_p00;
wire   [23:0] grp_fu_727_p00;
wire   [31:0] grp_fu_732_p00;
wire   [23:0] grp_fu_738_p00;
wire   [23:0] grp_fu_744_p00;
wire   [47:0] mul_ln15_2_fu_451_p00;
wire   [47:0] mul_ln15_2_fu_451_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 79'd1;
#0 grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_start_reg = 1'b0;
#0 grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_start_reg = 1'b0;
end

pooling_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5 grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_start),
    .ap_done(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_done),
    .ap_idle(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_idle),
    .ap_ready(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_ready),
    .m_axi_gmem0_AWVALID(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(1'b0),
    .m_axi_gmem0_RID(1'd0),
    .m_axi_gmem0_RFIFONUM(gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(1'd0),
    .m_axi_gmem0_RRESP(2'd0),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .sub_ln1027(sub_ln1027_reg_1009),
    .H_in_cast4(H_in_read_reg_825),
    .mul_ln15(mul_ln15_reg_915),
    .kernel_size(kernel_size_read_reg_810),
    .conv_i_i530(W_in_read_reg_817),
    .sub_ln1496(sub_ln1496_reg_1033),
    .W_in_cast5(W_in_read_reg_817),
    .conv_i_i721(C_in_read_reg_831),
    .zext_ln1633(select_ln1633_1_reg_1020),
    .feature_in(feature_in_read_reg_790),
    .p_out(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_p_out),
    .p_out_ap_vld(grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_p_out_ap_vld)
);

pooling_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7 grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_start),
    .ap_done(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_done),
    .ap_idle(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_idle),
    .ap_ready(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_ready),
    .m_axi_gmem0_AWVALID(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(1'b0),
    .m_axi_gmem0_RID(1'd0),
    .m_axi_gmem0_RFIFONUM(gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(1'd0),
    .m_axi_gmem0_RRESP(2'd0),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .sub_ln1027(sub_ln1027_reg_1009),
    .H_in_cast4(H_in_read_reg_825),
    .mul_ln15(mul_ln15_reg_915),
    .kernel_size(kernel_size_read_reg_810),
    .conv_i_i530(W_in_read_reg_817),
    .sub_ln1496(sub_ln1496_reg_1033),
    .W_in_cast5(W_in_read_reg_817),
    .conv_i_i721(C_in_read_reg_831),
    .zext_ln1633(select_ln1633_1_reg_1020),
    .feature_in(feature_in_read_reg_790),
    .count_1_out(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_count_1_out),
    .count_1_out_ap_vld(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_count_1_out_ap_vld),
    .sum_1_out(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_sum_1_out),
    .sum_1_out_ap_vld(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_sum_1_out_ap_vld)
);

pooling_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .C_in(C_in),
    .W_in(W_in),
    .stride(stride),
    .pool_type(pool_type),
    .H_in(H_in),
    .kernel_size(kernel_size),
    .padding(padding),
    .feature_in(feature_in),
    .feature_out(feature_out),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

pooling_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(gmem0_ARADDR),
    .I_ARLEN(gmem0_ARLEN),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RFIFONUM(gmem0_RFIFONUM),
    .I_AWVALID(gmem0_AWVALID),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(gmem0_addr_reg_1039),
    .I_AWLEN(32'd1),
    .I_WVALID(gmem0_WVALID),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(storemerge_reg_247),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(gmem0_BREADY)
);

pooling_fdiv_32ns_32ns_32_12_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_12_no_dsp_1_U36(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_sum_1_out),
    .din1(conv1_reg_1063),
    .ce(1'b1),
    .dout(grp_fu_292_p2)
);

pooling_sitofp_32ns_32_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_5_no_dsp_1_U37(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_count_1_out),
    .ce(1'b1),
    .dout(grp_fu_296_p1)
);

pooling_sdiv_18ns_9ns_16_22_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 22 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
sdiv_18ns_9ns_16_22_seq_1_U38(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_342_ap_start),
    .done(grp_fu_342_ap_done),
    .din0(grp_fu_342_p0),
    .din1(grp_fu_342_p1),
    .ce(1'b1),
    .dout(grp_fu_342_p2)
);

pooling_sdiv_18ns_9ns_16_22_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 22 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
sdiv_18ns_9ns_16_22_seq_1_U39(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_368_ap_start),
    .done(grp_fu_368_ap_done),
    .din0(grp_fu_368_p0),
    .din1(grp_fu_368_p1),
    .ce(1'b1),
    .dout(grp_fu_368_p2)
);

pooling_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U40(
    .din0(mul_ln15_fu_439_p0),
    .din1(mul_ln15_fu_439_p1),
    .dout(mul_ln15_fu_439_p2)
);

pooling_mul_16ns_32ns_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_16ns_32ns_48_1_1_U41(
    .din0(mul_ln15_2_fu_451_p0),
    .din1(mul_ln15_2_fu_451_p1),
    .dout(mul_ln15_2_fu_451_p2)
);

pooling_mul_32s_16ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_32s_16ns_32_1_1_U42(
    .din0(add_ln1494_reg_1015),
    .din1(mul_ln105_fu_607_p1),
    .dout(mul_ln105_fu_607_p2)
);

pooling_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U43(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_716_p0),
    .din1(grp_fu_716_p1),
    .ce(1'b1),
    .dout(grp_fu_716_p2)
);

pooling_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U44(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_722_p0),
    .din1(grp_fu_722_p1),
    .ce(1'b1),
    .dout(grp_fu_722_p2)
);

pooling_mul_mul_16ns_8ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16ns_8ns_24_4_1_U45(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_727_p0),
    .din1(grp_fu_727_p1),
    .ce(1'b1),
    .dout(grp_fu_727_p2)
);

pooling_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U46(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_732_p0),
    .din1(grp_fu_732_p1),
    .ce(1'b1),
    .dout(grp_fu_732_p2)
);

pooling_mul_mul_16ns_8ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16ns_8ns_24_4_1_U47(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_738_p0),
    .din1(grp_fu_738_p1),
    .ce(1'b1),
    .dout(grp_fu_738_p2)
);

pooling_mac_mul_sub_16ns_8ns_8ns_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 25 ))
mac_mul_sub_16ns_8ns_8ns_25_4_1_U48(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_744_p0),
    .din1(grp_fu_744_p1),
    .din2(grp_fu_744_p2),
    .ce(1'b1),
    .dout(grp_fu_744_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state36) & (pool_type_read_reg_796 == 1'd0))) begin
            grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_start_reg <= 1'b1;
        end else if ((grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_ready == 1'b1)) begin
            grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state36) & (pool_type_read_reg_796 == 1'd1))) begin
            grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_start_reg <= 1'b1;
        end else if ((grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_ready == 1'b1)) begin
            grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln104_fu_710_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state57))) begin
        avg_val_reg_236 <= 32'd0;
    end else if (((gmem0_AWREADY == 1'b1) & (icmp_ln104_reg_1059 == 1'd1) & (1'b1 == ap_CS_fsm_state55) & (pool_type_read_reg_796 == 1'd1))) begin
        avg_val_reg_236 <= div_reg_1068;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        c_fu_146 <= 16'd0;
    end else if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
        c_fu_146 <= select_ln1633_1_reg_1020;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        h_out_fu_138 <= 16'd0;
    end else if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
        h_out_fu_138 <= select_ln1027_3_reg_993;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten21_fu_142 <= 32'd0;
    end else if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
        indvar_flatten21_fu_142 <= select_ln1027_9_fu_674_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten45_fu_150 <= 48'd0;
    end else if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
        indvar_flatten45_fu_150 <= add_ln1027_reg_957;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
        if ((pool_type_read_reg_796 == 1'd0)) begin
            storemerge_reg_247 <= grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_p_out;
        end else if ((pool_type_read_reg_796 == 1'd1)) begin
            storemerge_reg_247 <= bitcast_ln106_fu_659_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_out_1_fu_134 <= 16'd0;
    end else if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
        w_out_1_fu_134 <= w_out_fu_663_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        C_in_read_reg_831 <= C_in;
        H_in_read_reg_825 <= H_in;
        W_in_read_reg_817 <= W_in;
        feature_in_read_reg_790 <= feature_in;
        feature_out_read_reg_785 <= feature_out;
        kernel_size_read_reg_810 <= kernel_size;
        padding_read_reg_800 <= padding;
        pool_type_read_reg_796 <= pool_type;
        stride_read_reg_805 <= stride;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        W_out_V_reg_873 <= W_out_V_fu_413_p2;
        conv_i_i707_reg_879[15 : 0] <= conv_i_i707_fu_419_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        add_ln1027_reg_957 <= add_ln1027_fu_481_p2;
        empty_reg_949 <= grp_fu_727_p2;
        mul_ln1494_reg_944 <= grp_fu_722_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        add_ln1494_reg_1015 <= add_ln1494_fu_585_p2;
        sub_ln1027_reg_1009 <= sub_ln1027_fu_577_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        conv1_reg_1063 <= grp_fu_296_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        conv_i_i721_reg_897[15 : 0] <= conv_i_i721_fu_427_p1[15 : 0];
        icmp_ln1027_reg_926 <= icmp_ln1027_fu_457_p2;
        mul_ln15_2_reg_921 <= mul_ln15_2_fu_451_p2;
        mul_ln15_reg_915 <= mul_ln15_fu_439_p2;
        stride_cast2_reg_902[7 : 0] <= stride_cast2_fu_430_p1[7 : 0];
        zext_ln48_reg_909[7 : 0] <= zext_ln48_fu_433_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        div_reg_1068 <= grp_fu_292_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        gmem0_addr_reg_1039 <= sext_ln106_1_fu_646_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_3_fu_476_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state30))) begin
        icmp_ln1027_4_reg_965 <= icmp_ln1027_4_fu_490_p2;
        select_ln1633_4_reg_975 <= select_ln1633_4_fu_500_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        icmp_ln104_reg_1059 <= icmp_ln104_fu_710_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        mul_ln105_reg_1028 <= mul_ln105_fu_607_p2;
        select_ln1633_1_reg_1020 <= select_ln1633_1_fu_600_p3;
        sub_ln1496_reg_1033 <= grp_fu_744_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        mul_ln15_1_reg_891 <= grp_fu_716_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        select_ln1027_3_reg_993 <= select_ln1027_3_fu_527_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        select_ln1027_reg_998 <= select_ln1027_fu_538_p3;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

always @ (*) begin
    if ((grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_done == 1'b0)) begin
        ap_ST_fsm_state37_blk = 1'b1;
    end else begin
        ap_ST_fsm_state37_blk = 1'b0;
    end
end

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

always @ (*) begin
    if ((gmem0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state55_blk = 1'b1;
    end else begin
        ap_ST_fsm_state55_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_done == 1'b0)) begin
        ap_ST_fsm_state56_blk = 1'b1;
    end else begin
        ap_ST_fsm_state56_blk = 1'b0;
    end
end

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

always @ (*) begin
    if ((gmem0_WREADY == 1'b0)) begin
        ap_ST_fsm_state74_blk = 1'b1;
    end else begin
        ap_ST_fsm_state74_blk = 1'b0;
    end
end

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

always @ (*) begin
    if ((gmem0_BVALID == 1'b0)) begin
        ap_ST_fsm_state79_blk = 1'b1;
    end else begin
        ap_ST_fsm_state79_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln1027_3_fu_476_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln104_reg_1059 == 1'd1) & (1'b1 == ap_CS_fsm_state55) & (pool_type_read_reg_796 == 1'd1))) begin
        ap_phi_mux_avg_val_phi_fu_240_p4 = div_reg_1068;
    end else begin
        ap_phi_mux_avg_val_phi_fu_240_p4 = avg_val_reg_236;
    end
end

always @ (*) begin
    if (((icmp_ln1027_3_fu_476_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state56) | ((1'b1 == ap_CS_fsm_state36) & (pool_type_read_reg_796 == 1'd1)))) begin
        gmem0_ARADDR = grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state37) | ((1'b1 == ap_CS_fsm_state36) & (pool_type_read_reg_796 == 1'd0)))) begin
        gmem0_ARADDR = grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARADDR;
    end else begin
        gmem0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state56) | ((1'b1 == ap_CS_fsm_state36) & (pool_type_read_reg_796 == 1'd1)))) begin
        gmem0_ARLEN = grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state37) | ((1'b1 == ap_CS_fsm_state36) & (pool_type_read_reg_796 == 1'd0)))) begin
        gmem0_ARLEN = grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARLEN;
    end else begin
        gmem0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state56) | ((1'b1 == ap_CS_fsm_state36) & (pool_type_read_reg_796 == 1'd1)))) begin
        gmem0_ARVALID = grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state37) | ((1'b1 == ap_CS_fsm_state36) & (pool_type_read_reg_796 == 1'd0)))) begin
        gmem0_ARVALID = grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_ARVALID;
    end else begin
        gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
        gmem0_AWVALID = 1'b1;
    end else begin
        gmem0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state79))) begin
        gmem0_BREADY = 1'b1;
    end else begin
        gmem0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state56) | ((1'b1 == ap_CS_fsm_state36) & (pool_type_read_reg_796 == 1'd1)))) begin
        gmem0_RREADY = grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_m_axi_gmem0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state37) | ((1'b1 == ap_CS_fsm_state36) & (pool_type_read_reg_796 == 1'd0)))) begin
        gmem0_RREADY = grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_m_axi_gmem0_RREADY;
    end else begin
        gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state74))) begin
        gmem0_WVALID = 1'b1;
    end else begin
        gmem0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        gmem0_blk_n_AW = m_axi_gmem0_AWREADY;
    end else begin
        gmem0_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state79)) begin
        gmem0_blk_n_B = m_axi_gmem0_BVALID;
    end else begin
        gmem0_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        gmem0_blk_n_W = m_axi_gmem0_WREADY;
    end else begin
        gmem0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_342_ap_start = 1'b1;
    end else begin
        grp_fu_342_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_368_ap_start = 1'b1;
    end else begin
        grp_fu_368_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            if (((icmp_ln1027_3_fu_476_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            if (((1'b1 == ap_CS_fsm_state36) & (pool_type_read_reg_796 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        ap_ST_fsm_state37 : begin
            if (((grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state37))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end
        end
        ap_ST_fsm_state56 : begin
            if (((grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state56))) begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end
        end
        ap_ST_fsm_state57 : begin
            if (((icmp_ln104_fu_710_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state57))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state74 : begin
            if (((gmem0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state74))) begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            if (((gmem0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state79))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state79;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign H_out_V_fu_403_p2 = (trunc_ln186_fu_399_p1 + 16'd1);

assign W_out_V_fu_413_p2 = (trunc_ln186_1_fu_409_p1 + 16'd1);

assign add_ln1027_1_fu_668_p2 = (indvar_flatten21_fu_142 + 32'd1);

assign add_ln1027_fu_481_p2 = (indvar_flatten45_fu_150 + 48'd1);

assign add_ln106_fu_631_p2 = ($signed(sext_ln106_fu_627_p1) + $signed(feature_out_read_reg_785));

assign add_ln1494_fu_585_p2 = (zext_ln1633_1_fu_582_p1 + select_ln1027_1_fu_561_p3);

assign add_ln1496_1_fu_352_p2 = (zext_ln1495_fu_310_p1 + zext_ln1496_2_fu_348_p1);

assign add_ln1496_fu_318_p2 = (zext_ln1495_fu_310_p1 + zext_ln1496_fu_314_p1);

assign add_ln48_fu_594_p2 = (c_fu_146 + 16'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state79 = ap_CS_fsm[32'd78];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln106_fu_659_p1 = ap_phi_mux_avg_val_phi_fu_240_p4;

assign conv_i_i707_fu_419_p1 = W_out_V_fu_413_p2;

assign conv_i_i721_fu_427_p1 = C_in_read_reg_831;

assign grp_fu_342_p0 = (zext_ln1496_1_fu_324_p1 - zext_ln1513_fu_328_p1);

assign grp_fu_342_p1 = zext_ln1513_1_fu_338_p1;

assign grp_fu_368_p0 = (zext_ln1513_2_fu_358_p1 - zext_ln1513_fu_328_p1);

assign grp_fu_368_p1 = zext_ln1513_1_fu_338_p1;

assign grp_fu_716_p0 = grp_fu_716_p00;

assign grp_fu_716_p00 = H_out_V_fu_403_p2;

assign grp_fu_716_p1 = grp_fu_716_p10;

assign grp_fu_716_p10 = W_out_V_fu_413_p2;

assign grp_fu_722_p0 = grp_fu_722_p00;

assign grp_fu_722_p00 = h_out_fu_138;

assign grp_fu_722_p1 = conv_i_i707_reg_879;

assign grp_fu_727_p0 = grp_fu_727_p00;

assign grp_fu_727_p00 = h_out_fu_138;

assign grp_fu_727_p1 = stride_cast2_reg_902;

assign grp_fu_732_p0 = grp_fu_732_p00;

assign grp_fu_732_p00 = h_out_3_fu_513_p2;

assign grp_fu_732_p1 = conv_i_i707_reg_879;

assign grp_fu_738_p0 = grp_fu_738_p00;

assign grp_fu_738_p00 = h_out_3_fu_513_p2;

assign grp_fu_738_p1 = stride_cast2_reg_902;

assign grp_fu_744_p0 = grp_fu_744_p00;

assign grp_fu_744_p00 = select_ln1027_fu_538_p3;

assign grp_fu_744_p1 = stride_cast2_reg_902;

assign grp_fu_744_p2 = zext_ln48_reg_909;

assign grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_start = grp_pooling_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_58_5_fu_257_ap_start_reg;

assign grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_start = grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_ap_start_reg;

assign h_out_3_fu_513_p2 = (select_ln1633_fu_507_p3 + 16'd1);

assign icmp_ln1027_3_fu_476_p2 = ((indvar_flatten45_fu_150 == mul_ln15_2_reg_921) ? 1'b1 : 1'b0);

assign icmp_ln1027_4_fu_490_p2 = ((indvar_flatten21_fu_142 == mul_ln15_1_reg_891) ? 1'b1 : 1'b0);

assign icmp_ln1027_5_fu_495_p2 = ((w_out_1_fu_134 == W_out_V_reg_873) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_457_p2 = ((W_out_V_reg_873 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln104_fu_710_p2 = (($signed(grp_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7_fu_274_count_1_out) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign mul_ln105_fu_607_p1 = conv_i_i721_reg_897;

assign mul_ln15_2_fu_451_p0 = mul_ln15_2_fu_451_p00;

assign mul_ln15_2_fu_451_p00 = C_in_read_reg_831;

assign mul_ln15_2_fu_451_p1 = mul_ln15_2_fu_451_p10;

assign mul_ln15_2_fu_451_p10 = mul_ln15_1_reg_891;

assign mul_ln15_fu_439_p0 = zext_ln15_fu_436_p1;

assign mul_ln15_fu_439_p1 = zext_ln15_fu_436_p1;

assign or_ln1027_fu_534_p2 = (select_ln1633_4_reg_975 | icmp_ln1027_4_reg_965);

assign out_offset_fu_614_p2 = (mul_ln105_reg_1028 + zext_ln1633_fu_611_p1);

assign select_ln1027_1_fu_561_p1 = grp_fu_732_p2;

assign select_ln1027_1_fu_561_p3 = ((select_ln1633_4_reg_975[0:0] == 1'b1) ? select_ln1027_1_fu_561_p1 : select_ln1633_2_fu_549_p3);

assign select_ln1027_2_fu_567_p1 = grp_fu_738_p2;

assign select_ln1027_2_fu_567_p3 = ((select_ln1633_4_reg_975[0:0] == 1'b1) ? select_ln1027_2_fu_567_p1 : select_ln1633_3_fu_555_p3);

assign select_ln1027_3_fu_527_p3 = ((select_ln1633_4_reg_975[0:0] == 1'b1) ? h_out_3_fu_513_p2 : select_ln1633_fu_507_p3);

assign select_ln1027_9_fu_674_p3 = ((icmp_ln1027_4_reg_965[0:0] == 1'b1) ? 32'd1 : add_ln1027_1_fu_668_p2);

assign select_ln1027_fu_538_p3 = ((or_ln1027_fu_534_p2[0:0] == 1'b1) ? 16'd0 : w_out_1_fu_134);

assign select_ln1633_1_fu_600_p3 = ((icmp_ln1027_4_reg_965[0:0] == 1'b1) ? add_ln48_fu_594_p2 : c_fu_146);

assign select_ln1633_2_fu_549_p3 = ((icmp_ln1027_4_reg_965[0:0] == 1'b1) ? 32'd0 : mul_ln1494_reg_944);

assign select_ln1633_3_fu_555_p3 = ((icmp_ln1027_4_reg_965[0:0] == 1'b1) ? 24'd0 : empty_reg_949);

assign select_ln1633_4_fu_500_p3 = ((icmp_ln1027_4_fu_490_p2[0:0] == 1'b1) ? icmp_ln1027_reg_926 : icmp_ln1027_5_fu_495_p2);

assign select_ln1633_fu_507_p3 = ((icmp_ln1027_4_reg_965[0:0] == 1'b1) ? 16'd0 : h_out_fu_138);

assign sext_ln106_1_fu_646_p1 = $signed(trunc_ln1_fu_636_p4);

assign sext_ln106_fu_627_p1 = $signed(shl_ln1_fu_619_p3);

assign shl_ln1_fu_619_p3 = {{out_offset_fu_614_p2}, {2'd0}};

assign shl_ln_fu_302_p3 = {{padding}, {1'd0}};

assign stride_cast2_fu_430_p1 = stride_read_reg_805;

assign sub_ln1027_fu_577_p2 = (zext_ln1027_5_fu_573_p1 - zext_ln48_reg_909);

assign trunc_ln186_1_fu_409_p1 = grp_fu_368_p2[15:0];

assign trunc_ln186_fu_399_p1 = grp_fu_342_p2[15:0];

assign trunc_ln1_fu_636_p4 = {{add_ln106_fu_631_p2[63:2]}};

assign w_out_fu_663_p2 = (select_ln1027_reg_998 + 16'd1);

assign zext_ln1027_5_fu_573_p1 = select_ln1027_2_fu_567_p3;

assign zext_ln1495_fu_310_p1 = shl_ln_fu_302_p3;

assign zext_ln1496_1_fu_324_p1 = add_ln1496_fu_318_p2;

assign zext_ln1496_2_fu_348_p1 = W_in;

assign zext_ln1496_fu_314_p1 = H_in;

assign zext_ln1513_1_fu_338_p1 = stride;

assign zext_ln1513_2_fu_358_p1 = add_ln1496_1_fu_352_p2;

assign zext_ln1513_fu_328_p1 = kernel_size;

assign zext_ln15_fu_436_p1 = kernel_size_read_reg_810;

assign zext_ln1633_1_fu_582_p1 = select_ln1027_reg_998;

assign zext_ln1633_fu_611_p1 = select_ln1633_1_reg_1020;

assign zext_ln48_fu_433_p1 = padding_read_reg_800;

always @ (posedge ap_clk) begin
    conv_i_i707_reg_879[31:16] <= 16'b0000000000000000;
    conv_i_i721_reg_897[31:16] <= 16'b0000000000000000;
    stride_cast2_reg_902[23:8] <= 16'b0000000000000000;
    zext_ln48_reg_909[24:8] <= 17'b00000000000000000;
end

endmodule //pooling
