// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pooling_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        sub_ln1027,
        H_in_cast4,
        mul_ln15,
        kernel_size,
        conv_i_i530,
        sub_ln1496,
        W_in_cast5,
        conv_i_i721,
        zext_ln1633,
        feature_in,
        count_1_out,
        count_1_out_ap_vld,
        sum_1_out,
        sum_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [31:0] m_axi_gmem0_WDATA;
output  [3:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [31:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [24:0] sub_ln1027;
input  [15:0] H_in_cast4;
input  [15:0] mul_ln15;
input  [7:0] kernel_size;
input  [15:0] conv_i_i530;
input  [24:0] sub_ln1496;
input  [15:0] W_in_cast5;
input  [15:0] conv_i_i721;
input  [15:0] zext_ln1633;
input  [63:0] feature_in;
output  [31:0] count_1_out;
output   count_1_out_ap_vld;
output  [31:0] sum_1_out;
output   sum_1_out_ap_vld;

reg ap_idle;
reg m_axi_gmem0_ARVALID;
reg m_axi_gmem0_RREADY;
reg count_1_out_ap_vld;
reg sum_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state10_pp0_stage4_iter1;
wire    ap_block_state15_pp0_stage4_iter2;
wire    ap_block_state20_pp0_stage4_iter3;
wire    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln1027_reg_591;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] and_ln92_reg_636;
reg    gmem0_blk_n_R;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg   [0:0] and_ln92_reg_636_pp0_iter1_reg;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state11_pp0_stage0_iter2;
wire    ap_block_state16_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] zext_ln1633_cast_fu_210_p1;
reg   [31:0] zext_ln1633_cast_reg_566;
wire   [31:0] conv_i_i721_cast_fu_214_p1;
reg   [31:0] conv_i_i721_cast_reg_571;
wire   [24:0] W_in_cast5_cast_fu_218_p1;
reg   [24:0] W_in_cast5_cast_reg_576;
reg   [7:0] kh_1_reg_586;
wire   [0:0] icmp_ln1027_fu_285_p2;
reg   [0:0] icmp_ln1027_reg_591_pp0_iter1_reg;
reg   [0:0] icmp_ln1027_reg_591_pp0_iter2_reg;
wire   [15:0] add_ln1027_fu_291_p2;
reg   [15:0] add_ln1027_reg_595;
reg   [7:0] kw_1_load_reg_600;
wire   [0:0] icmp_ln1027_1_fu_300_p2;
reg   [0:0] icmp_ln1027_1_reg_605;
wire   [7:0] add_ln85_fu_306_p2;
reg   [7:0] add_ln85_reg_611;
wire   [0:0] and_ln92_1_fu_370_p2;
reg   [0:0] and_ln92_1_reg_621;
wire   [7:0] select_ln1027_fu_376_p3;
reg   [7:0] select_ln1027_reg_626;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state9_pp0_stage3_iter1;
reg    ap_block_state14_pp0_stage3_iter2;
wire    ap_block_state19_pp0_stage3_iter3;
reg    ap_block_pp0_stage3_11001;
wire   [7:0] select_ln1027_4_fu_382_p3;
reg   [7:0] select_ln1027_4_reg_631;
wire   [0:0] and_ln92_fu_405_p2;
reg   [0:0] and_ln92_reg_636_pp0_iter2_reg;
reg   [0:0] and_ln92_reg_636_pp0_iter3_reg;
(* use_dsp48 = "no" *) wire  signed [31:0] add_ln1494_fu_413_p2;
reg  signed [31:0] add_ln1494_reg_640;
wire   [31:0] mul_ln94_fu_429_p2;
reg   [31:0] mul_ln94_reg_645;
wire    ap_block_pp0_stage4_11001;
reg   [63:0] gmem0_addr_reg_650;
reg   [31:0] gmem0_addr_read_reg_656;
wire   [31:0] grp_fu_206_p2;
reg   [31:0] sum_1_reg_671;
reg    ap_enable_reg_pp0_iter0_reg;
wire  signed [63:0] sext_ln97_1_fu_482_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state7_pp0_stage1_iter1;
reg    ap_block_state7_io;
wire    ap_block_state12_pp0_stage1_iter2;
wire    ap_block_state17_pp0_stage1_iter3;
reg    ap_block_pp0_stage1_11001;
reg   [7:0] kw_1_fu_100;
wire   [7:0] kw_fu_433_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_kw_1_load;
reg   [7:0] kh_fu_104;
reg   [7:0] ap_sig_allocacmp_kh_1;
reg   [15:0] indvar_flatten10_fu_108;
reg   [15:0] ap_sig_allocacmp_indvar_flatten10_load;
reg   [31:0] sum_fu_112;
reg   [31:0] ap_sig_allocacmp_sum_load_1;
wire    ap_block_pp0_stage4;
reg   [31:0] count_fu_116;
wire   [31:0] count_1_fu_418_p2;
wire    ap_block_pp0_stage4_01001;
wire   [31:0] grp_fu_206_p1;
wire   [24:0] zext_ln1027_fu_261_p1;
wire   [24:0] h_in_fu_265_p2;
wire   [24:0] H_in_cast4_cast_fu_226_p1;
wire   [24:0] zext_ln1027_1_fu_312_p1;
wire   [24:0] h_in_mid1_fu_316_p2;
wire  signed [24:0] select_ln1027_1_fu_322_p3;
wire   [0:0] tmp_1_fu_334_p3;
wire   [0:0] tmp_fu_271_p3;
wire   [0:0] select_ln1027_2_fu_342_p3;
wire   [0:0] notrhs_mid1_fu_356_p2;
wire   [0:0] notrhs_fu_279_p2;
wire   [0:0] select_ln1027_3_fu_362_p3;
wire   [0:0] xor_ln1027_fu_350_p2;
wire   [24:0] kw_3_cast_fu_387_p1;
wire  signed [24:0] w_in_fu_391_p2;
wire   [0:0] icmp_ln92_fu_400_p2;
wire  signed [31:0] sext_ln89_fu_396_p1;
wire  signed [31:0] grp_fu_512_p2;
wire   [15:0] mul_ln94_fu_429_p1;
wire   [31:0] in_offset_fu_451_p2;
wire   [33:0] shl_ln2_fu_455_p3;
wire  signed [63:0] sext_ln97_fu_463_p1;
wire   [63:0] add_ln97_fu_467_p2;
wire   [61:0] trunc_ln2_fu_472_p4;
wire   [15:0] grp_fu_512_p1;
reg    grp_fu_206_ce;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state8_pp0_stage2_iter1;
wire    ap_block_state13_pp0_stage2_iter2;
wire    ap_block_state18_pp0_stage2_iter3;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage2;
reg    grp_fu_512_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [4:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to3;
reg    ap_done_pending_pp0;
reg    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [31:0] grp_fu_512_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

pooling_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_sig_allocacmp_sum_load_1),
    .din1(grp_fu_206_p1),
    .ce(grp_fu_206_ce),
    .dout(grp_fu_206_p2)
);

pooling_mul_32s_16ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_32s_16ns_32_1_1_U20(
    .din0(add_ln1494_reg_640),
    .din1(mul_ln94_fu_429_p1),
    .dout(mul_ln94_fu_429_p2)
);

pooling_mul_mul_25s_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_25s_16ns_32_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln1027_1_fu_322_p3),
    .din1(grp_fu_512_p1),
    .ce(grp_fu_512_ce),
    .dout(grp_fu_512_p2)
);

pooling_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        count_fu_116 <= 32'd0;
    end else if (((1'd1 == and_ln92_fu_405_p2) & (icmp_ln1027_reg_591 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        count_fu_116 <= count_1_fu_418_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten10_fu_108 <= 16'd0;
    end else if (((icmp_ln1027_reg_591 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        indvar_flatten10_fu_108 <= add_ln1027_reg_595;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kh_fu_104 <= 8'd0;
    end else if (((icmp_ln1027_reg_591 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        kh_fu_104 <= select_ln1027_4_reg_631;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kw_1_fu_100 <= 8'd0;
    end else if (((icmp_ln1027_reg_591 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        kw_1_fu_100 <= kw_fu_433_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_fu_112 <= 32'd0;
    end else if (((1'd1 == and_ln92_reg_636_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        sum_fu_112 <= sum_1_reg_671;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        W_in_cast5_cast_reg_576[15 : 0] <= W_in_cast5_cast_fu_218_p1[15 : 0];
        add_ln1027_reg_595 <= add_ln1027_fu_291_p2;
        conv_i_i721_cast_reg_571[15 : 0] <= conv_i_i721_cast_fu_214_p1[15 : 0];
        icmp_ln1027_reg_591 <= icmp_ln1027_fu_285_p2;
        icmp_ln1027_reg_591_pp0_iter1_reg <= icmp_ln1027_reg_591;
        icmp_ln1027_reg_591_pp0_iter2_reg <= icmp_ln1027_reg_591_pp0_iter1_reg;
        kh_1_reg_586 <= ap_sig_allocacmp_kh_1;
        zext_ln1633_cast_reg_566[15 : 0] <= zext_ln1633_cast_fu_210_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln92_fu_405_p2) & (icmp_ln1027_reg_591 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln1494_reg_640 <= add_ln1494_fu_413_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_fu_285_p2 == 1'd0))) begin
        add_ln85_reg_611 <= add_ln85_fu_306_p2;
        and_ln92_1_reg_621 <= and_ln92_1_fu_370_p2;
        icmp_ln1027_1_reg_605 <= icmp_ln1027_1_fu_300_p2;
        kw_1_load_reg_600 <= ap_sig_allocacmp_kw_1_load;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_reg_591 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        and_ln92_reg_636 <= and_ln92_fu_405_p2;
        select_ln1027_4_reg_631 <= select_ln1027_4_fu_382_p3;
        select_ln1027_reg_626 <= select_ln1027_fu_376_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        and_ln92_reg_636_pp0_iter1_reg <= and_ln92_reg_636;
        and_ln92_reg_636_pp0_iter2_reg <= and_ln92_reg_636_pp0_iter1_reg;
        and_ln92_reg_636_pp0_iter3_reg <= and_ln92_reg_636_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln92_reg_636_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        gmem0_addr_read_reg_656 <= m_axi_gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln92_reg_636) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem0_addr_reg_650 <= sext_ln97_1_fu_482_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln92_reg_636) & (icmp_ln1027_reg_591 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        mul_ln94_reg_645 <= mul_ln94_fu_429_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln92_reg_636_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        sum_1_reg_671 <= grp_fu_206_p2;
    end
end

always @ (*) begin
    if (((icmp_ln1027_reg_591 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten10_load = 16'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten10_load = indvar_flatten10_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_kh_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_kh_1 = kh_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_kw_1_load = 8'd0;
    end else begin
        ap_sig_allocacmp_kw_1_load = kw_1_fu_100;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln92_reg_636_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_sig_allocacmp_sum_load_1 = sum_1_reg_671;
    end else begin
        ap_sig_allocacmp_sum_load_1 = sum_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (icmp_ln1027_reg_591_pp0_iter2_reg == 1'd1))) begin
        count_1_out_ap_vld = 1'b1;
    end else begin
        count_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln92_reg_636) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln92_reg_636_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_206_ce = 1'b1;
    end else begin
        grp_fu_206_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_512_ce = 1'b1;
    end else begin
        grp_fu_512_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln92_reg_636) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m_axi_gmem0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln92_reg_636_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (icmp_ln1027_reg_591_pp0_iter2_reg == 1'd1))) begin
        sum_1_out_ap_vld = 1'b1;
    end else begin
        sum_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign H_in_cast4_cast_fu_226_p1 = H_in_cast4;

assign W_in_cast5_cast_fu_218_p1 = W_in_cast5;

assign add_ln1027_fu_291_p2 = (ap_sig_allocacmp_indvar_flatten10_load + 16'd1);

assign add_ln1494_fu_413_p2 = ($signed(sext_ln89_fu_396_p1) + $signed(grp_fu_512_p2));

assign add_ln85_fu_306_p2 = (ap_sig_allocacmp_kh_1 + 8'd1);

assign add_ln97_fu_467_p2 = ($signed(sext_ln97_fu_463_p1) + $signed(feature_in));

assign and_ln92_1_fu_370_p2 = (xor_ln1027_fu_350_p2 & select_ln1027_3_fu_362_p3);

assign and_ln92_fu_405_p2 = (icmp_ln92_fu_400_p2 & and_ln92_1_reg_621);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state7_io));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state7_io));
end

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((1'd1 == and_ln92_reg_636_pp0_iter1_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((1'd1 == and_ln92_reg_636_pp0_iter1_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_pp0_stage3_iter2 = ((1'd1 == and_ln92_reg_636_pp0_iter1_reg) & (m_axi_gmem0_RVALID == 1'b0));
end

assign ap_block_state15_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage4_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_io = ((m_axi_gmem0_ARREADY == 1'b0) & (1'd1 == and_ln92_reg_636));
end

assign ap_block_state7_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign conv_i_i721_cast_fu_214_p1 = conv_i_i721;

assign count_1_fu_418_p2 = (count_fu_116 + 32'd1);

assign count_1_out = count_fu_116;

assign grp_fu_206_p1 = gmem0_addr_read_reg_656;

assign grp_fu_512_p1 = grp_fu_512_p10;

assign grp_fu_512_p10 = conv_i_i530;

assign h_in_fu_265_p2 = (zext_ln1027_fu_261_p1 + sub_ln1027);

assign h_in_mid1_fu_316_p2 = (zext_ln1027_1_fu_312_p1 + sub_ln1027);

assign icmp_ln1027_1_fu_300_p2 = ((ap_sig_allocacmp_kw_1_load == kernel_size) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_285_p2 = ((ap_sig_allocacmp_indvar_flatten10_load == mul_ln15) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_400_p2 = ((w_in_fu_391_p2 < W_in_cast5_cast_reg_576) ? 1'b1 : 1'b0);

assign in_offset_fu_451_p2 = (mul_ln94_reg_645 + zext_ln1633_cast_reg_566);

assign kw_3_cast_fu_387_p1 = select_ln1027_fu_376_p3;

assign kw_fu_433_p2 = (select_ln1027_reg_626 + 8'd1);

assign m_axi_gmem0_ARADDR = gmem0_addr_reg_650;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd1;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 32'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 4'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign mul_ln94_fu_429_p1 = conv_i_i721_cast_reg_571;

assign notrhs_fu_279_p2 = (($signed(h_in_fu_265_p2) < $signed(H_in_cast4_cast_fu_226_p1)) ? 1'b1 : 1'b0);

assign notrhs_mid1_fu_356_p2 = (($signed(h_in_mid1_fu_316_p2) < $signed(H_in_cast4_cast_fu_226_p1)) ? 1'b1 : 1'b0);

assign select_ln1027_1_fu_322_p3 = ((icmp_ln1027_1_fu_300_p2[0:0] == 1'b1) ? h_in_mid1_fu_316_p2 : h_in_fu_265_p2);

assign select_ln1027_2_fu_342_p3 = ((icmp_ln1027_1_fu_300_p2[0:0] == 1'b1) ? tmp_1_fu_334_p3 : tmp_fu_271_p3);

assign select_ln1027_3_fu_362_p3 = ((icmp_ln1027_1_fu_300_p2[0:0] == 1'b1) ? notrhs_mid1_fu_356_p2 : notrhs_fu_279_p2);

assign select_ln1027_4_fu_382_p3 = ((icmp_ln1027_1_reg_605[0:0] == 1'b1) ? add_ln85_reg_611 : kh_1_reg_586);

assign select_ln1027_fu_376_p3 = ((icmp_ln1027_1_reg_605[0:0] == 1'b1) ? 8'd0 : kw_1_load_reg_600);

assign sext_ln89_fu_396_p1 = w_in_fu_391_p2;

assign sext_ln97_1_fu_482_p1 = $signed(trunc_ln2_fu_472_p4);

assign sext_ln97_fu_463_p1 = $signed(shl_ln2_fu_455_p3);

assign shl_ln2_fu_455_p3 = {{in_offset_fu_451_p2}, {2'd0}};

assign sum_1_out = sum_fu_112;

assign tmp_1_fu_334_p3 = h_in_mid1_fu_316_p2[32'd24];

assign tmp_fu_271_p3 = h_in_fu_265_p2[32'd24];

assign trunc_ln2_fu_472_p4 = {{add_ln97_fu_467_p2[63:2]}};

assign w_in_fu_391_p2 = (kw_3_cast_fu_387_p1 + sub_ln1496);

assign xor_ln1027_fu_350_p2 = (select_ln1027_2_fu_342_p3 ^ 1'd1);

assign zext_ln1027_1_fu_312_p1 = add_ln85_fu_306_p2;

assign zext_ln1027_fu_261_p1 = ap_sig_allocacmp_kh_1;

assign zext_ln1633_cast_fu_210_p1 = zext_ln1633;

always @ (posedge ap_clk) begin
    zext_ln1633_cast_reg_566[31:16] <= 16'b0000000000000000;
    conv_i_i721_cast_reg_571[31:16] <= 16'b0000000000000000;
    W_in_cast5_cast_reg_576[24:16] <= 9'b000000000;
end

endmodule //pooling_pooling_Pipeline_VITIS_LOOP_85_6_VITIS_LOOP_86_7
