// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module shufflenet_block_shufflenet_block_Pipeline_VITIS_LOOP_299_15 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_out_AWVALID,
        m_axi_gmem_out_AWREADY,
        m_axi_gmem_out_AWADDR,
        m_axi_gmem_out_AWID,
        m_axi_gmem_out_AWLEN,
        m_axi_gmem_out_AWSIZE,
        m_axi_gmem_out_AWBURST,
        m_axi_gmem_out_AWLOCK,
        m_axi_gmem_out_AWCACHE,
        m_axi_gmem_out_AWPROT,
        m_axi_gmem_out_AWQOS,
        m_axi_gmem_out_AWREGION,
        m_axi_gmem_out_AWUSER,
        m_axi_gmem_out_WVALID,
        m_axi_gmem_out_WREADY,
        m_axi_gmem_out_WDATA,
        m_axi_gmem_out_WSTRB,
        m_axi_gmem_out_WLAST,
        m_axi_gmem_out_WID,
        m_axi_gmem_out_WUSER,
        m_axi_gmem_out_ARVALID,
        m_axi_gmem_out_ARREADY,
        m_axi_gmem_out_ARADDR,
        m_axi_gmem_out_ARID,
        m_axi_gmem_out_ARLEN,
        m_axi_gmem_out_ARSIZE,
        m_axi_gmem_out_ARBURST,
        m_axi_gmem_out_ARLOCK,
        m_axi_gmem_out_ARCACHE,
        m_axi_gmem_out_ARPROT,
        m_axi_gmem_out_ARQOS,
        m_axi_gmem_out_ARREGION,
        m_axi_gmem_out_ARUSER,
        m_axi_gmem_out_RVALID,
        m_axi_gmem_out_RREADY,
        m_axi_gmem_out_RDATA,
        m_axi_gmem_out_RLAST,
        m_axi_gmem_out_RID,
        m_axi_gmem_out_RFIFONUM,
        m_axi_gmem_out_RUSER,
        m_axi_gmem_out_RRESP,
        m_axi_gmem_out_BVALID,
        m_axi_gmem_out_BREADY,
        m_axi_gmem_out_BRESP,
        m_axi_gmem_out_BID,
        m_axi_gmem_out_BUSER,
        bound73,
        h_w,
        empty,
        ret_V_9,
        out_r,
        icmp_ln298
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_out_AWVALID;
input   m_axi_gmem_out_AWREADY;
output  [63:0] m_axi_gmem_out_AWADDR;
output  [0:0] m_axi_gmem_out_AWID;
output  [31:0] m_axi_gmem_out_AWLEN;
output  [2:0] m_axi_gmem_out_AWSIZE;
output  [1:0] m_axi_gmem_out_AWBURST;
output  [1:0] m_axi_gmem_out_AWLOCK;
output  [3:0] m_axi_gmem_out_AWCACHE;
output  [2:0] m_axi_gmem_out_AWPROT;
output  [3:0] m_axi_gmem_out_AWQOS;
output  [3:0] m_axi_gmem_out_AWREGION;
output  [0:0] m_axi_gmem_out_AWUSER;
output   m_axi_gmem_out_WVALID;
input   m_axi_gmem_out_WREADY;
output  [7:0] m_axi_gmem_out_WDATA;
output  [0:0] m_axi_gmem_out_WSTRB;
output   m_axi_gmem_out_WLAST;
output  [0:0] m_axi_gmem_out_WID;
output  [0:0] m_axi_gmem_out_WUSER;
output   m_axi_gmem_out_ARVALID;
input   m_axi_gmem_out_ARREADY;
output  [63:0] m_axi_gmem_out_ARADDR;
output  [0:0] m_axi_gmem_out_ARID;
output  [31:0] m_axi_gmem_out_ARLEN;
output  [2:0] m_axi_gmem_out_ARSIZE;
output  [1:0] m_axi_gmem_out_ARBURST;
output  [1:0] m_axi_gmem_out_ARLOCK;
output  [3:0] m_axi_gmem_out_ARCACHE;
output  [2:0] m_axi_gmem_out_ARPROT;
output  [3:0] m_axi_gmem_out_ARQOS;
output  [3:0] m_axi_gmem_out_ARREGION;
output  [0:0] m_axi_gmem_out_ARUSER;
input   m_axi_gmem_out_RVALID;
output   m_axi_gmem_out_RREADY;
input  [7:0] m_axi_gmem_out_RDATA;
input   m_axi_gmem_out_RLAST;
input  [0:0] m_axi_gmem_out_RID;
input  [10:0] m_axi_gmem_out_RFIFONUM;
input  [0:0] m_axi_gmem_out_RUSER;
input  [1:0] m_axi_gmem_out_RRESP;
input   m_axi_gmem_out_BVALID;
output   m_axi_gmem_out_BREADY;
input  [1:0] m_axi_gmem_out_BRESP;
input  [0:0] m_axi_gmem_out_BID;
input  [0:0] m_axi_gmem_out_BUSER;
input  [46:0] bound73;
input  [15:0] h_w;
input  [31:0] empty;
input  [31:0] ret_V_9;
input  [63:0] out_r;
input  [0:0] icmp_ln298;

reg ap_idle;
reg m_axi_gmem_out_AWVALID;
reg m_axi_gmem_out_WVALID;
reg m_axi_gmem_out_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
reg   [0:0] or_ln1027_reg_501;
reg   [0:0] or_ln1027_reg_501_pp0_iter3_reg;
reg   [0:0] and_ln298_reg_505;
reg   [0:0] and_ln298_reg_505_pp0_iter3_reg;
reg    ap_predicate_op83_writereq_state5;
reg    ap_block_state5_io;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
reg   [0:0] icmp_ln1027_2_reg_510;
reg   [0:0] icmp_ln1027_2_reg_510_pp0_iter9_reg;
reg   [0:0] icmp_ln298_2_reg_519;
reg   [0:0] icmp_ln298_2_reg_519_pp0_iter9_reg;
reg    ap_predicate_op92_writeresp_state11;
reg    ap_block_state11_pp0_stage0_iter10;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1027_fu_213_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_out_blk_n_B;
wire    ap_block_pp0_stage0;
reg    gmem_out_blk_n_W;
reg    gmem_out_blk_n_AW;
reg   [0:0] first_iter_0_reg_156;
reg   [0:0] first_iter_028_reg_167;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln1027_reg_482;
wire   [0:0] icmp_ln298_1_fu_227_p2;
reg   [0:0] icmp_ln298_1_reg_486;
wire   [14:0] select_ln297_1_fu_244_p3;
reg   [14:0] select_ln297_1_reg_491;
wire   [0:0] select_ln297_2_fu_257_p3;
reg   [0:0] select_ln297_2_reg_496;
wire   [0:0] or_ln1027_fu_270_p2;
reg   [0:0] or_ln1027_reg_501_pp0_iter2_reg;
wire   [0:0] and_ln298_fu_282_p2;
reg   [0:0] and_ln298_reg_505_pp0_iter2_reg;
wire   [0:0] icmp_ln1027_2_fu_308_p2;
reg   [0:0] icmp_ln1027_2_reg_510_pp0_iter2_reg;
reg   [0:0] icmp_ln1027_2_reg_510_pp0_iter3_reg;
reg   [0:0] icmp_ln1027_2_reg_510_pp0_iter4_reg;
reg   [0:0] icmp_ln1027_2_reg_510_pp0_iter5_reg;
reg   [0:0] icmp_ln1027_2_reg_510_pp0_iter6_reg;
reg   [0:0] icmp_ln1027_2_reg_510_pp0_iter7_reg;
reg   [0:0] icmp_ln1027_2_reg_510_pp0_iter8_reg;
wire   [31:0] mul_ln297_fu_360_p2;
reg   [31:0] mul_ln297_reg_514;
wire   [0:0] icmp_ln298_2_fu_384_p2;
reg   [0:0] icmp_ln298_2_reg_519_pp0_iter3_reg;
reg   [0:0] icmp_ln298_2_reg_519_pp0_iter4_reg;
reg   [0:0] icmp_ln298_2_reg_519_pp0_iter5_reg;
reg   [0:0] icmp_ln298_2_reg_519_pp0_iter6_reg;
reg   [0:0] icmp_ln298_2_reg_519_pp0_iter7_reg;
reg   [0:0] icmp_ln298_2_reg_519_pp0_iter8_reg;
reg   [63:0] gmem_out_addr_reg_523;
reg   [0:0] ap_phi_mux_first_iter_0_phi_fu_160_p4;
wire    ap_loop_init;
reg   [0:0] ap_phi_mux_first_iter_028_phi_fu_171_p4;
wire   [63:0] add_ln297_fu_397_p2;
reg    ap_block_pp0_stage0_01001;
reg   [15:0] w_V_fu_80;
wire   [15:0] w_V_2_fu_300_p3;
reg   [15:0] indvar186_fu_84;
wire   [15:0] select_ln298_fu_371_p3;
reg   [31:0] indvar_flatten65_fu_88;
wire   [31:0] select_ln298_1_fu_319_p3;
reg   [14:0] c_V_fu_92;
reg   [46:0] indvar_flatten85_fu_96;
wire   [46:0] add_ln1027_fu_218_p2;
wire  signed [31:0] icmp_ln298_1_fu_227_p1;
wire   [14:0] add_ln840_fu_238_p2;
wire   [0:0] icmp_ln1027_1_fu_252_p2;
wire   [0:0] or_ln297_1_fu_264_p2;
wire   [0:0] or_ln297_fu_232_p2;
wire   [0:0] xor_ln298_fu_276_p2;
wire   [0:0] or_ln840_fu_294_p2;
wire   [15:0] add_ln840_1_fu_288_p2;
wire   [31:0] add_ln298_2_fu_313_p2;
wire   [14:0] mul_ln297_fu_360_p0;
wire   [15:0] select_ln297_fu_350_p3;
wire   [15:0] add_ln298_fu_365_p2;
wire   [15:0] add_ln298_1_fu_378_p2;
wire   [63:0] zext_ln297_1_fu_394_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [31:0] mul_ln297_fu_360_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_done_reg = 1'b0;
end

shufflenet_block_mul_15ns_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_15ns_32s_32_1_1_U14(
    .din0(mul_ln297_fu_360_p0),
    .din1(ret_V_9),
    .dout(mul_ln297_fu_360_p2)
);

shufflenet_block_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_V_fu_92 <= 15'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_fu_213_p2 == 1'd0))) begin
            c_V_fu_92 <= select_ln297_1_fu_244_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_reg_482 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_028_reg_167 <= 1'd0;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_028_reg_167 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_reg_482 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_0_reg_156 <= and_ln298_reg_505;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_0_reg_156 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            indvar186_fu_84 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_reg_482 == 1'd0))) begin
            indvar186_fu_84 <= select_ln298_fu_371_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten65_fu_88 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_fu_213_p2 == 1'd0))) begin
            indvar_flatten65_fu_88 <= select_ln298_1_fu_319_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten85_fu_96 <= 47'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_fu_213_p2 == 1'd0))) begin
            indvar_flatten85_fu_96 <= add_ln1027_fu_218_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_V_fu_80 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1027_fu_213_p2 == 1'd0))) begin
            w_V_fu_80 <= w_V_2_fu_300_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_fu_213_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln298_reg_505 <= and_ln298_fu_282_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln298_reg_505_pp0_iter2_reg <= and_ln298_reg_505;
        and_ln298_reg_505_pp0_iter3_reg <= and_ln298_reg_505_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln1027_2_reg_510_pp0_iter2_reg <= icmp_ln1027_2_reg_510;
        icmp_ln1027_2_reg_510_pp0_iter3_reg <= icmp_ln1027_2_reg_510_pp0_iter2_reg;
        icmp_ln1027_2_reg_510_pp0_iter4_reg <= icmp_ln1027_2_reg_510_pp0_iter3_reg;
        icmp_ln1027_2_reg_510_pp0_iter5_reg <= icmp_ln1027_2_reg_510_pp0_iter4_reg;
        icmp_ln1027_2_reg_510_pp0_iter6_reg <= icmp_ln1027_2_reg_510_pp0_iter5_reg;
        icmp_ln1027_2_reg_510_pp0_iter7_reg <= icmp_ln1027_2_reg_510_pp0_iter6_reg;
        icmp_ln1027_2_reg_510_pp0_iter8_reg <= icmp_ln1027_2_reg_510_pp0_iter7_reg;
        icmp_ln1027_2_reg_510_pp0_iter9_reg <= icmp_ln1027_2_reg_510_pp0_iter8_reg;
        icmp_ln298_2_reg_519_pp0_iter3_reg <= icmp_ln298_2_reg_519;
        icmp_ln298_2_reg_519_pp0_iter4_reg <= icmp_ln298_2_reg_519_pp0_iter3_reg;
        icmp_ln298_2_reg_519_pp0_iter5_reg <= icmp_ln298_2_reg_519_pp0_iter4_reg;
        icmp_ln298_2_reg_519_pp0_iter6_reg <= icmp_ln298_2_reg_519_pp0_iter5_reg;
        icmp_ln298_2_reg_519_pp0_iter7_reg <= icmp_ln298_2_reg_519_pp0_iter6_reg;
        icmp_ln298_2_reg_519_pp0_iter8_reg <= icmp_ln298_2_reg_519_pp0_iter7_reg;
        icmp_ln298_2_reg_519_pp0_iter9_reg <= icmp_ln298_2_reg_519_pp0_iter8_reg;
        or_ln1027_reg_501_pp0_iter2_reg <= or_ln1027_reg_501;
        or_ln1027_reg_501_pp0_iter3_reg <= or_ln1027_reg_501_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln1027_reg_482 <= icmp_ln1027_fu_213_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln1027_reg_501_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln298_reg_505_pp0_iter2_reg))) begin
        gmem_out_addr_reg_523 <= add_ln297_fu_397_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_fu_213_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln1027_2_reg_510 <= icmp_ln1027_2_fu_308_p2;
        icmp_ln298_1_reg_486 <= icmp_ln298_1_fu_227_p2;
        or_ln1027_reg_501 <= or_ln1027_fu_270_p2;
        select_ln297_1_reg_491 <= select_ln297_1_fu_244_p3;
        select_ln297_2_reg_496 <= select_ln297_2_fu_257_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1027_2_reg_510 == 1'd1))) begin
        icmp_ln298_2_reg_519 <= icmp_ln298_2_fu_384_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_reg_482 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln297_reg_514 <= mul_ln297_fu_360_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1027_fu_213_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_reg_482 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_028_phi_fu_171_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_028_phi_fu_171_p4 = first_iter_028_reg_167;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln1027_reg_482 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_0_phi_fu_160_p4 = and_ln298_reg_505;
    end else begin
        ap_phi_mux_first_iter_0_phi_fu_160_p4 = first_iter_0_reg_156;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op83_writereq_state5 == 1'b1))) begin
        gmem_out_blk_n_AW = m_axi_gmem_out_AWREADY;
    end else begin
        gmem_out_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op92_writeresp_state11 == 1'b1))) begin
        gmem_out_blk_n_B = m_axi_gmem_out_BVALID;
    end else begin
        gmem_out_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_out_blk_n_W = m_axi_gmem_out_WREADY;
    end else begin
        gmem_out_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op83_writereq_state5 == 1'b1))) begin
        m_axi_gmem_out_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_out_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op92_writeresp_state11 == 1'b1))) begin
        m_axi_gmem_out_BREADY = 1'b1;
    end else begin
        m_axi_gmem_out_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_out_WVALID = 1'b1;
    end else begin
        m_axi_gmem_out_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1027_fu_218_p2 = (indvar_flatten85_fu_96 + 47'd1);

assign add_ln297_fu_397_p2 = (zext_ln297_1_fu_394_p1 + out_r);

assign add_ln298_1_fu_378_p2 = (select_ln298_fu_371_p3 + 16'd1);

assign add_ln298_2_fu_313_p2 = (indvar_flatten65_fu_88 + 32'd1);

assign add_ln298_fu_365_p2 = (select_ln297_fu_350_p3 + 16'd1);

assign add_ln840_1_fu_288_p2 = (w_V_fu_80 + 16'd1);

assign add_ln840_fu_238_p2 = (c_V_fu_92 + 15'd1);

assign and_ln298_fu_282_p2 = (xor_ln298_fu_276_p2 & or_ln297_fu_232_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_op92_writeresp_state11 == 1'b1) & (m_axi_gmem_out_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_op92_writeresp_state11 == 1'b1) & (m_axi_gmem_out_BVALID == 1'b0)) | ((m_axi_gmem_out_WREADY == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter10 == 1'b1) & (ap_predicate_op92_writeresp_state11 == 1'b1) & (m_axi_gmem_out_BVALID == 1'b0)) | ((m_axi_gmem_out_WREADY == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp0_stage0_iter10 = ((ap_predicate_op92_writeresp_state11 == 1'b1) & (m_axi_gmem_out_BVALID == 1'b0));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((m_axi_gmem_out_AWREADY == 1'b0) & (ap_predicate_op83_writereq_state5 == 1'b1));
end

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

always @ (*) begin
    ap_predicate_op83_writereq_state5 = ((1'd1 == and_ln298_reg_505_pp0_iter3_reg) & (or_ln1027_reg_501_pp0_iter3_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op92_writeresp_state11 = ((icmp_ln298_2_reg_519_pp0_iter9_reg == 1'd1) & (icmp_ln1027_2_reg_510_pp0_iter9_reg == 1'd1));
end

assign icmp_ln1027_1_fu_252_p2 = ((w_V_fu_80 == h_w) ? 1'b1 : 1'b0);

assign icmp_ln1027_2_fu_308_p2 = ((w_V_2_fu_300_p3 == h_w) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_213_p2 = ((indvar_flatten85_fu_96 == bound73) ? 1'b1 : 1'b0);

assign icmp_ln298_1_fu_227_p1 = ret_V_9;

assign icmp_ln298_1_fu_227_p2 = ((indvar_flatten65_fu_88 == icmp_ln298_1_fu_227_p1) ? 1'b1 : 1'b0);

assign icmp_ln298_2_fu_384_p2 = ((add_ln298_1_fu_378_p2 == h_w) ? 1'b1 : 1'b0);

assign m_axi_gmem_out_ARADDR = 64'd0;

assign m_axi_gmem_out_ARBURST = 2'd0;

assign m_axi_gmem_out_ARCACHE = 4'd0;

assign m_axi_gmem_out_ARID = 1'd0;

assign m_axi_gmem_out_ARLEN = 32'd0;

assign m_axi_gmem_out_ARLOCK = 2'd0;

assign m_axi_gmem_out_ARPROT = 3'd0;

assign m_axi_gmem_out_ARQOS = 4'd0;

assign m_axi_gmem_out_ARREGION = 4'd0;

assign m_axi_gmem_out_ARSIZE = 3'd0;

assign m_axi_gmem_out_ARUSER = 1'd0;

assign m_axi_gmem_out_ARVALID = 1'b0;

assign m_axi_gmem_out_AWADDR = gmem_out_addr_reg_523;

assign m_axi_gmem_out_AWBURST = 2'd0;

assign m_axi_gmem_out_AWCACHE = 4'd0;

assign m_axi_gmem_out_AWID = 1'd0;

assign m_axi_gmem_out_AWLEN = empty;

assign m_axi_gmem_out_AWLOCK = 2'd0;

assign m_axi_gmem_out_AWPROT = 3'd0;

assign m_axi_gmem_out_AWQOS = 4'd0;

assign m_axi_gmem_out_AWREGION = 4'd0;

assign m_axi_gmem_out_AWSIZE = 3'd0;

assign m_axi_gmem_out_AWUSER = 1'd0;

assign m_axi_gmem_out_RREADY = 1'b0;

assign m_axi_gmem_out_WDATA = 8'd0;

assign m_axi_gmem_out_WID = 1'd0;

assign m_axi_gmem_out_WLAST = 1'b0;

assign m_axi_gmem_out_WSTRB = 1'd1;

assign m_axi_gmem_out_WUSER = 1'd0;

assign mul_ln297_fu_360_p0 = mul_ln297_fu_360_p00;

assign mul_ln297_fu_360_p00 = select_ln297_1_reg_491;

assign or_ln1027_fu_270_p2 = (select_ln297_2_fu_257_p3 | or_ln297_1_fu_264_p2);

assign or_ln297_1_fu_264_p2 = (icmp_ln298_1_fu_227_p2 | ap_phi_mux_first_iter_028_phi_fu_171_p4);

assign or_ln297_fu_232_p2 = (icmp_ln298_1_fu_227_p2 | ap_phi_mux_first_iter_0_phi_fu_160_p4);

assign or_ln840_fu_294_p2 = (select_ln297_2_fu_257_p3 | icmp_ln298_1_fu_227_p2);

assign select_ln297_1_fu_244_p3 = ((icmp_ln298_1_fu_227_p2[0:0] == 1'b1) ? add_ln840_fu_238_p2 : c_V_fu_92);

assign select_ln297_2_fu_257_p3 = ((icmp_ln298_1_fu_227_p2[0:0] == 1'b1) ? icmp_ln298 : icmp_ln1027_1_fu_252_p2);

assign select_ln297_fu_350_p3 = ((icmp_ln298_1_reg_486[0:0] == 1'b1) ? 16'd0 : indvar186_fu_84);

assign select_ln298_1_fu_319_p3 = ((icmp_ln298_1_fu_227_p2[0:0] == 1'b1) ? 32'd1 : add_ln298_2_fu_313_p2);

assign select_ln298_fu_371_p3 = ((select_ln297_2_reg_496[0:0] == 1'b1) ? add_ln298_fu_365_p2 : select_ln297_fu_350_p3);

assign w_V_2_fu_300_p3 = ((or_ln840_fu_294_p2[0:0] == 1'b1) ? 16'd1 : add_ln840_1_fu_288_p2);

assign xor_ln298_fu_276_p2 = (select_ln297_2_fu_257_p3 ^ 1'd1);

assign zext_ln297_1_fu_394_p1 = mul_ln297_reg_514;

endmodule //shufflenet_block_shufflenet_block_Pipeline_VITIS_LOOP_299_15
